### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by xhzengAIB** [forkingdog/UITableView-FDTemplateLayoutCell#1]
请问- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath这个方法是不是会调用两次呢？

**Comment by LengBinBin** [comment]
确实调用了两次，但是好像没有什么影响， `[tableView dequeueReusableCellWithIdentifier:@"FDFeedCell" forIndexPath:indexPath]` 获取的单条对象是只有一个的。

**Comment by xhzengAIB** [comment]
在效率上会不会比计算Cell的高度好很多啊？

在iOS7上可用吗？ 因为iOS8上有更方便的做法，动态计算Cell的高度，也是通过AutoLayout的。

**Comment by LengBinBin** [comment]
iOS 7 运行没问题， 感觉iOS 8上可能也是这个思路实现的。当然只是我的猜测

**Comment by xhzengAIB** [comment]
iOS8上的话，我在这个[项目](https://github.com/xhzengAIB/iOS8SelfSizingCells)里面用这新的方法，你觉得底层原理会不会和你这个一样啊？

**Comment by LengBinBin** [comment]
－ － 我不是作者啊！  我也是个路人。 。 。  而且， iOS 8的那个 属性好像不需要额外限制吧？ 约束条件足够的话好像就可以， 因为没具体去试，所以不太确定

**Comment by xhzengAIB** [comment]
@LengBinBin 
好的，谢谢你的回答，确认这个在iOS7上可以正常运行的对吧？

**Comment by LengBinBin** [comment]
我的7.1.2运行正常
