### ISSUE TITLE
ImageView size

### ISSUE THREAD

**Issue by phucnd0604** [forkingdog/UITableView-FDTemplateLayoutCell#10]
How to use with image from internet download asynchronies when set content of cell. Size of the image may already known

**Comment by sunnyxx** [comment]
If you've known image's size when you get its url, `IBOutlet` image view's width and height constraints.

```
@property (nonatomic, weak) IBOutlet NSLayoutConstraint *imageViewWidthConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint *imageViewHeightConstraint;
```

When configure your cell:  

```
- (void)configureWithEntity:(SomeEntity *)entity {
    self.imageViewWidthConstraint.constant = entity.imageSize.width;
    self.imageViewHeightConstraint.constant = entity.imageSize.height;
    [self.imageView sd_setImageWithURL:entity.imageURL];
}
```

**Comment by phucnd0604** [comment]
thanks. very helpfull

**Comment by CODE4APPLE** [comment]
If you've not known image's size when you get its url,How do i do?

**Comment by sunnyxx** [comment]
This is really a problem that you may hardly handle it properly, reloading is unavoidable when you can't get image's size before download it. Table view cell's height need to be re-calculated, so cell will "jump" from placeholder's height to its real height.
