### ISSUE TITLE
大哥我想问一个动态cell的问题，有关饿了么的cell效果怎么实现的问题

### ISSUE THREAD

**Issue by TrackyTian** [forkingdog/UITableView-FDTemplateLayoutCell#101]
![](http://cdn.cocimg.com/bbs/attachment/Fid_21/21_473832_c243364e6f0cff5.gif)

使用autolayout怎么才能实现？里面的活动的数量也不一定

**Comment by zhaofucheng1129** [comment]
用代码 何必执着于autolayout

**Comment by TrackyTian** [comment]
用代码难道就不用autolayout了吗，主要说一下思路就行

**Comment by zhaofucheng1129** [comment]
就是拿到数据隐藏下面两行得到一个Cell的高度 然后 点击按钮的时候在reload指定的Cell给出全部数据的高度就好了

**Comment by jkyin** [comment]
@TrackyTian 饿了么把所有的优惠信息放到了一个 containerView 中。至于更新约束的代码放到 beginUpdates 和 endUpdates 中就有这种效果了。

**Comment by sunnyxx** [comment]
beginUpdates 和 endUpdates +1
