### ISSUE TITLE
IOS9上面有明显的卡顿

### ISSUE THREAD

**Issue by hongdong** [forkingdog/UITableView-FDTemplateLayoutCell#103]
经过测试发现在IOS9上面有明显的卡顿，希望能得到改善。

**Comment by igiu1988** [comment]
是否在tableView:cellForRowAtIndexPath:中调用了如下代码
```
 [cell setNeedsUpdateConstraints];
  或者      [cell updateConstraintsIfNeeded];
```

**Comment by shukaka** [comment]
ios9上卡顿很严重。没有调用[cell setNeedsUpdateConstraints] 或者 [cell updateConstraintsIfNeeded]

**Comment by igiu1988** [comment]
如果在每次 cellForRow 中都有大量的约束改变，就会卡。我想你需要帖上一段代码一起来看看

**Comment by shukaka** [comment]
func ConfigCell(cell:UITableViewCell, _ indexPath: NSIndexPath) -> Void{
        let ccell = cell as! JiaoLiuCell
            
ccell.nameLabel.text = indexPath.row%2==0 ? "王菲" : "邓紫棋"
                ccell.timeLabel.text = indexPath.row%2==0 ? "09-12 17:52" : "15-22 17:09"
                ccell.contentLabel.text = indexPath.row%2==0 ? "就是这个范儿 ~ " : "时间一去不返 回忆总会消散 猛然回头一看 我们快乐但短暂 花曾开得灿烂 笑曾点亮夜晚 然而双眼一眨 今夜我们一样孤单 啊~~~啊~~~ 我们遇见 我们相恋"
    }

以上就是cellForRow中调用的唯一配置函数。还没开始接后台，用假数据测了一下，在真机上卡顿明显(ios9.1, iphone 5c)。模拟器上很流畅。

**Comment by igiu1988** [comment]
cell 里是否有根据值的情况做出约束的变化？或者是否 cell 的约束有问题，导致在真机里 debug 运行时打印了太多的 log 而感觉卡？我的 iOS 9运行很流畅，测试到了 iPhone 4S机型，所以库的效率你可以放心

**Comment by shukaka** [comment]
class JiaoLiuCell: UITableViewCell {
    
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var timeLabel: UILabel!
    @IBOutlet weak var contentLabel: UILabel!
}
cell里没做任何处理，log也没开，cell布局用了两个Stackview,一个竖排stackview里面有一个横排的stackview，是否是这个导致了计算时间过长？

**Comment by igiu1988** [comment]
sorry ， stackView 我还没有用过。刚才我说的 log 是指约束冲突引起的警告 Log。

**Comment by shukaka** [comment]
布局中没有黄色的警告和红色的错误，刚才试过去掉stackview重新布局，流畅度提升了。

**Comment by sunnyxx** [comment]
1. 理论上 stack view 的高度计算会比直连约束效率低 2. 如果没使用带 cache 的算高 API，打开后会提升流畅度

**Comment by d1248966459** [comment]
同样的情况
