### ISSUE TITLE
求科普

### ISSUE THREAD

**Issue by keshiim** [forkingdog/UITableView-FDTemplateLayoutCell#106]
`          [UITableViewCellAccessoryNone] = 0,
            [UITableViewCellAccessoryDisclosureIndicator] = 34,
            [UITableViewCellAccessoryDetailDisclosureButton] = 68,
            [UITableViewCellAccessoryCheckmark] = 40,
            [UITableViewCellAccessoryDetailButton] = 48
`
这是什么语法？

**Comment by sunnyxx** [comment]
C 语言的一个语法
