### ISSUE TITLE
阳阳，iOS9上卡顿好明显啊

### ISSUE THREAD

**Issue by jueXying** [forkingdog/UITableView-FDTemplateLayoutCell#107]
阳阳，iOS9上卡顿好明显啊，iOS7和iOS8很丝滑，有空看看呗

**Comment by wy19901227** [comment]
我的怎么不卡？

**Comment by jueXying** [comment]
不知道，但是我要是不用这个，自己算高就不卡

**Comment by wy19901227** [comment]
把你demo发出来




------------------ 原始邮件 ------------------
发件人: "jueyingxx";<notifications@github.com>;
发送时间: 2015年10月13日(星期二) 中午11:30
收件人: "forkingdog/UITableView-FDTemplateLayoutCell"<UITableView-FDTemplateLayoutCell@noreply.github.com>; 
抄送: "so , sad❤"<936788507@qq.com>; 
主题: Re: [UITableView-FDTemplateLayoutCell] 阳阳，iOS9上卡顿好明显啊 (#107)




不知道，但是我要是不用这个，自己算高就不卡

**Comment by jueXying** [comment]
我都说了7和8上面不卡，代码都一样

**Comment by mleasyZhuZhiqiang** [comment]
我也发现了会卡，可是很奇怪，一开始比较卡，有图片时滑动会一顿一顿的，但是，后来又不卡了。
现在9上不卡了，7上还是卡。有人知道为什么吗?
