### ISSUE TITLE
发现如下bug

### ISSUE THREAD

**Issue by androidNdk** [forkingdog/UITableView-FDTemplateLayoutCell#109]
1，当一个tableview中注册多个cell时，cell高度计算错误。
2，没有发现使用自动布局的例子。
3，若用contentview的width约束时，会约束错误。

**Comment by jkyin** [comment]
关于第一个问题，你能提供更详细的信息吗。

**Comment by wy19901227** [comment]
我就醉了，你让作者怎么回答你，你就不会把demo 或者把问题错误描述清楚？你让别人按照你的步骤，自己建个工程，还原你的错误，在告诉你，而且还不知道，你用法到底对不对，

**Comment by androidNdk** [comment]
我是在项目中使用的，不方便把所有的项目源码都给作者不好意思。我明天写歌deamon，其实我是希望作者给一个用autolayout使用的例子。

**Comment by wangbiye** [comment]
今天刚集成到项目里,不过我第一次用的是注册一个cell,来凑个热闹

**Comment by sunnyxx** [comment]
没太懂，demo 不就是 AutoLayout 的例子么

**Comment by CaliosD** [comment]
猜测@androidNdk 可能期望的是用代码写成的例子，而不是用storyboard。最近遇到一些问题，发现有些约束是可以在storyboard中直接设置的，比如content hugging priority，而这恰好是用代码写时比较容易忽略的。

**Comment by weekwood** [comment]
Closing this as no response from @androidNdk
