### ISSUE TITLE
高度计算出来都是一样的是什么回事

### ISSUE THREAD

**Issue by Starlight-Roc** [forkingdog/UITableView-FDTemplateLayoutCell#115]
所有的高度都一样，总是以最高的返回，返回所有cell中最高的

**Comment by gripleaf** [comment]
我也碰到了类似问题，但后面解决了，不过姿势不太优雅。
我的情况是需要在tableView: cellForRowAtIndexPath:中配置cell，但是因为tableView: heightForRowAtIndexPath: 比它先执行，所以，此时的cell都是没有填充过数据的cell，计算高度的结果也就都一样了。因此，需要在tableView: heightForRowAtIndexPath:中配置cell，但是配置了cell之后，cell的数据显示却成了问题，因此，我会在更新完cell中的元素之后，调用setNeedsFocusUpdate， 然后才搞定的。

**Comment by sunnyxx** [comment]
保证 `fd_heightForCell` 中的 configuration 正确设置，计算结果全依仗约束设置和 configuration，正常使用不会出现你说的情况的
