### ISSUE TITLE
加载多条数据时，页面被卡主，无法操作

### ISSUE THREAD

**Issue by Gorilla957** [forkingdog/UITableView-FDTemplateLayoutCell#116]
调用[tableView reloadData]后，会计算出所有的cell的高度，如果在主线程执行这个计算，数据量大时，会卡死页面，对于这个问题，请问有什么好的优化方案吗？

**Comment by leasontou** [comment]
我现在也是这个问题，发现这个计算高度很耗时。

**Comment by MrCaoBoHan** [comment]
可以使用- (CGFloat)fd_heightForCellWithIdentifier:(NSString *)identifier cacheByKey:(id<NSCopying>)key configuration:(void (^)(id cell))configuration跟数据绑定

**Comment by Gorilla957** [comment]
@MrCaoBoHan 用的就是这个API.

**Comment by sunnyxx** [comment]
如果用 `cacheByKey` API，已经可以保证没有重复计算；若使用 `cacheByIndexPath` API，要注意直接调用 `- reloadData` 会导致所有高度缓存重新计算，`- fd_reloadDataWithoutInvalidateIndexPathHeightCache` 才不会。因为 UIKit 的方法只能在主线程调用，所以当 Cell 约束复杂，或者里面有很多 AttributedString 时，无论如何都会卡主线程。另一个 Tip 就是在 configure cell 时，根据 `cell.fd_isTemplateLayoutCell` 来区分算高 cell 和真实 cell，避免不必要的副作用引起的卡顿。接下来我也会着手去优化 TemplateCell 引发的性能问题。

**Comment by keroushe** [comment]
是会卡住不动，请问有什么解决方法吗?
