### ISSUE TITLE
Cell must be registered to table view for identifier - infoAllCell

### ISSUE THREAD

**Issue by zx1050336132** [forkingdog/UITableView-FDTemplateLayoutCell#119]
请教一下我已经注册过cell 了，怎么还是报“Cell must be registered to table view for identifier - infoAllCell”这个错误，tableview注册了三个cell，infoAllCell在section2中显示

**Comment by mqlsq** [comment]
我也遇到这个问题,怎么解决的

**Comment by zx1050336132** [comment]
还没有解决，等作者的回答了

**Comment by mqlsq** [comment]
你是自己代码写的tableView吗?

**Comment by charonLynx** [comment]
我是代码写的cell 无论怎么注册都会报这个错误

**Comment by calios** [comment]
我也出现了这个问题。后来发现是在tableview的初始化里面加了` self.tableFooterView = [[UIView alloc] initWithFrame:CGRectZero];` 这一句，貌似加上之后就直接开始算高度了，导致dequeueReusableCellWithIdentifier返回的cell为空。删除了设置footerview的一句就好了。

**Comment by LargeShrimp** [comment]
个人感觉最好是用sb，如果不是就用viewcontroller，在创建tableview的时候注册

发送自 taitanxiami




On Sun, Oct 25, 2015 at 7:28 PM -0700, "zx1050336132" <notifications@github.com> wrote:












请教一下我已经注册过cell 了，怎么还是报“Cell must be registered to table view for identifier - infoAllCell”这个错误，tableview注册了三个cell，infoAllCell在section2中显示

**Comment by ihappyhacking** [comment]
的确如 @calios 所说的，设置tableView 的 tableHeaderView 或者 tableFooterView 之后注册 cell 的话，是有这个问题的，把 tableHeaderView 或者 tableFooterView 放在注册 cell 之后设置，就可以了

**Comment by charonLynx** [comment]
感谢帮助！

在 2015-11-29 22:31:55，"我的眼里只有代码" <notifications@github.com> 写道：


的确如 @calios 所说的，设置tableView 的 tableHeaderView 或者 tableFooterView 之后注册 cell 的话，是有这个问题的，把 tableHeaderView 或者 tableFooterView 放在注册 cell 之后设置，就可以了

**Comment by HanYaZhou1990** [comment]
创建过tableView以后，就直接regist，就不出出现Cell must be registered to table view for identifier - xxxx”这种错误了，出现这个错误是因为regist太晚了，往前提提就好了

**Comment by Job-Yang** [comment]
作者在博客里这样解释的：这个 cell 只为了参加高度计算，不会真的显示到屏幕上；它通过 UITableView 的 -dequeueCellForReuseIdentifier: 方法创建并保存，所以要求这个 ReuseID 必须已经被注册到了 UITableView 中，也就是说，要么是 Storyboard 中的原型 cell，要么就是使用了 UITableView 的 -registerClass:forCellReuseIdentifier: 或 -registerNib:forCellReuseIdentifier:其中之一的注册方法。

**Comment by rydensun** [comment]
我的解决办法就是在你创建tableview的时候，手动注册任何你可能用到的cell，并分配reuse Indentifier。
  [self.tableView registerClass:[TableViewCell1 class] forCellReuseIdentifier:@"cell1"];
  [self.tableView registerClass:[TableViewCell2 class] forCellReuseIdentifier:@"cell2"];

**Comment by zj381652512** [comment]
如果是通用tableView,已经在公共代码中,设置了tableHeaderView,tableFooterView,不妨试一下交换这两句代码的先后顺序:
1.OK的代码
tableView.contentInset = UIEdgeInsetsMake(kNavBarH, 0, 0, 0);
tableView.delegate   = self;
tableView.dataSource = self;

2.崩溃的代码
tableView.delegate   = self;
tableView.dataSource = self;
tableView.contentInset = UIEdgeInsetsMake(kNavBarH, 0, 0, 0);
