### ISSUE TITLE
加载下一页后，会有短暂卡顿，应如何解决？

### ISSUE THREAD

**Issue by yangwei0401** [forkingdog/UITableView-FDTemplateLayoutCell#12]
大约每页有20个项目，图片异步加载，行高已经正确设置，没有问题，只是加载出下一页时，会有短暂卡顿，应该是在算高度，而使用sizeFit 又无法在线程中，该怎么解决呢？

**Comment by sunnyxx** [comment]
应该是正常现象，可以放个demo工程看看哪里可以做优化的

**Comment by yangwei0401** [comment]
我加了预估行高，这个现象好了，可是带来了其他问题：往上滑，看上面的内容时，表格会跳动

**Comment by sunnyxx** [comment]
下一个版本里面会对这些问题进行优化，请关注
