### ISSUE TITLE
autolayout 和 framelayout混用的场景

### ISSUE THREAD

**Issue by lawrsp** [forkingdog/UITableView-FDTemplateLayoutCell#120]
比如，有一个subview展示一组图片，图片的高度要根据这个subview的宽度来决定
宽度由autolayout决定，而高度使用了手工计算得到的frame

这种情况下，目前可以重写cell的sizeThatFits，在其中使用 systemLayoutSizeFittingSize 决定cell其他部分的大小，使用 subview的sizeThatFits决定这个subview的大小

能够在库中直接支持这种情形呢？
比如加一个 - (CGFloat)addtionalHeight:(CGSize)size 
这样在计算完autolayout的高度后，如果cell实现了 这个方法，再加上这个方法得到的高度

**Comment by sunnyxx** [comment]
库里加这个情况不太合适，下面的代码不知道能否解决：
``` objc
CGFloat height = [tableView fd_heightForCellWithIdentifier:@"FDFeedCell" configuration:^(FDFeedCell *cell) {
    [self configureCell:cell atIndexPath:indexPath];
}];
return height + addtionalHeight;
```
