### ISSUE TITLE
删除多个 Cell 出现 bug 

### ISSUE THREAD

**Issue by juvham** [forkingdog/UITableView-FDTemplateLayoutCell#122]
同时删除多个cell 时闪退  代码 定位到这一行

 if (self.fd_autoCacheInvalidationEnabled) {
        [self.fd_cellHeightCache buildHeightCachesAtIndexPathsIfNeeded:indexPaths];
        [indexPaths enumerateObjectsUsingBlock:^(NSIndexPath *indexPath, NSUInteger idx, BOOL *stop) {
            NSMutableArray *rows = self.fd_cellHeightCache.sections[indexPath.section];
＝＝》            [rows removeObjectAtIndex:indexPath.row];
        }];
    }
    [self fd_deleteRowsAtIndexPaths:indexPaths withRowAnimation:animation]; // Primary call

目测 enumerate 的错

**Comment by guibin1989** [comment]
我是单条cell删除，删除最后一个时闪退，也是定位到这一行

**Comment by juvham** [comment]
1.4解决了这个问题 麻烦作者把 issue 关了吧。

**Comment by sunnyxx** [comment]
Fixed in 1.4
