### ISSUE TITLE
contentViewWidth计算出来是0，控制台输出约束冲突

### ISSUE THREAD

**Issue by tounaobun** [forkingdog/UITableView-FDTemplateLayoutCell#123]
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    NSLayoutConstraint:0x7ff1ad94c830 SwipeView:0x7ff1ad9c99d0.leading == UITableViewCellContentView:0x7ff1ad9801e0.leading + 5,
    NSLayoutConstraint:0x7ff1ad945750 UITableViewCellContentView:0x7ff1ad9801e0.trailing == SwipeView:0x7ff1ad9c99d0.trailing,
    NSLayoutConstraint:0x7ff1ad94c610 UITableViewCellContentView:0x7ff1ad9801e0.width == 0
)

我想知道为什么UITableViewCellContentView.width == 0 ??

**Comment by unkosun** [comment]
我也遇到这个问题，在计算高度的时候，会添加这个约束：NSLayoutConstraint *tempWidthConstraint =
        [NSLayoutConstraint constraintWithItem:cell.contentView
                                     attribute:NSLayoutAttributeWidth
                                     relatedBy:NSLayoutRelationEqual
                                        toItem:nil
                                     attribute:NSLayoutAttributeNotAnAttribute
                                    multiplier:1.0
                                      constant:contentViewWidth];
        [cell.contentView addConstraint:tempWidthConstraint];
但是 contentViewWidth 这个宽度获取的时候是0，不知道怎么解决

**Comment by parallelWorld** [comment]
实现文件中把438行的代码改成
`CGFloat contentViewWidth = CGRectGetWidth([UIScreen mainScreen].bounds);`就好了

**Comment by tounaobun** [comment]
@parallelWorld 为什么要用UIScreen的bounds?

**Comment by parallelWorld** [comment]
你的tableView也是用约束写的吧？
用bounds只是避免出现冲突，你写320或者别的什么值都可以啊。只要那个宽度大小跟你现在的不冲突就可以了，一般cell的宽度取屏宽，所以就取屏宽啦。

**Comment by tounaobun** [comment]
这种改法侵入性太强了。

**Comment by unkosun** [comment]
我解决这个问题了，造成CGRectGetWidth(self.frame)为0，是因为tableview 的frame(0,0,0,0)。我的tableview也是自动布局的，再布局完后需要立即生效 就需要调用layoutIfNeeded。

**Comment by tounaobun** [comment]
解决了。
