### ISSUE TITLE
当tableview中有多种cell时，计算高度的异步会导致页面没法看？

### ISSUE THREAD

**Issue by CaliosD** [forkingdog/UITableView-FDTemplateLayoutCell#125]
当tableview中注册多种cell时，都使用异步的高度计算会让相互依赖的各个cell展示起来很不稳定。
比如共有3个cell，cell1的高度还没有计算出来，cell2的高度已经算出来，此时cell2会先展示在cell1的位置。并不符合cell1-cell2依次展示的期望。

请问有什么解决办法么？还是说这种场景下不适合使用该category？谢谢！

**Comment by leasontou** [comment]
同求

**Comment by Coder-XL** [comment]
同求

**Comment by sunnyxx** [comment]
没太明白意思 - - cell 的显示顺序不是应该由 data source 完全决定么？

**Comment by CaliosD** [comment]
cell的 内容 的确是由data source完全决定的，但是 顺序 ，不敢肯定。我按照demo中的方法来计算高度，会出现cell3覆盖到cell2这样的状况。不知道我是否表达清楚了？期待“同求”的伙伴们补充更多详情～

**Comment by sunnyxx** [comment]
出现“覆盖”的情况很可能是上一个 Cell 的高度计算失败，返回了个 0，看上去就乱了，所以应该查约束设置的是否规范和完整

**Comment by liuzhiyi1992** [comment]
@CaliosD 所有subview要add到contentView里面，contentView四周约束要完整， 计算也要对于contentView计算，否则会出现“顺序错乱”的假象
