### ISSUE TITLE
动态变化Cell的高度时，由于缓存的存在，导致约束出现冲突

### ISSUE THREAD

**Issue by zekunyan** [forkingdog/UITableView-FDTemplateLayoutCell#126]
动态改变Cell的约束，想实现Cell的高度变化效果，但是出现了约束冲突。  
感觉是缓存高度导致Cell的高度没有改变而引起的。。。

**Comment by zekunyan** [comment]
不好意思，是我搞错了=。=，库很棒。

**Comment by ssjk4** [comment]
楼主，我也有这个问题啊，cell里updateConstraints，就约束冲突了，你是怎么解决的，求方法
