### ISSUE TITLE
你好、请问在cell中嵌套了tableview的话支持吗？

### ISSUE THREAD

**Issue by hongdong** [forkingdog/UITableView-FDTemplateLayoutCell#128]
你好、请问在cell中嵌套了tableview的话支持吗？

**Comment by axl411** [comment]
应该是需要手动给 table view 加上 height 的 constraint 才 work

**Comment by sunnyxx** [comment]
楼上正解。加高约束，里层 table view 数据源 reload 后，将 contentSize.height 的值设置到高约束上

**Comment by realchen** [comment]
在 reload完后 ，设置 高约束，发现字会堆积起来，并且显示不全变成 ...

**Comment by fanruoyang** [comment]
我是cell里面又是一个tableview ，也用了这个框架计算自适应高度，现在是外面那一层自适应cell无法显示tablview，有没有解决的办法，拿 contentSize.height  高度也不准确，因为设置了自动的
