### ISSUE TITLE
请问一下，如果一个cell中有多张图片，就像朋友圈里那种情况的时候，该怎么处理呢？

### ISSUE THREAD

**Issue by wfkbyni** [forkingdog/UITableView-FDTemplateLayoutCell#129]

**Comment by faimin** [comment]
不固定张数的图片感觉用代码动态创建视图并添加约束会更方便一些, 或者如果产品已经限制最多显示图片张数的时候,可以在IB中添加好视图,然后根据从服务端获取到数据来操作显示或隐藏某些视图

**Comment by weekwood** [comment]
Not the issues in this repo
