### ISSUE TITLE
请问，为啥这样的 Cell 约束设置会产生冲突

### ISSUE THREAD

**Issue by jiyee** [forkingdog/UITableView-FDTemplateLayoutCell#130]
请问，为啥这样的 Cell 约束设置会产生冲突，高度能自动计算正确。但是报冲突。

```
@implementation DetailAnnotationImageTableViewCell

- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier {
    if (self = [super initWithStyle:style reuseIdentifier:reuseIdentifier]) {
        self.translatesAutoresizingMaskIntoConstraints = NO;

        self.accessoryType = UITableViewCellAccessoryNone;
        self.selectionStyle = UITableViewCellSelectionStyleNone;

        [self.contentView addSubview:self.photoView];
        [self.contentView addSubview:self.badgeView];
        [self.contentView addSubview:self.titleLabel];
        [self.contentView addSubview:self.descLabel];
    }

    return self;
}

- (void)updateConstraints {
    if (!self.didSetupConstraints) {

        [self.photoView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.equalTo(self.contentView).offset(15);
            make.left.equalTo(self.contentView).offset(8);
            make.right.equalTo(self.contentView).offset(-8);
            make.height.equalTo(self.photoView.mas_width).dividedBy(1.5f);
        }];

        [self.badgeView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.equalTo(self.photoView.mas_bottom).offset(12);
            make.left.equalTo(self.photoView);
            make.height.equalTo(@14);
            make.width.equalTo(@4);
        }];

        [self.titleLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.equalTo(self.photoView.mas_bottom).offset(10);
            make.left.equalTo(self.badgeView.mas_right).offset(3);
            make.width.equalTo(@60);
        }];

        [self.descLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.equalTo(self.photoView.mas_bottom).offset(10);
            make.left.equalTo(self.titleLabel.mas_right).offset(10);
            make.right.equalTo(self.photoView);
            make.bottom.equalTo(self.contentView);
        }];

        self.didSetupConstraints = YES;
    }

    [super updateConstraints];
}
```

冲突如下：

```
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-11-20 15:57:52.426 renrenche[66027:7529275] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<MASLayoutConstraint:0x7fd9d287f3b0 UIImageView:0x7fd9d2d09160.top == UITableViewCellContentView:0x7fd9d2d08160.top + 15>",
    "<MASLayoutConstraint:0x7fd9d287e200 UIImageView:0x7fd9d2d09160.left == UITableViewCellContentView:0x7fd9d2d08160.left + 8>",
    "<MASLayoutConstraint:0x7fd9d287e3b0 UIImageView:0x7fd9d2d09160.right == UITableViewCellContentView:0x7fd9d2d08160.right - 8>",
    "<MASLayoutConstraint:0x7fd9d287ff00 UIImageView:0x7fd9d2d09160.height == UIImageView:0x7fd9d2d09160.width * 0.666667>",
    "<MASLayoutConstraint:0x7fd9d2882d40 TTTAttributedLabel:0x7fd9d2d0ad80.top == UIImageView:0x7fd9d2d09160.bottom + 10>",
    "<MASLayoutConstraint:0x7fd9d2883700 TTTAttributedLabel:0x7fd9d2d0ad80.bottom == UITableViewCellContentView:0x7fd9d2d08160.bottom>",
    "<NSLayoutConstraint:0x7fd9d0564bb0 UITableViewCellContentView:0x7fd9d2d08160.height == 44>",
    "<NSLayoutConstraint:0x7fd9d0564840 UITableViewCellContentView:0x7fd9d2d08160.width == 320>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x7fd9d287ff00 UIImageView:0x7fd9d2d09160.height == UIImageView:0x7fd9d2d09160.width * 0.666667>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-11-20 15:57:52.535 renrenche[66027:7529275] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. 
    Try this: 
        (1) look at each constraint and try to figure out which you don't expect; 
        (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<MASLayoutConstraint:0x7fd9d287f3b0 UIImageView:0x7fd9d2d09160.top == UITableViewCellContentView:0x7fd9d2d08160.top + 15>",
    "<MASLayoutConstraint:0x7fd9d2882d40 TTTAttributedLabel:0x7fd9d2d0ad80.top == UIImageView:0x7fd9d2d09160.bottom + 10>",
    "<MASLayoutConstraint:0x7fd9d2883700 TTTAttributedLabel:0x7fd9d2d0ad80.bottom == UITableViewCellContentView:0x7fd9d2d08160.bottom>",
    "<NSLayoutConstraint:0x7fd9d0564bb0 UITableViewCellContentView:0x7fd9d2d08160.height == 0.5>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x7fd9d2882d40 TTTAttributedLabel:0x7fd9d2d0ad80.top == UIImageView:0x7fd9d2d09160.bottom + 10>
```

**Comment by robert121** [comment]
为什么在updateConstraints里面布局，这里更新约束的

**Comment by ihappyhacking** [comment]
我也是报了一大推冲突，但是我不是在 ``updateConstraints`` 里面设置的，我是在 cell 的 ``- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier`` 里面设置约束的，高度计算也是正确的，但是就是出现了一大推的冲突，然后我将高度返回一个固定的值(也就是计算之后得到的高度值)之后，就没有约束冲突，不知道这是为什么。。。
``
Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<MASLayoutConstraint:0x1742b3e00 UIView:0x13454bee0.left == UITableViewCellContentView:0x1345530b0.left>",
    "<MASLayoutConstraint:0x1742b3ec0 UIView:0x13454bee0.right == UITableViewCellContentView:0x1345530b0.right>",
    "<MASLayoutConstraint:0x1742b4460 UIImageView:0x134557730.right == UIView:0x13454bee0.right - 16>",
    "<MASLayoutConstraint:0x1742b44c0 UIImageView:0x134557730.width == 9>",
    "<MASLayoutConstraint:0x1742b46a0 UILabel:0x134557be0.right == UIImageView:0x134557730.left - 5>",
    "<MASLayoutConstraint:0x1742b48e0 UIView:0x13454a710.left == UIView:0x13454bee0.left + 8>",
    "<MASLayoutConstraint:0x1742b4a00 UIView:0x13454a710.right == UILabel:0x134557be0.left - 8>",
    "<NSLayoutConstraint:0x170281c70 UITableViewCellContentView:0x1345530b0.width == 0>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x1742b44c0 UIImageView:0x134557730.width == 9>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-11-30 10:27:54.172 MyApp[10680:1096108] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<MASLayoutConstraint:0x1742b3e00 UIView:0x13454bee0.left == UITableViewCellContentView:0x1345530b0.left>",
    "<MASLayoutConstraint:0x1742b3ec0 UIView:0x13454bee0.right == UITableViewCellContentView:0x1345530b0.right>",
    "<MASLayoutConstraint:0x1742b4460 UIImageView:0x134557730.right == UIView:0x13454bee0.right - 16>",
    "<MASLayoutConstraint:0x1742b46a0 UILabel:0x134557be0.right == UIImageView:0x134557730.left - 5>",
    "<MASLayoutConstraint:0x1742b48e0 UIView:0x13454a710.left == UIView:0x13454bee0.left + 8>",
    "<MASLayoutConstraint:0x1742b4a00 UIView:0x13454a710.right == UILabel:0x134557be0.left - 8>",
    "<NSLayoutConstraint:0x170281c70 UITableViewCellContentView:0x1345530b0.width == 0>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x1742b4460 UIImageView:0x134557730.right == UIView:0x13454bee0.right - 16>
.
.
.
.
.
.
``

**Comment by shaveKevin** [comment]
这个是因为你cell初始化的时候默认高度是44 在进行布局的时候imageview有高度的 高度跟cell 初始化的高度是不匹配的。建议你在初始化cell的时候给cell一个高度 cell 的contentview一个高度  https://github.com/shaveKevin/MasonryStoryboardCellHeight  看下这个demo的代码。可能会帮你解决掉这个冲突

**Comment by wujichao** [comment]
参考这个issus https://github.com/forkingdog/UITableView-FDTemplateLayoutCell/issues/332
设置top 和 bottom 约束优先级可以解决
