### ISSUE TITLE
自动布局出现怪异现象，图片占的高度太大了

### ISSUE THREAD

**Issue by hanhailong** [forkingdog/UITableView-FDTemplateLayoutCell#131]
![image](https://cloud.githubusercontent.com/assets/4241807/11321571/939fef28-9100-11e5-9ed8-fa6dc2a49059.png)

**Comment by zooyf** [comment]
同样的错误。
问题描述：
我的设备是5s，在cell中设置手机截屏即640*1136像素的图片，会出现此错误。
图片被拉长，宽度是320，高度是1136。
请问如何解决此问题

**Comment by sunnyxx** [comment]
需要看约束是怎么连的

**Comment by blmyself** [comment]
遇到同样问题了，请问楼主解决了么？ 我是直接在官方demo上改成异步加载图片，约束都没改，成下面这样了:

**Comment by JackZYH** [comment]
我也发现这个问题了，当图片是被缩放之后显示出来的，高度计算任然会计算为缩放之前的高度。也就是图片的原始高度。求解决方案！

**Comment by iiyumewo** [comment]
这问题困扰我一个下午了！好难受啊...
只要图片宽度比屏幕大，图片上下都会有留白。
图片宽度比屏幕小的话，不管图片多长都相安无事。

**Comment by iHTCboy** [comment]
约束 高度小于等于宽度

**Comment by weekwood** [comment]
closed cause no response
