### ISSUE TITLE
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Customized cell must override '-sizeThatFits:' method if not using auto layout.'

### ISSUE THREAD

**Issue by jiazufei** [forkingdog/UITableView-FDTemplateLayoutCell#132]
自定义的cell是有约束条件的，为什么还是说没有使用自动布局？
![image](https://cloud.githubusercontent.com/assets/3351691/11465935/4d915354-9778-11e5-9113-68ecb7df886a.png)

**Comment by sunnyxx** [comment]
向 cell.contentView 上加约束，而不是加 cell 上；最新版本已经去掉了这个 assert
