### ISSUE TITLE
有时候在dequeueReusableCellWithIdentifier cell的时候会产生UIViewAlertForUnsatisfiableConstraints

### ISSUE THREAD

**Issue by xilin** [forkingdog/UITableView-FDTemplateLayoutCell#133]
不同cell之间的高度肯定是不一致的，在多于一屏的cell时dequeueReusableCellWithIdentifier偶尔会报出UIViewAlertForUnsatisfiableConstraints错误。而且在iOS7上这种时候的UIViewAlertForUnsatisfiableConstraints也不会导致崩溃。
使用v1.3

**Comment by sunnyxx** [comment]
根据具体情况，把一些约束的优先级设置成 999 （如下边距约束，右边距约束）可以解决问题

**Comment by xilin** [comment]
果然可以了，谢谢！为啥会出现这种问题呢？是重用和显示的时机导致的吗？

**Comment by sunnyxx** [comment]
当一个 Cell 高度确定时，比如 100，UITableView 会给 ContentView 扣一个高度为 100，优先级 1000 的高约束，若重用后这个 Cell 的高度应该变成比如 50 时，100 的约束还在，假如内部的约束优先级都是 1000 （必须满足） 就会发生冲突，然而新高度生效后原来那个冲突约束就消失了，所以不会影响最后的显示。设置些 999 的优先级能一定程度减少 1000 对 1000 的不满足冲突。

**Comment by xilin** [comment]
了解了，谢谢！
