### ISSUE TITLE
动态修改约束的高度，有报错，求指导

### ISSUE THREAD

**Issue by FutureChen** [forkingdog/UITableView-FDTemplateLayoutCell#135]
![52b74947-3918-46bd-b93e-0557cd0dc3bc](https://cloud.githubusercontent.com/assets/8944181/11533283/cc4f34aa-9943-11e5-95c2-3f310db7e973.jpg)
我这样添加了一个View和约束,并且先设定了蓝色的视图的，高度
而后在代码里修改了蓝色视图的高度

- (void)configureCell:(UITableViewCell *)cell atIndexPath:(NSIndexPath *)indexPath
{
    MMDiaryCell *virtualCell=(MMDiaryCell*)cell;
//    CGFloat raH=  arc4random() % 200+20;
    [virtualCell setMyheight:250];
}

cell.m里面 
-(void)setMyheight:(CGFloat )height
{
      _blueHeigthLayout.constant=height;
}

然后提示了一个约束警告

2015-12-02 22:29:00.589 MeiMei[1105:33286] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7f9a3250b940 UIView:0x7f9a325764a0.height == 54>",
    "<NSLayoutConstraint:0x7f9a32566d60 UIView:0x7f9a325764a0.top == UITableViewCellContentView:0x7f9a32582d90.top + 8>",
    "<NSLayoutConstraint:0x7f9a3256eeb0 UITableViewCellContentView:0x7f9a32582d90.bottom == UIView:0x7f9a325764a0.bottom + 8>",
    "<NSLayoutConstraint:0x7f9a32574900 UITableViewCellContentView:0x7f9a32582d90.height == 266>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7f9a3250b940 UIView:0x7f9a325764a0.height == 54>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

是我这样用法存在问题么？

**Comment by FutureChen** [comment]
refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7f9a3250b940 UIView:0x7f9a325764a0.height == 54>",
    "<NSLayoutConstraint:0x7f9a32566d60 UIView:0x7f9a325764a0.top == UITableViewCellContentView:0x7f9a32582d90.top + 8>",
    "<NSLayoutConstraint:0x7f9a3256eeb0 UITableViewCellContentView:0x7f9a32582d90.bottom == UIView:0x7f9a325764a0.bottom + 8>",
    "<NSLayoutConstraint:0x7f9a32574900 UITableViewCellContentView:0x7f9a32582d90.height == 266>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7f9a3250b940 UIView:0x7f9a325764a0.height == 54>

**Comment by FutureChen** [comment]
"<NSLayoutConstraint:0x7f9a3250b940 UIView:0x7f9a325764a0.height == 54>",
    "<NSLayoutConstraint:0x7f9a32566d60 UIView:0x7f9a325764a0.top == UITableViewCellContentView:0x7f9a32582d90.top + 8>",
    "<NSLayoutConstraint:0x7f9a3256eeb0 UITableViewCellContentView:0x7f9a32582d90.bottom == UIView:0x7f9a325764a0.bottom + 8>",
    "<NSLayoutConstraint:0x7f9a32574900 UITableViewCellContentView:0x7f9a32582d90.height == 266>"

**Comment by FutureChen** [comment]
- -卧槽，为什么报错信息贴不上来

**Comment by FutureChen** [comment]
<NSLayoutConstraint:0x7f9a3250b940 UIView:0x7f9a325764a0.height == 54>

**Comment by FutureChen** [comment]
Will attempt to recover by breaking constraint 
 NSLayoutConstraint:0x7f9a3250b940 UIView:0x7f9a325764a0.height == 54

**Comment by ssjk4** [comment]
楼主解决了吗？ 我也有这个问题，求解决方法

**Comment by FutureChen** [comment]
@ssjk4  不好意思，没有去解决呢。

**Comment by Better-Jiao** [comment]
也遇到这样的问题

**Comment by sunnyxx** [comment]
你贴出来的两个冲突的约束：
```
"NSLayoutConstraint:0x7f9a3250b940 UIView:0x7f9a325764a0.height == 54",
"NSLayoutConstraint:0x7f9a32574900 UITableViewCellContentView:0x7f9a32582d90.height == 266>"
```
上面的应该是蓝色 View 的高约束，下面的是 `heightForRowAtIndexPath:` 的值被 UITableView 获取到后，加到 `tableView.contentView`上的约束，更改内部约束后需要调用 UITableView 的 reload 方法来刷新下面这个约束的值。 `- reloadData` 或 `- reloadRows` 都可以

**Comment by FutureChen** [comment]
过了这么久，发现这个问题并没有解决，我的tableview 中就是需要显示不同高度的蓝色视图，如何做到

**Comment by Peter0065** [comment]
一般在配置实体的时候会根据实体内容来决定cell内某些view（无法自动计算）的高度，但是在这之前cell contentview的约束已经确定，强制调整某view的高度约束会导致如@FutureChen  那般冲突报错。
而这种情况下楼上@sunnyxx 的方案并不能解决该问题。在cellforrow里面配置实体，在实体里面算好新的高度，紧接着UITableView reload 那不是又触发了cellforrow ,这样将陷入死循环。。  在已经确定好cell contentView的cell里面调整某view高度而产生的这个冲突报错是合理的可以理解的，有什么方法可以避免该报错吗？或者说一个正确的处理这种存在无法自动计算的view的方式？

**Comment by Peter0065** [comment]
http://stackoverflow.com/questions/28572319/autolayout-constraints-warning-will-attempt-to-recover-by-breaking-constraint
类似处理解决了我与@FutureChen 类似的报错问题
