### ISSUE TITLE
点击cell后push到新的ViewController瞬间tableView的cell往上移

### ISSUE THREAD

**Issue by tounaobun** [forkingdog/UITableView-FDTemplateLayoutCell#136]
版本：iOS8.1（模拟器，真机均可）
demo为UITableView-FDTemplateLayoutCell的demo。（版本1.3)
在storyboard里添加新的ViewController，并将cell通过segue连接到ViewController(push)。
在storyboard将UITableView的Selection由No->Single。(这样就可以点击cell了)

运行demo，快速向上拉，等tableView停止滚动后，随意点击一个cell，在push到新的ViewController过程中，你会发现cell突然发生了偏移。

![Uploading Untitled.gif…]()

如果把这行注释掉，上面的现象就不会出现了。但是会有点性能问题（pop时会比较卡)
// self.tableView.estimatedRowHeight = 200;

**Comment by tounaobun** [comment]
![Uploading Untitled.gif…]()

**Comment by tounaobun** [comment]
- -. 没人遇到过这种问题吗

**Comment by tounaobun** [comment]
解决了。在viewWillDisappear:方法里reloadData就行了。

    - (void)viewWillDisappear:(BOOL)animated {
        [super viewWillDisappear:animated];
        [self.tableView reloadData];
    }

**Comment by MrCaoBoHan** [comment]
哥们，解决了吗

**Comment by tounaobun** [comment]
@MrCaoBoHan 临时用这个方法来解决部分问题，

    - (void)viewWillDisappear:(BOOL)animated {
        [super viewWillDisappear:animated];
        // fix cells shifting when pushing for iOS8.1
        [self.tableView reloadData];
    }

但是tableView滚到底部的时候再push的时候还是会跳跃。。。

**Comment by caoer** [comment]
:+1:

**Comment by MrCaoBoHan** [comment]
nice

**Comment by sunnyxx** [comment]
:+1:
