### ISSUE TITLE
CocoaPods broken after latest update.

### ISSUE THREAD

**Issue by eddieespinal** [forkingdog/UITableView-FDTemplateLayoutCell#14]
⇒  pod install
Analyzing dependencies
[!] Unable to find a specification for `UITableView+FDTemplateLayoutCell`

**Comment by sunnyxx** [comment]
try `pod setup` first to update all repos  
in Podfile `pod 'UITableView+FDTemplateLayoutCell', '~> 1.1-beta'`  
run `pod install`

**Comment by eddieespinal** [comment]
I got it to work by doing the following on my computer.

- pod repo remove master
- pod setup

It was weird, because it was saying it couldn't find this library but after I did this it worked.

Thanks again.

**Comment by WPDreamMelody** [comment]
$ pod search UITableView+FDTemplateLayoutCell 
[!] Unable to find a pod with name matching `UITableView\+FDTemplateLayoutCell'
