### ISSUE TITLE
 [cell prepareForReuse];

### ISSUE THREAD

**Issue by WFNeIn** [forkingdog/UITableView-FDTemplateLayoutCell#140]
能够详细解释一下，在计算cell高度时。强制调用这个方法的作用吗？

**Comment by sunnyxx** [comment]
为了保证 Template Layout Cell 和正常显示在屏幕上的 Cell 调用的方法和顺序一致，防止 Cell 的 `prepareForReuse` 中写了会影响布局的代码而 Template Cell 没有同步这个更改。
