### ISSUE TITLE
deleteRowsAtIndexPaths 的时候会crash

### ISSUE THREAD

**Issue by FutureChen** [forkingdog/UITableView-FDTemplateLayoutCell#141]
- (void)fd_deleteRowsAtIndexPaths:(NSArray *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation
{
    if (self.fd_autoCacheInvalidationEnabled) {
        [self.fd_cellHeightCache buildHeightCachesAtIndexPathsIfNeeded:indexPaths];
        [indexPaths enumerateObjectsUsingBlock:^(NSIndexPath *indexPath, NSUInteger idx, BOOL *stop) {
            NSMutableArray *rows = self.fd_cellHeightCache.sections[indexPath.section];
            [rows removeObjectAtIndex:indexPath.row];
         
        }];
    }
    [self fd_deleteRowsAtIndexPaths:indexPaths withRowAnimation:animation]; // Primary call
}

奔溃在    [rows removeObjectAtIndex:indexPath.row];

**Comment by gq630960023** [comment]
同问 我用的是 insertRowsAtIndexPaths

**Comment by sunnyxx** [comment]
这个在最新版本已经修复了（1.4）

**Comment by shengyouxiao** [comment]
没有修复啊。还是崩溃

**Comment by peanutgao** [comment]
问题依然在, 还是会崩溃
<img width="944" alt="qq20161217-121439 2x" src="https://cloud.githubusercontent.com/assets/8164433/21284281/68e35cee-c452-11e6-88b6-14eec7120477.png">
