### ISSUE TITLE
cell的某条数据源变化，高度不重新计算

### ISSUE THREAD

**Issue by MrCaoBoHan** [forkingdog/UITableView-FDTemplateLayoutCell#142]
当某条数据中的文本数据发生变化的时候，这时候cell会变化，但是高度不会重新计算，还是取的缓存，导致布局出现问题。怎么破？

**Comment by MrCaoBoHan** [comment]
@sunnyxx

**Comment by sunnyxx** [comment]
数据源变化时当然要 reload 了，reloadData 或者 reload 变化的 cell
