### ISSUE TITLE
Swift，拿来没效果

### ISSUE THREAD

**Issue by Eiltea** [forkingdog/UITableView-FDTemplateLayoutCell#143]
不知道是不是我用错了，pod下来之后，重写heightForRowAtIndexPath ,也尝试重写estimatedHeightForRowAtIndexPath这两个方法，似乎还是一直再跳，而且我把预估行高设置上，注释掉依然跳跳跳～～～，闭包里边写的是模型赋值的语句吧。如果我理解错了，还请指教

**Comment by sunnyxx** [comment]
Swift 的用法和 Objective-C 上的用法一致，estimatedHeight 设置不好会引起跳来跳去的，建议不设置估算试试，configuration block 里面写和 cellForRow 里面一样的 cell 配置。
