### ISSUE TITLE
导致sd_webImageView加载图片失败

### ISSUE THREAD

**Issue by FutureChen** [forkingdog/UITableView-FDTemplateLayoutCell#144]
发现了一个非常极端的BUG
当使用了FD，并且设置了 tableView.estimatedRowHeight ，会导致sd_web有些图片加载不出来，需要滑动列表才会显示出来。
比如我的情况，tableView的head 高度150， cell 高度 280，第二个cell正好处于显示半个的情况，那么第二个cell的图片100%不加载。其他cell的图片也存在不规则的不加载。
如果不设置tableView.estimatedRowHeight 则不会触发这个BUG，不使用FD也不会触发，不知道FD和SD的算法产生了什么冲突。

**Comment by FutureChen** [comment]
[fdsdTest.zip](https://github.com/forkingdog/UITableView-FDTemplateLayoutCell/files/68243/fdsdTest.zip)

**Comment by hongdong** [comment]
遇到同样的问题

**Comment by QiuZhiFei** [comment]
SDWebImage 的问题 ...

**Comment by QiuZhiFei** [comment]
SDWebImage 的问题 .. 

原因：
UITableView-FDTemplateLayoutCell 高度是根据 tempCell 计算，计算高度时 heightForRowAtIndexPath 里的 tempCell 的 imageview 加载图片1，展示的cellForRowAtIndexPath 的 cell 也加载图片1 … 然后当 tempCell 又去加载别的图片 .. cancel 了 加载图片1的 operation .. 

解决方案：
在heightForRowAtIndexPath 的 fd_heightForCellWithIdentifier 的 配置 cell 的方法里只加载数据，不加载图片 ... 在 cellForRowAtIndexPath 里的 fd_heightForCellWithIdentifier 才加载图片 ~

**Comment by FutureChen** [comment]
@QiuZhiFei  66666 问题解决了，实在66，膜拜一下

**Comment by DrustZ** [comment]
666

**Comment by sunnyxx** [comment]
也可以使用 `cell.fd_isTemplateLayoutCell` 来判断是否要加载图片

**Comment by lilyApplezhang** [comment]
请问解决了此问题的朋友能否给个demo，新手请谅解

**Comment by FutureChen** [comment]
@lilyApplezhang 
最简单的关闭tableView 的estimatedRowHeight 就好了，还能避免其他很多坑

**Comment by lilyApplezhang** [comment]
方便加个好友细指导一下吗

**Comment by lilyApplezhang** [comment]
@FutureChen 我没有用到estimatedRowHeight哈

**Comment by lilyApplezhang** [comment]
@QiuZhiFei 能否给个详细的demo
