### ISSUE TITLE
类似于"<NSLayoutConstraint UITableViewCellContentView:0x7fe3c24a4590.width == 0>"的警告

### ISSUE THREAD

**Issue by liwenDeng** [forkingdog/UITableView-FDTemplateLayoutCell#145]
我在使用过程中遇到如下问题：cell 内部控件如label 宽度没有指定为定值，比如依赖于cell宽度的话，会出现如下提示信息：
(
    <MASLayoutConstraint:0x7fe3c4821930 UIView:0x7fe3c24bef40.left == UITableViewCellContentView:0x7fe3c24a4590.left>,
    <MASLayoutConstraint:0x7fe3c48231e0 UIView:0x7fe3c24bef40.right == UITableViewCellContentView:0x7fe3c24a4590.right>,
    <MASLayoutConstraint:0x7fe3c24fafe0 UILabel:0x7fe3c24fa8f0.left == UIView:0x7fe3c24bef40.left + 10>,
    <MASLayoutConstraint:0x7fe3c24fb490 UILabel:0x7fe3c24fa8f0.right <= UIView:0x7fe3c24bef40.right - 10>,
    <NSLayoutConstraint:0x7fe3c4a5c4c0 UITableViewCellContentView:0x7fe3c24a4590.width == 0>
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x7fe3c24fb490 UILabel:0x7fe3c24fa8f0.right <= UIView:0x7fe3c24bef40.right - 10>

我做了以下几点尝试：
1.使用同样的约束布局，通过self-sizing 的方式的话不会出现约束警告，应该可以说明约束是正确的。

2.通过下断点，发现警告是在- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath 方法中 调用 【    return [tableView fd_heightForCellWithIdentifier:@"Cell2" configuration:^(MSCell2 *cell) {
        cell.cellModel = self.dataArray[indexPath.row];
    }];】 方法时触发的。 
具体定位到 UITableView+FDTemplateLayoutCell.m 文件中第100行的       [cell.contentView addConstraint:tempWidthConstraint] 方法中;

3.如果从内部如把label宽度写为定值的话，是不会报警告信息的（但是在某些场合下，内部label 的宽度是由外部视图决定的）

我的猜测：
应该是通过创建（获取？）一个类似于 template layout cell 的方式来进行赋值并调用 systemLayoutSizeFittingSize 计算高度的前一步中，由于template layout cell 没有superView，导致其无法在宽度上获得依赖于外部视图的约束引起的？

个人测试Demo地址：https://github.com/liwenDeng/AutolayoutCell，Demo2 

###补充：
找到问题所在了，在给template layout cell 添加宽度约束时，宽度是通过 CGFloat contentViewWidth = CGRectGetWidth(self.frame);  获取的，如果tableView 也是用约束添加到父视图上的话，self.frame ＝ （0，0；0，0）,获取到的宽度为0，所以会提示宽度为0 警告。目前我的解决办法是通过frame 的形式添加 tableView。

**Comment by sunnyxx** [comment]
楼上说的对 - -
