### ISSUE TITLE
在cell的updateConstraints更新高度约束，有冲突，求指导

### ISSUE THREAD

**Issue by ssjk4** [forkingdog/UITableView-FDTemplateLayoutCell#147]
用Masonry写的约束，想动态改变cell内imageView的高度，实现cell的自适应高度。代码如下

```
- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier
{
    self = [super initWithStyle:style reuseIdentifier:reuseIdentifier];
    if (self) {
        self.imageV = [[UIImageView alloc] init];
        [self.contentView addSubview:self.imageV];
        self.imageV.backgroundColor = [UIColor redColor];
        [self.imageV mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.top.right.equalTo(self.contentView);
            make.height.equalTo(@(60));
            make.bottom.equalTo(self.contentView).offset(-20);
        }];
    }
    return self;
}

- (void)updateConstraints
{
        [self.imageV mas_updateConstraints:^(MASConstraintMaker *make) {
            if (self.indexPath.row % 2 == 0) {
                make.height.equalTo(@(60));
            } else {
                make.height.equalTo(@(10));
            }
        }];

    [super updateConstraints];
}
```

把updateConstraints注释掉，一切都正常，打开updateConstraints动态改变imageView高度时界面效果是达到预期了也能正常运行，但是出现约束冲突提示：

```
(
    "<MASLayoutConstraint:0x7f8ab2d6c3a0 UIImageView:0x7f8ab2d6b1c0.top == UITableViewCellContentView:0x7f8ab2d6aaa0.top>",
    "<MASLayoutConstraint:0x7f8ab2d6c730 UIImageView:0x7f8ab2d6b1c0.height == 60>",
    "<MASLayoutConstraint:0x7f8ab2d6c8b0 UIImageView:0x7f8ab2d6b1c0.bottom == UITableViewCellContentView:0x7f8ab2d6aaa0.bottom - 20>",
    "<NSLayoutConstraint:0x7f8ab2d6cf70 UITableViewCellContentView:0x7f8ab2d6aaa0.height == 30>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x7f8ab2d6c730 UIImageView:0x7f8ab2d6b1c0.height == 60>
```

这个跟高度缓存有关吗？  还是我写的约束有问题？求指导

**Comment by Better-Jiao** [comment]
同求

**Comment by janicezhw** [comment]
一样，困扰我好久了，虽然不影响效果。。。

**Comment by bibuliu** [comment]
同求。cell 里有根据不同值做出不同约束的变化后都会有类似报错

**Comment by ssjk4** [comment]
顶一顶，求大神指点下

我试了好多种方法，感觉是image view的高度约束跟 cell content view的高度约束冲突了，给image view或者content view的高度约束加个priority优先级，就不会有冲突警告，但是这样cell 高度会有偏差

**Comment by sunnyxx** [comment]
更新内部约束后有没有调用 tableView 的 reload 方法呢？

**Comment by ssjk4** [comment]
@sunnyxx 在哪调用tableview 的reload？在tableview的代理里面吗？

还有个问题tableview reload后cellForRowAtIndexPath又会被调用，cell里又会updateConstraints，然后又要tableview reload吗？这不是死循环了吗？？

请指导，谢谢！

**Comment by sunnyxx** [comment]
`- updateConstraints` 是一个事件 callback，视图层级更新约束时会调用，在这个方法里添加约束就跟在 UIViewController 的 `- viewDidLoad` 里调用 `- loadView` 一样不合理。所以对约束的创建和更新不应该写在这个方法中。

**Comment by ssjk4** [comment]
@sunnyxx 我updateConstraints里只是跟新约束啊，用的是masonry的mas_updateConstraints方法，苹果官方不是建议更新约束要在updateConstraints里操作么？

我就问个直观点的问题吧，像微博、微信朋友圈列表的这种cell，有9宫格相册的这种布局，适合用这个库来自适应cell高度吗？？ 相册里的图片数有多有少。

按我的思路没办法创建一个固定的约束来确定相册的高度，肯定要获取到图片个数后才能确定，也就是在获取图片个数后在cell的updateConstraints更新约束。这种情况怎么处理

大神指个明路

**Comment by sunnyxx** [comment]
@ssjk4 解释一下哈，用不用这个库和做什么需求没有关系，这个库用于 AutoLayout 下的 UITableViewCell 高度计算，完全取决于里面约束是怎么连的。可以观察像微博、微信朋友圈列表这些 Cell，**一定是 Cell 高度确定之后才会展示**，如九宫格确定有几行时、单张图片得到宽高之后等。这类需求我建议在 Cell 中垫一层 Wrapper，给 Wrapper 添加一个高约束，然后根据数据计算出正确的高度后，修改高约束的 `constant` 值，随后调用相应的 reload 方法通知 UITableView 更新高度即可。

**Comment by ssjk4** [comment]
@sunnyxx 灰常感谢大神指点啊。首先这个库确实很好用最近几个新的项目都用了，很方便。

关于根据cell动态内容改变高度，又回到了我之前关心的两个问题，
1. 获取完cell的内容后在哪里去更新约束？按以往的经验我只会在cell的数据模型set方法中设置好数据，然后调用下updateConstraints，在updateConstraints方法中根据数据内容调整约束。上面的回复你也说了不应该把更新约束写在updateConstraints中，哪我该写在哪？

2. 更新完约束后如何触发tableview的reload？cellForRowAtIndexPath方法每次被调用都会触发一次cell的数据更新，cell更新完了再去调用tableview reloadData又会触发cellForRowAtIndexPath，这个死循环我实在不知道怎么处理，很疑惑。还是我的思路就不对？？

其实我看了Issues里有好多跟我这个情况差不多的问题，我看了你的回复都是说要在更新完约束后调用tableview reload。我相信有很多人跟我有一样的疑惑。

有个提议啊，能不能麻烦大神针对这个在demo中加个示例，相信能解决好多人的疑惑

**Comment by igiu1988** [comment]
有冲突这个，我一直没有解决

**Comment by sunnyxx** [comment]
待最近有空重新搞下 Demo，弄复杂点的 - -

**Comment by igiu1988** [comment]
有空我也写一个复杂的cell，能不能再次把冲突问题再现

**Comment by lvming6816077** [comment]
请问这个问题最后有结论了么 我也遇到同样的问题。。

**Comment by ssjk4** [comment]
@lvming6816077 还没解决，期待大神在demo里实现这个功能，等等等。。。

**Comment by shaveKevin** [comment]
这个我也遇到过cell.frame = CGRectMake(0, 0, CGRectGetWidth(PhoneBounds), CGRectGetHeight(PhoneBounds));
cell.contentView.frame = cell.frame;

**Comment by zxy198717** [comment]
+1 同样遇到这个问题，还有人在研究吗？

**Comment by anyuhao** [comment]
前提:只框架只支持autoLayout, frame可以get out 模仿要是不会请离开,我是这样用的.一般没问题,卡顿问题不清楚.可以左上角...
使用基本步骤:
1.首先你要在设置代理之前调用: 
        [tableView registerClass:[TweetCell class] forCellReuseIdentifier:kCellIdentifier_Tweet];
        tableView.delegate = self; 
        tableView.dataSource = self;  //如果你的row count 存在则会执行 此处会执行计算高度.所以建议先注册再设置
如果你不按这个来,    UITableViewCell *templateLayoutCell = [self fd_templateCellForReuseIdentifier:identifier]; 可能为nil
2.不管你使用Masonry还是什么其他的autolayout都要明白一点
            // Auto layout engine does its math
            fittingSize = [templateLayoutCell.contentView systemLayoutSizeFittingSize:UILayoutFittingCompressedSize];
这句是这个框架得到高度的依据,如果你不知道怎么才会有值.请记住一点:
这个一点一定告诉系统: self.contentView 的bottom为多少.不告诉它,它不知道哪个是底部怎么给你计算高度.(所以你一定要记住,之前我也一直不会用这个框架,那是没去了解清楚.只是看了介绍多快.没介绍具体怎么用...当我明了了一点的时候摸摸头,可能最近太累了,这怎么简单的道理都不知道了)
//这是关键...
    [self.tweetTextFiled mas_makeConstraints:^(MASConstraintMaker *make) {
        make.bottom.equalTo(self.contentView).offset(-15).priority(MASLayoutPriorityDefaultLow);
    }];
//为什么会用这个属性呢.因为当你设置了top,left width/right的时候又设置了bottom.还设置了height这时候如果bottom - top 得到的高度不 == height就会导致高度变化,所以masonry会报 warning所以你需要设置优先级....height or bottom.
priority(MASLayoutPriorityDefaultLow);

 我认为:
如果你cell里面有一个 tableView
 那么这时候这个  tableView的高度需要自己去得计算.
我用的时候会出现高度为0的情况 ,忘记了iOS7还是都会了.
所以需要手动自己去计算
如果不对请forking dog  告诉..

**Comment by FallenAngle** [comment]
@ssjk4  是不是调用layoutIfNeeded了

**Comment by HChong3210** [comment]
@ssjk4 
解决了吗, 我也遇到这个问题了

**Comment by githubTyd** [comment]
大哥 解决了吗？ 我做cell 嵌套 tableview  也出现这个问题 。

**Comment by ssjk4** [comment]
@HChong3210 @githubTyd 

> [self.tweetTextFiled mas_makeConstraints:^(MASConstraintMaker *make) {
make.bottom.equalTo(self.contentView).offset(-15).priority(MASLayoutPriorityDefaultLow);
}];

@anyuhao 的回复中解释了，bottom属性加priority(MASLayoutPriorityDefaultLow)就ok

**Comment by lvming6816077** [comment]
把约束的priority设置低点就可以了

**Comment by igiu1988** [comment]
设置优先级的确可以解决问题。我刚才试了MASLayoutPriorityDefaultLow，发先最后一个view的bottom没有紧贴cell，于是我改成了MASLayoutPriorityDefaultHigh，一切就都完美了。感谢 @ssjk4 @lvming6816077

**Comment by benzhemin** [comment]
@anyuhao @sunnyxx   我用ios8的self-sizing自动算高，可还是报约束冲突，修改bottom constraint的优先级确实可以，我困惑的是为什么用自动算高还会出现bottom - top 得到的高度不 == height 这种情况？cell的height本身不是约束设置好后求得的吗？

**Comment by gx2015** [comment]
是的 设置bottom优先级确实能完美解决问题 但是不知道为什么要做么做 疑惑中。。。

**Comment by KelaKing** [comment]
我也遇到，后来发现自己在fd_heightForCellWithIdentifier:中写错identifier了。。。

**Comment by iwill** [comment]
优先级确实能解决问题，但是完美的解决办法是这个 http://stackoverflow.com/a/19959217/456536

**Comment by weekwood** [comment]
@ssjk4 look like your issue solved. free feel to re-open.

**Comment by quyongtao** [comment]
> 设置优先级的确可以解决问题。我刚才试了MASLayoutPriorityDefaultLow，发先最后一个view的bottom没有紧贴cell，于是我改成了MASLayoutPriorityDefaultHigh，一切就都完美了。感谢 @ssjk4 @lvming6816077

亲测有效~厉害

**Comment by rondayu** [comment]
ssjk4，你好，你这个问题属于自己代码造成的约束冲突，跟缓存无关。
而且你这种情况只会在if (self.indexPath.row % 2 == 0) {make.height.equalTo(@(60));} 的时候出现。
我给你解释一下冲突问题在哪里：
首先你定义的图片顶部跟cell粘合，底部也跟cell粘合，此时你给定的图片高度为60.但是当前cell的高度只有30.
这种情况，你需要考虑的是你的数据源什么地方给定了cell的高度为30。是不是在heightforrow的地方给了30。只要是高度不足高，你这个约束冲突就会出现，但是你给的约束已经写死了，这样的约束写法是不合理，也不是自动约束提倡的。你给定了上下端的粘合，另外又给了60的高度，那么跟代码写法已经没有区别，自动布局约束也没有任何意义。

**Comment by karosLi** [comment]
> ssjk4，你好，你这个问题属于自己代码造成的约束冲突，跟缓存无关。
> 而且你这种情况只会在if (self.indexPath.row % 2 == 0) {make.height.equalTo(@(60));} 的时候出现。
> 我给你解释一下冲突问题在哪里：
> 首先你定义的图片顶部跟cell粘合，底部也跟cell粘合，此时你给定的图片高度为60.但是当前cell的高度只有30.
> 这种情况，你需要考虑的是你的数据源什么地方给定了cell的高度为30。是不是在heightforrow的地方给了30。只要是高度不足高，你这个约束冲突就会出现，但是你给的约束已经写死了，这样的约束写法是不合理，也不是自动约束提倡的。你给定了上下端的粘合，另外又给了60的高度，那么跟代码写法已经没有区别，自动布局约束也没有任何意义。

cell 高度即使是自动高度，在动态修改高度的时候，还是会有约束警告的，就像sunny说的，可能需要刷新tableview，但是这样感觉确实又会形成循环。
