### ISSUE TITLE
FDFeedCell中持有@property (nonatomic, strong) FDFeedEntity *entity;对象有什么作用？

### ISSUE THREAD

**Issue by realcrazysun** [forkingdog/UITableView-FDTemplateLayoutCell#148]
把这个成员变量删掉看着也没有问题  如果有用的话如果每个界面都要写这个Entity岂不是还是挺麻烦的一件事？
我理解的是在heightForRowAtIndexPath方法中先填充一下数据 通过fd_heightForCellWithIdentifier方法计算出对应高度  可是自己试了一下每次计算出来高度都是0.。。

**Comment by sunnyxx** [comment]
主要为了重载 setter，作为属性有个好处就是可以根据 `[tableView cellForRowAtIndexPath:indexPath].entity` 反查出 entity 来

**Comment by realcrazysun** [comment]
谢谢~ 还有请问一下有没有结合VFL语言的cell的example可以参考一下呢？我试了一下每次高度计算都是0  谢谢
