### ISSUE TITLE
是否适用于masonry手写约束？

### ISSUE THREAD

**Issue by qimuya3** [forkingdog/UITableView-FDTemplateLayoutCell#149]
是否适用于masonry手写约束？

**Comment by liwenDeng** [comment]
手写木有问题

**Comment by cythb** [comment]
只要确保约束，能确定cell的高度就可以了

**Comment by qimuya3** [comment]
但是在我这里有问题：环境：xcode7.1，iphone4。返回的高度永远都是：0，不知道为什么？
我的用法如下：
第一：HMSetCell 继承UITableViewCell 如下：
@implementation HMSetCell

- (void)awakeFromNib
{
    [super awakeFromNib];
    
    // Fix the bug in iOS7 - initial constraints warning
    self.contentView.bounds = [UIScreen mainScreen].bounds;
}

- (instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(nullable NSString *)reuseIdentifier
{
    self = [super initWithStyle:style reuseIdentifier:reuseIdentifier];
    [self setUp];
    return self;
    
}



-(void) setUp
{
    // Fix the bug in iOS7 - initial constraints warning
    self.contentView.bounds = [UIScreen mainScreen].bounds;
    UIView *v1 = [UIView new];
    UIView *v2 = [UIView new];
    
    v1.backgroundColor = RGB(0, 123, 123);
    v2.backgroundColor = RGB(123, 0, 123);
    
     WS(ww, self.contentView);
    [self.contentView addSubview:v1];
    [self.contentView addSubview:v2];
    
    [v1 mas_makeConstraints:^(MASConstraintMaker *make) {
        //
        make.top.left.right.equalTo(ww);
        make.height.mas_equalTo(40);
    }];
    
    [v2 mas_makeConstraints:^(MASConstraintMaker *make) {
        //
        make.top.equalTo(v1.mas_bottom).with.offset(10);
        make.left.right.equalTo(ww);
        make.height.mas_equalTo(40);
    }];

}
@end

第二：viewcontroller 使用如下：
//========= UITableView ===========
-(NSInteger)numberOfSectionsInTableView:(UITableView *)tableView{
    //    return 4;//0 大屏滚动热点，1 双排次热点，2 纪录片，3 军事片
    return 1;//0 大屏滚动热点，1 双排次热点，2 纪录片，3 军事片
}

-(CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath{
    
//    return [JYResource getTableCellHeight:3];
    float h =  [_tableView fd_heightForCellWithIdentifier:@"HMSetCell" configuration:^(id c) {
        UITableViewCell * cell = c;
        cell.fd_enforceFrameLayout = NO; // Enable to use "-sizeThatFits:"
        if (indexPath.row % 2 == 0) {
            cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
        } else {
            cell.accessoryType = UITableViewCellAccessoryCheckmark;
        }
    }];
    
    return h;
}

- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section{
    
    return 13;
}

-(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{
    return 3;
}

-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath{
    NSString *cellIdentifier = nil;
    UITableViewCell * cell = nil;
    
    cellIdentifier = @"HMSetCell";
    
    cell = [tableView dequeueReusableCellWithIdentifier:cellIdentifier forIndexPath:indexPath];
    
    if (!cell){
        cell = [[HMSetCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:cellIdentifier];
    }
    
    cell.fd_enforceFrameLayout = NO; // Enable to use "-sizeThatFits:"
    if (indexPath.row % 2 == 0) {
        cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    } else {
        cell.accessoryType = UITableViewCellAccessoryCheckmark;
    }
    
    return cell;
}

**Comment by liwenDeng** [comment]
@qimuya3  高度约束没对，这样试下
[v2 mas_makeConstraints:^(MASConstraintMaker *make) {
    //
    make.top.equalTo(v1.mas_bottom).with.offset(10);
    make.left.right.equalTo(ww);
    make.height.mas_equalTo(40);
    make.bottom.equalTo(ww);
}];

**Comment by sunnyxx** [comment]
手写系统约束或 Masonry 写约束都是可以的，需要保证约束完整性以及**约束设置时机**，算高发生之前所有约束必须就位
