### ISSUE TITLE
cell中设置图片高度过高

### ISSUE THREAD

**Issue by zooyf** [forkingdog/UITableView-FDTemplateLayoutCell#150]
问题描述：
我的设备是5s，在cell中设置手机截屏即640*1136像素的图片，会出现此错误。
图片被拉长，宽度是手机屏幕宽度，高度是1136。
请问如何解决此问题

**Comment by cythb** [comment]
手动设置图片高度的约束试试看呢？

**Comment by sunnyxx** [comment]
额，这个 Issue 好像和这个 repo 没关系吧
