### ISSUE TITLE
完全不能用，整个tableview变成灰色的一个色块

### ISSUE THREAD

**Issue by fuer4869** [forkingdog/UITableView-FDTemplateLayoutCell#151]
这是出错的界面：
![e1725856-b2b4-4ba3-9025-4b7a3ed4bb8f](https://cloud.githubusercontent.com/assets/4188115/12032841/9e84872c-ae57-11e5-8998-247fff885627.png)

这是我测试的源码，
![e97d7ff4-bb33-4c06-9181-006b6d61ceed](https://cloud.githubusercontent.com/assets/4188115/12032818/693711d4-ae57-11e5-9a60-023493a347e4.png)

这是cell的约束界面：
![14336f77-5958-4127-b60b-4a7839c3fb6c](https://cloud.githubusercontent.com/assets/4188115/12032880/0fb347a8-ae58-11e5-8d8f-1dd969e2103b.png)

环境：
Xcode7.2 
FDTemplateLayoutCell是最新的，刚刚fork下来的

**Comment by sunnyxx** [comment]
约束不完整，导致计算的高度为0

**Comment by PascoCoder** [comment]
@fuer4869 能否提示哪里约束不完整，我也遇到了这种情况，没发现约束不完整呀( ⊙ o ⊙ )

**Comment by yolii** [comment]
image需要有高度约束，否则是无法计算cell高度的 @PascoCoder
