### ISSUE TITLE
Why the breaking change for frame layout in 1.4?

### ISSUE THREAD

**Issue by skyline75489** [forkingdog/UITableView-FDTemplateLayoutCell#154]
从 1.3 升级到 1.4 之后，必须在 Cell 中加入 `fd_enforceFrameLayout` 才能使用基于 frame 的计算了，这种用法对于 Cell 来说入侵性太高了。

**Comment by sunnyxx** [comment]
你可以尝试下，无视这个属性，直接在非 Auto Layout 的 Cell 中重写 `- (CGSize)sizeThatFits:(CGSize)size` 方法

**Comment by sunnyxx** [comment]
因为判断是否在使用 AutoLayout 的逻辑在开启 Size Classes 时有 bug，所以改成了强制声明才会走 `- sizeThatFits:`

**Comment by skyline75489** [comment]
好吧，我没有使用 Size Classes，只能继续用 1.3 版本了。换用 1.4 的成本太高了。

**Comment by skyline75489** [comment]
@sunnyxx  感觉在 README 里把这一点说明一下会比较好，毕竟这是 1.3 -> 1.4 很重要的一个变化了，可能会有很多人被坑

**Comment by sunnyxx** [comment]
@skyline75489 行，可以先用着，在下个版本（1.5）试着着手解决这个问题，请关注更新。
