### ISSUE TITLE
crashed in iOS 7.0

### ISSUE THREAD

**Issue by ouyongyong** [forkingdog/UITableView-FDTemplateLayoutCell#155]
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[ valueForUndefinedKey:]: this class is not key value coding-compliant for the key _separatorHeight.'

and crashed in this line
[UITableView(FDTemplateLayoutCell) fd_heightForCellWithIdentifier:configuration:]

**Comment by neil-wu** [comment]
Yep, release 1.4 crash in iOS7

**Comment by sunnyxx** [comment]
@ouyongyong @neil-wu exactly 7.0 crash? I'm testing with an iOS 7.1 device.

**Comment by idealx** [comment]
@sunnyxx Yes, exactly 7.0 crash.

**Comment by idealx** [comment]
In iOS 7.0, UITableViewCell has no property 'separatorHeight', should use the way of 1.3 to get cell separatorHeight: 1.0 / [UIScreen mainScreen].scale.

**Comment by sunnyxx** [comment]
updated, re-pod install `1.4` please.

**Comment by xilin** [comment]
@sunnyxx  Maybe it is better to update the version number? I've use version `1.4` previously. And when I tried `pod update`/`pod install` again, the code didn't change.
