### ISSUE TITLE
不知道是我自己造的坑还是怎么的。

### ISSUE THREAD

**Issue by HongWeiChen** [forkingdog/UITableView-FDTemplateLayoutCell#156]
配合MJRefresh上拉加载更多的时候会出现无限加载，并且tableView空白（这时候只要随便拉动一下tableView，就可以回复正常，但是contentOffset处在的位置不正确）。
我这样说，您可能不明白，我希望能加下你的好友什么的，我将部分代码发给你什么的。或者详细讨论一下。
很普通的Cell。所有的Cell约束都已设置正常。

**Comment by HongWeiChen** [comment]
已经陷入迷茫状态了@.@

**Comment by HongWeiChen** [comment]
已经修复这个问题了~不好意思打扰了。

**Comment by HongWeiChen** [comment]
但是如果是一次性加载4、500个Cell就会加载缓慢，如果是10-20个还好，estimated的问题。而且旋转屏幕的情况下~更是要重新加载一遍estimated了~iOS7上这个估计你们也是无解么~~~？~如果能联系到开发者就好了~~

**Comment by sunjianan** [comment]
已经私聊解决~
