### ISSUE TITLE
崩溃在

### ISSUE THREAD

**Issue by AugustRush** [forkingdog/UITableView-FDTemplateLayoutCell#16]
- (void)fd_insertRowsAtIndexPaths:(NSArray *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation
{
    if (self.fd_autoCacheInvalidationEnabled) {
        [indexPaths enumerateObjectsUsingBlock:^(NSIndexPath *indexPath, NSUInteger idx, BOOL *stop) {
            NSMutableArray *rows = self.fd_cellHeightCache.sections[indexPath.section];
            [rows insertObject:@(_FDTemplateLayoutCellHeightCacheAbsentValue) atIndex:indexPath.row];
        }];
    }
    [self fd_insertRowsAtIndexPaths:indexPaths withRowAnimation:animation]; // Primary call
    [self fd_precacheIfNeeded];
}

**Comment by sunnyxx** [comment]
"这个 cell 只为了参加高度计算，不会真的显示到屏幕上；它通过 UITableView 的 -dequeueCellForReuseIdentifier: 方法 lazy 创建并保存，所以要求这个 ReuseID 必须已经被注册到了 UITableView 中，也就是说，要么是 Storyboard 中的原型 cell，要么就是使用了 UITableView 的 -registerClass:forCellReuseIdentifier: 或 -registerNib:forCellReuseIdentifier:其中之一的注册方法。"

**Comment by AugustRush** [comment]
这个我明白，但是如果我不用cacheHeight那个方法，只用普通的就不会崩溃，可能是我用了NSFechResultController来绑定的tableView，它的更新在插入的时候是无序的吧，所以有可能会导致数组的越界，然后就会崩溃到这里：[rows insertObject:@(_FDTemplateLayoutCellHeightCacheAbsentValue) atIndex:indexPath.row];，

**Comment by sunnyxx** [comment]
恩，我也试着构造一下这个问题。希望你那边也测试下插入时是不是table view 的数据源没有正确的更新，或者说 section 或row的插入有跳跃的插入，比如原来最大的index path是 [0: 10]，插入的是 [0: 12] 或者 [2: 0] 这样

**Comment by AugustRush** [comment]
我几乎可以确定是CoreData更新的时候有可能会是无序的，我加了if判断之后就好了，不知道会有别的什么问题？
 if (indexPath.row <= rows.count) {
                [rows insertObject:@(_FDTemplateLayoutCellHeightCacheAbsentValue) atIndex:indexPath.row];
            }

**Comment by sunnyxx** [comment]
我还是没能构造出来，要不试试用下面的代码替换那个函数：  
``` objc
- (void)fd_insertRowsAtIndexPaths:(NSArray *)indexPaths withRowAnimation:(UITableViewRowAnimation)animation
{
    if (self.fd_autoCacheInvalidationEnabled) {
        [self.fd_cellHeightCache buildHeightCachesAtIndexPathsIfNeeded:indexPaths]; // 加了这句
        [indexPaths enumerateObjectsUsingBlock:^(NSIndexPath *indexPath, NSUInteger idx, BOOL *stop) {
            NSMutableArray *rows = self.fd_cellHeightCache.sections[indexPath.section];
            [rows insertObject:@(_FDTemplateLayoutCellHeightCacheAbsentValue) atIndex:indexPath.row];
        }];
    }
    [self fd_insertRowsAtIndexPaths:indexPaths withRowAnimation:animation]; // Primary call
    [self fd_precacheIfNeeded];
}
```

**Comment by AugustRush** [comment]
这里又crash了：
- (void)fd_precacheIndexPathIfNeeded:(NSIndexPath *)indexPath
{
    if (![self.fd_cellHeightCache hasCachedHeightAtIndexPath:indexPath]) {
        CGFloat height = [self.delegate tableView:self heightForRowAtIndexPath:indexPath];
        [self.fd_cellHeightCache cacheHeight:height byIndexPath:indexPath];
        [self fd_debugLog:[NSString stringWithFormat:
                           @"precached - [%@:%@] %@",
                           @(indexPath.section),
                           @(indexPath.row),
                           @(height)]];
    }
}

**Comment by AugustRush** [comment]
CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__:

**Comment by sunnyxx** [comment]
哎，你这样贴代码让人咋定位问题嘛- - 等我这两天发一个修复bug后的版本你再试试看

**Comment by sunnyxx** [comment]
增加了一些修复和防御的代码，可以试试看
