### ISSUE TITLE
_separatorHeight 导致KVC异常crash

### ISSUE THREAD

**Issue by bibuliu** [forkingdog/UITableView-FDTemplateLayoutCell#162]
在iOS7中有大量这样的报错
NSUnknownKeyException:
this class is not key value coding-compliant for the key _separatorHeight. 这是相关报错信息

**Comment by KF5** [comment]
我正想说这个呢,在iOS7.1没有报错,但在iOS7.0时会报这个错误!!

**Comment by leasontou** [comment]
如何解决的？也没看到作者对这个问题有什么解决方法

**Comment by bibuliu** [comment]
最新版已修复
