### ISSUE TITLE
手动计算，是否会导致内存、CPU暴增？

### ISSUE THREAD

**Issue by zliuqing** [forkingdog/UITableView-FDTemplateLayoutCell#170]
你好，我这是用手动计算高度。高度没问题，缓存高度成功。但有个问题，加载数据进行高度计算时，内存暴增、CPU暴增，会内存不足crash。虽说我的cell数量多，计算高度复杂，但系统算高倒不至于双暴增和crash，盼作者回复这是什么问题，打开方式不对？

**Comment by HeathWang** [comment]
感觉跟框架没关系，你自己的cell写的有问题吧
