### ISSUE TITLE
代码奔溃了

### ISSUE THREAD

**Issue by cyqluowang** [forkingdog/UITableView-FDTemplateLayoutCell#171]
**\* Assertion failure in -[UITableView fd_templateCellForReuseIdentifier:], /Users/cyq/Documents/git/CarPrice/CarPrice/Pods/UITableView+FDTemplateLayoutCell/Classes/UITableView+FDTemplateLayoutCell.m:41
- Hook 1 (expr -- @import UIKit)
- Hook 2 (target stop-hook disable)
  2016-01-28 14:42:11.093 CarPrice[6288:2450021] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cell must be registered to table view for identifier - TableSampleIdentifier'

加了[self.tableView registerClass:[UITableViewCell class] forCellReuseIdentifier:@"TableSampleIdentifier"];

**Comment by xilin** [comment]
贴一下完整代码会比较好找问题
在哪注册的cell class?

**Comment by cyqluowang** [comment]
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath

**Comment by cyqluowang** [comment]
没有xib 纯代码的，但是怎么试都不行。

**Comment by zhangbofu** [comment]
哥们，注册在viewdidload中试试看

发自我的 iPhone

在 2016年1月28日，15:10，cyqluowang <notifications@github.com<mailto:notifications@github.com>> 写道：


没有xib 纯代码的，但是怎么试都不行。

―

**Comment by cyqluowang** [comment]
#pragma mark UITableViewDelegate
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath{
//    NSUInteger row = [indexPath row];
//    RecordData *data =[self.listData objectAtIndex:row];
//    if (data.model_d_detail_model.length) {
//        
//    }
//    
//    return 94;
    
    return [tableView fd_heightForCellWithIdentifier:@"TableSampleIdentifier" cacheByIndexPath:indexPath configuration:^(id cell) {
        NSUInteger row = [indexPath row];
        RecordData *data =[self.listData objectAtIndex:row];
        [cell setCellData:data];
    }];
}


- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath{
    static NSString *TableSampleIdentifier = @"TableSampleIdentifier";
    ResultCell *cell = [tableView dequeueReusableCellWithIdentifier:TableSampleIdentifier];
    if (cell == nil) {
        cell = [[ResultCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:TableSampleIdentifier];
    }
    [cell.ruku setTag:indexPath.row];
    NSUInteger row = [indexPath row];
    RecordData *data =[self.listData objectAtIndex:row];
    [cell setCellData:data];
    __weak __typeof(self) weakself = self;
    cell.submit = ^(NSInteger index){
        NSLog(@"222222222,%ld",index);
        [weakself submit:index];
    };
    return cell;

}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.listData =  [[NSMutableArray alloc] init];
    self.tableView = [[UITableView alloc]initWithFrame:CGRectMake(0, 0, FUll_VIEW_WIDTH, FUll_VIEW_HEIGHT) style:UITableViewStylePlain];
    self.tableView.delegate=self;
    self.tableView.dataSource=self;
    [self.view addSubview:self.tableView];
    
    self.listData =self.resultdata.gpj_list;
    [self.tableView reloadData];
    [self.tableView registerClass:[UITableViewCell class] forCellReuseIdentifier:@"TableSampleIdentifier"];
  }

**Comment by cyqluowang** [comment]
还是崩溃

**Comment by zhangbofu** [comment]
注册的时候别用UITableViewCell，用你自定义的那个类的名字注册呀

发自我的 iPhone

在 2016年1月28日，15:25，cyqluowang <notifications@github.com<mailto:notifications@github.com>> 写道：


还是崩溃

―

**Comment by cyqluowang** [comment]
[self.tableView registerClass:[ResultCell class] forCellReuseIdentifier:@"TableSampleIdentifier"];
一样啊。。。。 
QQ;573700261
求救啊

**Comment by xilin** [comment]
`ResultCell *cell = [tableView dequeueReusableCellWithIdentifier:TableSampleIdentifier];`
改成
`ResultCell *cell = [tableView dequeueReusableCellWithIdentifier:TableSampleIdentifier forIndexPath:indexPath];`

**Comment by cyqluowang** [comment]
我试试

**Comment by cyqluowang** [comment]
我试试

**Comment by cyqluowang** [comment]
还是不行啊@xillin

**Comment by xilin** [comment]
@cyqluowang 在你reload table之前就要先注册好cell
```
[self.tableView registerClass:[UITableViewCell class] forCellReuseIdentifier:@"TableSampleIdentifier"];
self.listData =self.resultdata.gpj_list;
[self.tableView reloadData];
```

**Comment by skyline75489** [comment]
@xilin  +1，肯定是要先注册，再做别的操作的

**Comment by cyqluowang** [comment]
我试试，很期盼有个纯代码的demo

**Comment by skyline75489** [comment]
@cyqluowang  我写过一个基于 Frame Layout 的纯代码的 Demo https://github.com/skyline75489/FDTemplateLayoutCell-Frame-Example 。需要使用 1.3 版本。可以参考一下。

**Comment by cyqluowang** [comment]
谢谢

**Comment by jhfkf** [comment]
哥们你的解决了吗？我的的不知道怎么就崩溃了 试了上面的所有方法了...

**Comment by cyqluowang** [comment]
还没有

**Comment by imagons** [comment]
static NSString *TableSampleIdentifier = @"TableSampleIdentifier";
ResultCell *cell = [tableView dequeueReusableCellWithIdentifier:TableSampleIdentifier];
if (cell == nil) {
cell = [[ResultCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:TableSampleIdentifier];
}
使用了这个  完全没有必要注册啊 自己去把你最开始的注册代码注释掉试试
