### ISSUE TITLE
在iOS 7.0.4 系统下会crash

### ISSUE THREAD

**Issue by lexiaoyao20** [forkingdog/UITableView-FDTemplateLayoutCell#174]
pod最新版本1.4，会因为valueForKey:separatorHeight 而 crash，而直接下载的代码就没这个问题。 
你们pod的版本没有和最新的代码同步啊

**Comment by sablib** [comment]
1.4是有这个问题，之后这个问题修复的时候没有更新pod的版本。
暂时先指定分支master就可以了。
