### ISSUE TITLE
对DEMO自适应有点疑问

### ISSUE THREAD

**Issue by zoujoe7750** [forkingdog/UITableView-FDTemplateLayoutCell#175]
![simulator screen shot 2016 2 23 11 44 11](https://cloud.githubusercontent.com/assets/3715569/13257053/2c56a8e4-da88-11e5-9dde-48921a2e8f51.png)

试了下DEMO有点疑问：
（1）、如图所示，分别对几个lable和image设置了背景颜色来观察高度的变化。
红色部分是没有图片的情况，我的理解是没图的情况是高度为0，或者有个高度但是应该不是一个会变化的值。
（2）、绿色部分为什么一个lable在空的情况有高度，而另一个会没有，我的理解是应该都是没有才对。

麻烦解答一下谢谢。

**Comment by liwenDeng** [comment]
@zoujoe7750 ->>> [传送门](http://adad184.com/2015/06/08/complex-cell-with-masonry/)

**Comment by weekwood** [comment]
@zoujoe7750 check 1.6.beta if issue solved
