### ISSUE TITLE
可否支持header和footer

### ISSUE THREAD

**Issue by 623637646** [forkingdog/UITableView-FDTemplateLayoutCell#176]
header 和 footer 的view 一般为 UITableViewHeaderFooterView 甚至是 UIView 而非 UITableViewCell。是否可以支持呢？

**Comment by BigPlane** [comment]
同求

**Comment by xuleiios** [comment]
求解答 我试了下 好像不行

**Comment by 623637646** [comment]
@xuleiios 还没有支持

**Comment by xuleiios** [comment]
@623637646 麻烦问一下 你的header和footer自适应高度是怎么做的 我现在是计算高度再回来刷新 这样reload时用户就会看到刷新的过程 不是很好看

**Comment by 623637646** [comment]
@xuleiios 约束设置自适应后， 用view 的 systemLayoutSizeFittingSize 方法计算大小

**Comment by 623637646** [comment]
@xuleiios 看下这个，对你有帮助 http://blog.sunnyxx.com/2015/05/17/cell-height-calculation/

**Comment by weekwood** [comment]
Supported
