### ISSUE TITLE
请问怎么不支持cell动画高度变化

### ISSUE THREAD

**Issue by tounaobun** [forkingdog/UITableView-FDTemplateLayoutCell#179]
http://stackoverflow.com/questions/460014/can-you-animate-a-height-change-on-a-uitableviewcell-when-selected/2063776#2063776

调用了
```
 [self.tableView beginUpdates];
 [self.tableView endUpdates];
```
高度不会发生变化

**Comment by 907064772** [comment]
请问解决了吗，我目前也遇到了这个问题
