### ISSUE TITLE
缓存高度问题

### ISSUE THREAD

**Issue by coldmn3** [forkingdog/UITableView-FDTemplateLayoutCell#181]
我的view结构比较特殊,是一个横向的UICollectionView,每个UICollectionViewCell里是一个tableView,然后tableView里有各种比较复杂的Cell.计算高度使用了
[tableView fd_heightForCellWithIdentifier:@"identifer" cacheByIndexPath:indexPath configuration:^(id cell) {
        // configurations
    }];
但是发现，似乎由于tableView在collectionViewCell里，不使用height cache，最初计算出来的高度0，后面几次计算才会计算出正常高度。如果使用了height cache,则会缓存第一次计算出来的高度0，导致了问题。

**Comment by ShelockWindy** [comment]
这个框架我看了，但是我觉得他这个优化不是很好啊，举个例子，用它自带的demo 在刷新那个微博的列表时明显有卡顿，而且我感觉选不选 indexCache 差别不明显，反正就是一个卡


------------------ 原始邮件 ------------------
发件人: "coldmn3";<notifications@github.com>;
发送时间: 2016年3月8日(星期二) 中午1:37
收件人: "forkingdog/UITableView-FDTemplateLayoutCell"<UITableView-FDTemplateLayoutCell@noreply.github.com>; 

主题: [UITableView-FDTemplateLayoutCell] 缓存高度问题 (#181)




我的view结构比较特殊,是一个横向的UICollectionView,每个UICollectionViewCell里是一个tableView,然后tableView里有各种比较复杂的Cell.计算高度使用了
 [tableView fd_heightForCellWithIdentifier:@"identifer" cacheByIndexPath:indexPath configuration:^(id cell) {
         // configurations
     }];
 但是发现，似乎由于tableView在collectionViewCell里，不使用height cache，最初计算出来的高度0，后面几次计算才会计算出正常宽度。如果使用了height cache,则会缓存第一次计算出来的高度0，导致了问题。

**Comment by coldmn3** [comment]
我把[tableView reloadData];去掉就好了，不调用reloadData tableView也会刷新。这是什么魔法？有同学能解释下吗。

**Comment by CaliosD** [comment]
我也遇到了第一次计算高度为0的问题，之后的计算才会正确。请问@coldmn3，你解决了么？

**Comment by coldmn3** [comment]
解决了，是我自己的constraints的问题。
