### ISSUE TITLE
問問题前请看这

### ISSUE THREAD

**Issue by anyuhao** [forkingdog/UITableView-FDTemplateLayoutCell#191]
前提:只框架只支持autoLayout, frame可以get out 模仿要是不会请离开,我是这样用的.一般没问题,卡顿问题不清楚.可以左上角...
使用基本步骤:
1.首先你要在设置代理之前调用: 
        [tableView registerClass:[TweetCell class] forCellReuseIdentifier:kCellIdentifier_Tweet];
        tableView.delegate = self; 
        tableView.dataSource = self;  //如果你的row count 存在则会执行 此处会执行计算高度.所以建议先注册再设置
如果你不按这个来,    UITableViewCell *templateLayoutCell = [self fd_templateCellForReuseIdentifier:identifier]; 可能为nil
2.不管你使用Masonry还是什么其他的autolayout都要明白一点
            // Auto layout engine does its math
            fittingSize = [templateLayoutCell.contentView systemLayoutSizeFittingSize:UILayoutFittingCompressedSize];
这句是这个框架得到高度的依据,如果你不知道怎么才会有值.请记住一点:
这个一点一定告诉系统: self.contentView 的bottom为多少.不告诉它,它不知道哪个是底部怎么给你计算高度.(所以你一定要记住,之前我也一直不会用这个框架,那是没去了解清楚.只是看了介绍多快.没介绍具体怎么用...当我明了了一点的时候摸摸头,可能最近太累了,这怎么简单的道理都不知道了)
//这是关键...
    [self.tweetTextFiled mas_makeConstraints:^(MASConstraintMaker *make) {
        make.bottom.equalTo(self.contentView).offset(-15).priority(MASLayoutPriorityDefaultLow);
    }];
//为什么会用这个属性呢.因为当你设置了top,left width/right的时候又设置了bottom.还设置了height这时候如果bottom - top 得到的高度不 == height就会导致高度变化,所以masonry会报 warning所以你需要设置优先级....height or bottom.
priority(MASLayoutPriorityDefaultLow);

 我认为:
如果你cell里面有一个 tableView
 那么这时候这个  tableView的高度需要自己去得计算.
我用的时候会出现高度为0的情况 ,忘记了iOS7还是都会了.
所以需要手动自己去计算
如果不对请forking dog  告诉.....

**Comment by songhailiang** [comment]
非常感谢~~~

**Comment by yangweicong** [comment]
good

**Comment by weekwood** [comment]
Thanks your help @anyuhao
