### ISSUE TITLE
 [self methodSignatureForSelector:nil]; 这句用啥用，不写会怎样

### ISSUE THREAD

**Issue by wanshanhu79** [forkingdog/UITableView-FDTemplateLayoutCell#196]
- (FDIndexPathHeightCache *)fd_indexPathHeightCache {
  FDIndexPathHeightCache *cache = objc_getAssociatedObject(self, _cmd);
  if (!cache) {
      [self methodSignatureForSelector:nil];
      cache = [FDIndexPathHeightCache new];
      objc_setAssociatedObject(self, _cmd, cache, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
  }
  return cache;
  }

不太明白为啥要写这一句   [self methodSignatureForSelector:nil];

**Comment by weekwood** [comment]
@wanshanhu79 I am closing this issue now, it is a useless code. Thank your help.
