### ISSUE TITLE
使用deleteRowsAtIndexPaths删除最后一个cell时crash

### ISSUE THREAD

**Issue by Bayonetta** [forkingdog/UITableView-FDTemplateLayoutCell#197]
使用deleteRowsAtIndexPaths删除最后一个cell时crash

如果使用deleteSectionsAtIndexSets就没事，使用reloaddata也没有问题

**Comment by shengyouxiao** [comment]
我也是在最后一个删除的时候崩溃了。

**Comment by jcccn** [comment]
@Bayonetta @shengyouxiao 
如果删除的是最后一个cell，导致了section数量的变化，这种情况下，最好使用这个方法代替：
`- (void)deleteSections:(NSIndexSet *)sections withRowAnimation:(UITableViewRowAnimation)animation`

**Comment by weekwood** [comment]
FYI #219
