### ISSUE TITLE
需求是：当cell内容过多的时候，限制最多显示5行，最后出现一个‘更多’按钮，点击cell展示全部内容，再点击收起，用这个库就做不了。

### ISSUE THREAD

**Issue by Cooooper** [forkingdog/UITableView-FDTemplateLayoutCell#199]
效果类似，app store 里某个软件的更新记录一样。用这个库做不了。

**Comment by ClearerMe** [comment]
@Cooooper 类似朋友圈“全文/展开”的效果吗？

**Comment by ClearerMe** [comment]
@Cooooper 可以做，numberOfLines完美实现。

**Comment by 13298897828** [comment]
为什么我用numberOfRows出现异常跳动@ClearerMe

**Comment by 13298897828** [comment]
numberOfRows,没图的时候才可以,有图就不可以是为什么

**Comment by Cooooper** [comment]
@ClearerMe  你是说直接设置numberOfLines 么 其他都不用改变？，我需要折叠起来的时候 出现一个【更多】按钮，类似微信朋友圈的【全文】和【收起】

**Comment by Cooooper** [comment]
对的，就是这样的效果，apple store 里的应用更新记录也是这样的效果。用怎么库怎么实现？

**Comment by ClearerMe** [comment]
@Cooooper 这个库，实际上就是根据 设置好的约束，以及设置可能会影响控件size的属性（比如label的字体，还有我们刚刚提到的numberOfLines等等）的值，来自动算出cell的高度（AutoLayout的博大精深）。所以设置numberOfLines，就可以cell的高度啦。

**Comment by songhailiang** [comment]
话说AppStore里更新记录后面那个“更多”是怎么加到label的后面的呢？还可以点击，用什么能实现？

**Comment by Kingson** [comment]
numberOfLines 在哪？

**Comment by hllGitHub** [comment]
请问有类似的Demo吗？想参考一下。不手动计算高度。
