### ISSUE TITLE
A free logo for your lovely team

### ISSUE THREAD

**Issue by lexrus** [forkingdog/UITableView-FDTemplateLayoutCell#2]
<img src="https://cloud.githubusercontent.com/assets/219689/7244961/4209de32-e816-11e4-87bc-b161c442d348.png" width="750" alt="banner"/>

<img src="https://cloud.githubusercontent.com/assets/219689/7244956/21e15d24-e816-11e4-8b6f-4519c201d924.png" width="512" alt="1024"/>

<img src="https://cloud.githubusercontent.com/assets/219689/7244974/68de23ba-e816-11e4-98c5-ab88a4d7770b.png" width="128" alt="128"/>

**Comment by expkzb** [comment]
@lexrus LOL.....

**Comment by philcn** [comment]
@lexrus thank you so much. we all loved this funny little thing.

**Comment by lexrus** [comment]
@expkzb @philcn My honor. Thanks.
