### ISSUE TITLE
调用reloadSections会崩溃

### ISSUE THREAD

**Issue by dongxinb** [forkingdog/UITableView-FDTemplateLayoutCell#20]
(void)fd_reloadSections:(NSIndexSet *)sections withRowAnimation:(UITableViewRowAnimation)animation

NSMutableArray *rows = self.fd_cellHeightCache.sections[idx];
运行到这句话崩溃，调用如下：

[_displayTableView reloadSections:[NSIndexSet indexSetWithIndex:0] withRowAnimation:UITableViewRowAnimationFade];

**Comment by sunnyxx** [comment]
传入的 section 是不是不在数据源里的 section？ 比如原来有“0”，“1”两个 section，而传入了 “2” section？

**Comment by dongxinb** [comment]
感谢回复！
不过问题应该不是在这里，因为我注释掉你代码中的加了fd的reloadSections的selector，然后再调用原方法，一切正常，并不会crash。

**Comment by sunnyxx** [comment]
新版本已经增加了越界问题的修复，请关注

**Comment by WeiweiYuan810** [comment]
1.3版本这个问题仍然存在
