### ISSUE TITLE
关于源代码中的几处疑惑。

### ISSUE THREAD

**Issue by leizh007** [forkingdog/UITableView-FDTemplateLayoutCell#201]
在这个` UITableView+FDIndexPathHeightCache.m`文件中
`static void __FD_TEMPLATE_LAYOUT_CELL_PRIMARY_CALL_IF_CRASH_NOT_OUR_BUG__(void (^callout)(void)) {
    callout();
}`
`#define FDPrimaryCall(...) do {__FD_TEMPLATE_LAYOUT_CELL_PRIMARY_CALL_IF_CRASH_NOT_OUR_BUG__(^{__VA_ARGS__});} while(0)
`
这个地方`FDPrimaryCall`直接调用`__FD_TEMPLATE_LAYOUT_CELL_PRIMARY_CALL_IF_CRASH_NOT_OUR_BUG__`这个函数不行吗？为什么要用`do{...}while(0)`包起来啊？
谢谢

**Comment by teng555teng** [comment]
do{...}while(0) 使{} 中的代码整合成一条语句 防止 一下类似代码出错
if(...)
    todo;
