### ISSUE TITLE
使用xib自定义cell,用拖曳的方式给子视图添加手势运行会崩溃

### ISSUE THREAD

**Issue by HApple** [forkingdog/UITableView-FDTemplateLayoutCell#203]
在Content View的subview里用xib拖曳的方式添加Tap Gesture Recognizer会崩溃

在UITableView+FDTemplateLayoutCell类里，112行
 templateCell = [self dequeueReusableCellWithIdentifier:identifier]; 崩溃在这里

用代码添加手势正常

**Comment by maplelover** [comment]
如果是以下错误的话：
'invalid nib registered for identifier (CellIdentifier) - nib must contain exactly one top level object which must be a UITableViewCell instance'

楼上你错怪FDTemplateLayoutCell了，就算不用这个库，该崩的还是会崩，添加了Tap Gesture Recognizer后，Top level object 已经变成了手势识别器，而系统只傻傻地直接取出来用。要真追究起来，应该算是系统的bug。

暂时想到的解决方案：
在Cell中用代码添加Gesture Recongizer

**Comment by HApple** [comment]
额啊，确实是这个错误，看来错怪了。。。

**Comment by PromiscuousYouth** [comment]
同上,求解

**Comment by hello--world** [comment]
原来是这个原因。
