### ISSUE TITLE
demo IB一点小疑问

### ISSUE THREAD

**Issue by dongqihouse** [forkingdog/UITableView-FDTemplateLayoutCell#204]
cell 中的空间高度是依赖contentView contentView是根据内容计算的，这个没什么问题。就是当内容为空的时候，这些拥有contentView控件的高度不应该为0么,为什么我用reveal查看即使为内容为空，cell里面的控件仍有高度（有点莫名其妙）。跪求解答头疼

**Comment by ClearerMe** [comment]
@dongqihouse 拥有contentView的控件 是指？
