### ISSUE TITLE
使用snapkit约束了cell中的label，但是cell得高度是0.5，而且cell都堆叠在一起。

### ISSUE THREAD

**Issue by xiuxingsang** [forkingdog/UITableView-FDTemplateLayoutCell#205]
使用snapkit约束了cell中的label，但是cell得高度是0.5，而且cell都堆叠在一起。

**Comment by xiuxingsang** [comment]
`override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        titleLabel = UILabel()
        titleLabel.textColor = UIColor.blackColor()
        titleLabel.textAlignment = NSTextAlignment.Center
        titleLabel.font = UIFont.systemFontOfSize(14)
        titleLabel.numberOfLines = 0
        titleLabel.sizeToFit()
        self.addSubview(titleLabel)
        
        titleLabel.snp_makeConstraints { (make) in
            make.top.equalTo(self.snp_top)
            make.bottom.equalTo(self.snp_bottom)
            make.right.equalTo(self.snp_right)
            make.left.equalTo(self.snp_left)
        }
        
    }`
cell中的label是这么写的。

**Comment by xiuxingsang** [comment]
`override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        titleLabel = UILabel()
        titleLabel.textColor = UIColor.blackColor()
        titleLabel.textAlignment = NSTextAlignment.Center
        titleLabel.font = UIFont.systemFontOfSize(14)
        titleLabel.numberOfLines = 0
        titleLabel.sizeToFit()
        self.addSubview(titleLabel)
        titleLabel.snp_makeConstraints { (make) in
            make.top.equalTo(self.snp_top)
            make.bottom.equalTo(self.snp_bottom)
            make.right.equalTo(self.snp_right)
            make.left.equalTo(self.snp_left)
        }
        
    }`
cell中的label是这么写的

**Comment by xiuxingsang** [comment]
`override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        titleLabel = UILabel()
        titleLabel.textColor = UIColor.blackColor()
        titleLabel.textAlignment = NSTextAlignment.Center
        titleLabel.font = UIFont.systemFontOfSize(14)
        titleLabel.numberOfLines = 0
        titleLabel.sizeToFit()
        self.addSubview(titleLabel)
        titleLabel.snp_makeConstraints { (make) in
            make.top.equalTo(self.snp_top)
            make.bottom.equalTo(self.snp_bottom)
            make.right.equalTo(self.snp_right)
            make.left.equalTo(self.snp_left)
        }
    }`
cell中的代码

**Comment by github410117** [comment]
同问，我也是全部都是0.5，全部重叠在了一起，请问解决了吗?

**Comment by HeathWang** [comment]
不是应该
self.contentView.addSubView(titleLabel)
不要把view加到cell的self上。
