### ISSUE TITLE
注册方法创建cell，崩溃：：Cell must be registered to table view for identifier

### ISSUE THREAD

**Issue by windtersharp** [forkingdog/UITableView-FDTemplateLayoutCell#206]
利用了tableView  registerClass：   forCellReuseIdentifier: 而不是alloc
哪里出问题了

**Comment by fdddf** [comment]
+1

**Comment by iStarEternal** [comment]
我就是rigister 没问题  请检查代码的完整性

**Comment by DarielChen** [comment]
代码没问题呀

**Comment by DarielChen** [comment]
删掉重新安装一下就好了,求解

**Comment by wangqianjun** [comment]
+1

**Comment by hwzss** [comment]
+1,注册了可就是崩溃，cellForRow方法中创建cell没问题，计算高时就奔溃了

**Comment by ios-archy** [comment]
+1,注册了可就是崩溃

**Comment by wuyaomin** [comment]
+1 注册了可就是崩溃  Cell must be registered to table view for identifier

**Comment by ios-archy** [comment]
-(UITableView *)MyContent
{
    if (!_MyContent) {
        _MyContent =[[UITableView alloc]initWithFrame:RECTMAKE(0, 0, kMainScreenWidth, kMainScreenHeight) style:UITableViewStylePlain];
        _MyContent.delegate = self;
        _MyContent.dataSource = self;
        _MyContent.separatorColor =[UIColor colorFromHexRGB:@"e0e0e0"];
        _MyContent.separatorInset = UIEdgeInsetsZero;
        _MyContent.showsVerticalScrollIndicator = NO;
//当前代码注释掉就好了，假如说没有注释掉的话，下面的注册cell代码不执行
//        if ([self.MyContent respondsToSelector:@selector(setLayoutMargins:)]) {
//            self.MyContent.layoutMargins = UIEdgeInsetsZero;
//        }
        [_MyContent registerClass:[HoteldeltalFirstCell class] forCellReuseIdentifier:HotelcellIndentifer1];
        [_MyContent registerClass:[HoteldetailNextCell class] forCellReuseIdentifier:HotelcellIndentifer2];
        _MyContent.tableHeaderView = self.HeaderView;
    }
    return _MyContent;
}

**Comment by songhailiang** [comment]
@ios-archy 你应该用_MyContent替代你注释掉的代码里的self.MyContent

**Comment by ios-archy** [comment]
@songhailiang   恩，应该是的，问题已经解决了，我是贴上来让更多人可以看到，问题出在哪里了，哈哈

**Comment by guakeliao** [comment]
+1

**Comment by balkarov** [comment]
+1

**Comment by 0xdatou** [comment]
个人出现这种情况是直接在- init：方法中进行注册，但是实例化的时候用的是initWithStyle：

但是实际调用情况是
- (id)init
{
    return [self initWithStyle:UITableViewStylePlain];
}
