### ISSUE TITLE
使用FD自动计算表格的高度出现图层混合

### ISSUE THREAD

**Issue by josercc** [forkingdog/UITableView-FDTemplateLayoutCell#209]
最后在优化性能 ,改善图层混合的问题 ,发现表格是红色的。 最后发现是因为frame存在小数点， 因为不能绘制的十分的精确才导致的， 但是用FD返回高度直接设置为整数 没解决问题 。FD内部直接计算好了， 请问用FD怎么解决计算小数点的问题？

**Comment by 15038777234** [comment]
发现 代码隐藏headView 返回了0.001导致的 可能不是FD的BUG Closed
