### ISSUE TITLE
iOS7上reloadSections或者reloadRowsAtIndexPaths闪退

### ISSUE THREAD

**Issue by zhcpeng** [forkingdog/UITableView-FDTemplateLayoutCell#210]
问题很严重，暂时只能用reloadData解决，之前没发现过这问题，如果解决不了之后肯定不会继续使用这个的

**Comment by iStarEternal** [comment]
你这个地方应该用insertRowsAtIndexPaths，这不是神烦狗的问题，是你使用不当的问题

**Comment by zhcpeng** [comment]
@iStarEternal 不是这个原因，我确实是要reload而不是insert。
问题找到了，越界问题，indexSetWithIndex我传的是数组的count，此处应该是count - 1。
犯的这低级错误，无语了
