### ISSUE TITLE
请问，如果我的Cell的内容布局完全是手算的，FD支持自动计算高度吗？

### ISSUE THREAD

**Issue by zhangchioulin** [forkingdog/UITableView-FDTemplateLayoutCell#215]
如果我的Cell的内容完全是手算的，没有用到任何的相对布局，纯代码手算的位置，FDTemplateLayoutCell 支持计算高度吗？
我试了下没有出现崩溃的问题，但是高度却一直是45.f 所以我问下。谢谢

**Comment by oceantang** [comment]
不支持的，两种方式二选一。
1、autolayout
2、sizeThatFits
