### ISSUE TITLE
deleteRowsAtIndexPaths最后一个cell时crash

### ISSUE THREAD

**Issue by Penton** [forkingdog/UITableView-FDTemplateLayoutCell#219]
使用deleteRowsAtIndexPaths删除最后一个cell时crash，这时候使用deleteSections，但是如果是最后一个sections时也会crash

**Comment by linsyorozuya** [comment]
+1

**Comment by qingnaniso** [comment]
有类似的问题

**Comment by weekwood** [comment]
@Penton Think you forget to delete from array first. also, don't forget to add beginUpdate and endUpdate tag when you call deleteRowsAtIndexPaths.

**Comment by weekwood** [comment]
I tested from demo project it works. So close this issue for now. free feel to re-open
