### ISSUE TITLE
一定要用nib吗？

### ISSUE THREAD

**Issue by agan112** [forkingdog/UITableView-FDTemplateLayoutCell#22]
我的cell是代码写的可以吗？不用nib的画，fd_templateCellForReuseIdentifier这个方法就会断言必需注册identifier，并退出程序。

**Comment by sunnyxx** [comment]
不是一定用 nib 写，但必须要走 UITableView 的注册机制， 要么 registerNib 要么 registerClass，这个在 README 中已经解释过了。

**Comment by agan112** [comment]
thanks
