### ISSUE TITLE
[self methodSignatureForSelector:nil]; 使用JSPatch后，这句会产生Crash

### ISSUE THREAD

**Issue by li6185377** [forkingdog/UITableView-FDTemplateLayoutCell#223]
![image](https://cloud.githubusercontent.com/assets/1924211/16678163/10ac14ac-450f-11e6-8ae1-faf1ce7b82d8.png)

**Comment by weekwood** [comment]
JSPatch has abandoned by Apple

**Comment by weekwood** [comment]
@li6185377 removed from 1.6.release
