### ISSUE TITLE
页面闪动

### ISSUE THREAD

**Issue by xingchenxiaoyao** [forkingdog/UITableView-FDTemplateLayoutCell#232]
当cell中用到NSMutableAttributedString的方法initWithData: options: documentAttributes: error:(NSError **)error;读取HTML语言时。再用此方法设置cell的自适应高度，为什么会有闪动的现象。怎么才能消除，求指点

**Comment by weekwood** [comment]
If still has an issue, Please upload a Gif. And demo code.
