### ISSUE TITLE
在cell的layoutSubviews方法写约束，识别为frame

### ISSUE THREAD

**Issue by zzgo** [forkingdog/UITableView-FDTemplateLayoutCell#233]
首先谢谢开源。
我在cell的layoutSubviews方法里，使用Masonry写布局，结果一直按frame的来算。不能自动布局算高。后来我都改了一下写布局的位置就没问题了。
出问题的code大概是这样的:

```
- (instancetype)initWithStyle:(UITableViewCellStyle)style
              reuseIdentifier:(NSString *)reuseIdentifier
{
    self = [super initWithStyle:style reuseIdentifier:reuseIdentifier];
    if (!self) {
        return nil;
    }
   [self.contentView addSubview:self.labelA];
   [self.contentView addSubview:self.labelB];
    return self;
}



- (void)layoutSubviews
{
   [super layoutSubviews];
   [self.labelA mas_makeConstraints:^(MASConstraintMaker *make) {
     xxxx
    }];
   [self.labelB mas_makeConstraints:^(MASConstraintMaker *make) {
     xxxx
    }];
}
```

**Comment by weekwood** [comment]
@zzgo think you should put auto layout code in `updateConstraints `, and if you want to force update constraints. please call `layoutIfNeeded` instead.

> To force the system to update the layout of a view tree immediately, you can call layoutIfNeeded/layoutSubtreeIfNeeded (on iOS and OS X respectively). This can be helpful if your next steps rely on the views’ frame being up to date.

**Comment by zzgo** [comment]
@weekwood Thank you.It is  helpful to me！

**Comment by tianglin** [comment]
@zzgo 我也是用Masonry布局的，一直出现警告：[FDTemplateLayoutCell] Warning once only: Cannot get a proper cell height (now 0) from '- systemFittingSize:'(AutoLayout). You should check how constraints are built in cell, making it into 'self-sizing' cell.
![455cd468-ff96-4d6e-b76e-692eec2e1834](https://cloud.githubusercontent.com/assets/1657594/25794569/1791d36c-3404-11e7-92c2-7300a11960a0.jpeg)

**Comment by weekwood** [comment]
@tianglin I am not familiar about Masonry. but you should follow Masonry guide to use `mas_reamke` api
https://github.com/SnapKit/Masonry#where-should-i-create-my-constraints

**Comment by zzgo** [comment]
@tianglin 直接在初始化的方法里写约束就ok了，不用调updateConstraints也行。
