### ISSUE TITLE
AutoSizeClass下仅遵循Any/Any模式约束

### ISSUE THREAD

**Issue by darkThanBlack** [forkingdog/UITableView-FDTemplateLayoutCell#235]
唔...(发issue好紧张,会不会被鄙视,会不会被打
先上步骤描述

1.
1.1>在Any/Any模式下,没有任何控件和约束
1.2>在w:Compact/h:Regular模式下拖入一个Label2,高度默认,上/下/左/右间距为50/50/8/8
1.3>运行后,发现出现了那个经典的错误画面(图我先不放了),没有显示任何cell

2.
2.1>在Any/Any模式下拖入一个Label1,高度默认,上/下/左/右间距为8
2.2>在w:Compact/h:Regular模式下拖入一个Label2,高度默认,上/下/左/右间距为50/50/8/8
2.3>运行后,发现cell的高度计算依从于Label1的约束
2.4>同时发现,Label2的位置是根据cell的高度反推计算而成的

怎么说呢......
AutoSizeClass的优先级肯定是Any/Any最高,其他模式会默认继承他的控件和约束,但是因为默认画布一般是600*600,我布局时会习惯切换到w:Compact模式下,结果这次就出问题了,害我找了我好久的原因,结果发现其他模式下的一堆东西全部没有卵用T~T
请问下各路大神,这个除了必须在Any/Any模式下布局外,还有没有其他的解决方案呢?

**Comment by darkThanBlack** [comment]
@philcn @sunnyxx

**Comment by weekwood** [comment]
Think this issue already out of time. I am closing for now.
