### ISSUE TITLE
含多种cell时，不可-registerClass:forCellReuseIdentifier:怎么办

### ISSUE THREAD

**Issue by liuzhiyi1992** [forkingdog/UITableView-FDTemplateLayoutCell#237]
好像必须提前为tableview注册cell的类，但是如果tableview内需要使用多个不同的cell怎么办?

**Comment by darkThanBlack** [comment]
@liuzhiyi1992 可以注册多个identifier不同的cell,然后在cellForRow中根据identifier来区分,仔细看文档即可.

**Comment by liuzhiyi1992** [comment]
@darkThanBlack 目前也是这么做的，这样的话只能用dequeueReusableCellWithIdentifier:了，而且有20几种cell，得想个好办法动态布置

**Comment by liuzhiyi1992** [comment]
@darkThanBlack 朋友的意思是说多个registerClass也是有效的？

**Comment by darkThanBlack** [comment]
@liuzhiyi1992 registerClass当然可以注册多个;

我的代码:
[basicTableView registerClass:[A class] forCellReuseIdentifier:NSStringFromClass([A class])];
[basicTableView registerClass:[B class] forCellReuseIdentifier:NSStringFromClass([B class])];
然后
if(xx)
{
    NSString *cellIdentifier = NSStringFromClass([A class]);
                NewGuideEvaluationCell *cell = [tableView dequeueReusableCellWithIdentifier:cellIdentifier];
}
else if(xx)
{
    NSString *cellIdentifier = NSStringFromClass([B class]);
                NewGuideEvaluationCell *cell = [tableView dequeueReusableCellWithIdentifier:cellIdentifier];
}
......

**Comment by darkThanBlack** [comment]
@liuzhiyi1992 而且什么需求会用到20几个cell......

**Comment by liuzhiyi1992** [comment]
@darkThanBlack 感谢，之前就是在怀疑可否多次registerClass。20几种cell是因为很多种业务重用一个tableview代码。每个tableview里会用到一两种cell
