### ISSUE TITLE
一个tableview中两种cell该怎样适应高度啊？

### ISSUE THREAD

**Issue by february29** [forkingdog/UITableView-FDTemplateLayoutCell#239]
tableview 注册cell的时候怎样注册？

**Comment by wonderffee** [comment]
不应该是分别注册？题目信息过少

**Comment by february29** [comment]
在初始化tableview的时候得注册cell  
例如：[mTableView registerClass:[PurchaseApplayTableCell class] forCellReuseIdentifier:@"PurchaseApplayTableCell"];（没有这句话fd没发工作）

如果我有两个cell  能写成类似这样的么
[mTableView registerClass:[PurchaseApplayTableCell1 class] forCellReuseIdentifier:@"PurchaseApplayTableCell1"];

[mTableView registerClass:[PurchaseApplayTableCell2 class] forCellReuseIdentifier:@"PurchaseApplayTableCell2"];  用来注册两个么？


另：我用到了masnory纯代码布局 没有xib文件。

**Comment by wonderffee** [comment]
对啊，就是这样
