### ISSUE TITLE
Xcode 8 计算高度有问题 会定高 用Xcode7就没问题,求解决

### ISSUE THREAD

**Issue by zb737472783** [forkingdog/UITableView-FDTemplateLayoutCell#241]

**Comment by zhangzhe0309** [comment]
我的也有点问题，iOS10 上用fd算的高度有，但是tableview上不出现，调试视图也没有，不知道是不是写法问题，暂时先用systemLayoutSizeFittingSize

**Comment by xylinuxkernel** [comment]
项目已经上线了 升级到ios10各种错乱

**Comment by zb737472783** [comment]
我的iOS10没问题，但是换开发工具Xcode 8 编译运行有部分cell高度有问题，是定高的，目前在用Xcode 7.3.1开发。

**Comment by weekwood** [comment]
@zb737472783 try 1.6.beta see if issue fixed. please re-open if still not working
