### ISSUE TITLE
为什么tableviewController里面使用没问题，而使用ViewController里面套一个tableview计算出来的高度有问题？

### ISSUE THREAD

**Issue by hevi1991** [forkingdog/UITableView-FDTemplateLayoutCell#246]
大神，求救~ 做了个demo，相同的cell，相同的约束，datasource，delegate也相同，计算出来的高度不同。

**Comment by iHTCboy** [comment]
我表示没有问题，自己查一下原因，或提供demo链接。

**Comment by weekwood** [comment]
@hevi1991 feel free  to re-open if still issues or provide a demo project
