### ISSUE TITLE
iOS10高度计算问题（这回问题可以描述清楚，用这个库的demo就可以出现）

### ISSUE THREAD

**Issue by yrx0910** [forkingdog/UITableView-FDTemplateLayoutCell#247]
希望大神帮忙解决一下。
我想实现一个功能类似微信朋友圈的点赞和评论的菜单的显示和隐藏，我就改变包含这个菜单容器的宽度约束的constant的值，0隐藏，120显示，然后又想有动画所以需要调layoutIfNeeded。我在cell中调用这个方法布局就有问题啦。
我在demo中的FDFeedCell中的- (void)setEntity:(FDFeedEntity *)entity方法中加 [self.contentView layoutIfNeeded];布局在iOS9模拟器没问题，在iOS10模拟器就乱拉。希望大神帮忙看看。

**Comment by yrx0910** [comment]
这是一个问题？可能是布局都还没出来，我就去刷新界面了，重新布局的事。通过这个问题，我看了作者的源码，收货颇多，谢谢。这个库在ios 10，xcode8中也是完美的，谢谢作者写一个这么好的库。有些地方不是很清楚，不知道作者怎么想到下面的代码的，这是什么原理呢？希望有大神可以解答一下。
  // Add a hard width constraint to make dynamic content views (like labels) expand vertically instead
        // of growing horizontally, in a flow-layout manner.
        NSLayoutConstraint *widthFenceConstraint = [NSLayoutConstraint constraintWithItem:cell.contentView attribute:NSLayoutAttributeWidth relatedBy:NSLayoutRelationEqual toItem:nil attribute:NSLayoutAttributeNotAnAttribute multiplier:1.0 constant:contentViewWidth];
        [cell.contentView addConstraint:widthFenceConstraint];

**Comment by wanhmr** [comment]
添加 widthFenceConstraint 约束，就是为了解决鸡生蛋，蛋生鸡问题，因为 contentView 没有宽度约束，内部的子 view 就不能得到高度

**Comment by benzhemin** [comment]
我觉得是解决iOS7的兼容性的问题，iOS7 dequeue出来的cell是没有宽的约束的

**Comment by yrx0910** [comment]
这个库不更新了么？都一年没有更新了。

**Comment by weekwood** [comment]
@yrx0910 free feel to re-open if still issues
