### ISSUE TITLE
你好 ，我用这个框架，会出现单元格重叠，单元格被压扁的情况，但是滑动一下就恢复正常了

### ISSUE THREAD

**Issue by hejintaochenxin** [forkingdog/UITableView-FDTemplateLayoutCell#249]
你好 ，我用这个框架，会出现单元格重叠，单元格被压扁的情况，但是滑动一下就恢复正常了，请问这是什么原因？代码 是直接照着你demo来写的。 请指点  谢谢

**Comment by yangzhixiao** [comment]
我也出现了这个问题，可以通过这样解决
```
    override func viewWillAppear(_ animated: Bool) {
        tableView.delegate = self
        tableView.dataSource = self
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        tableView.delegate = nil
        tableView.dataSource = nil
    }
```
但是这样的话，就会失去上次滑动的位置了，所以还是自己去计算高度，缓存高度好了

**Comment by york17** [comment]
我也遇到这个问题，我的问题是我使用了    dispatch_async( dispatch_get_main_queue(), ^{
        //执行UI变化
    });

而后我把    dispatch_async( dispatch_get_main_queue(), ^{
        
    });

去掉，就可以了，你可以试一下

**Comment by Kingson** [comment]
我也出现了一样的问题

**Comment by weekwood** [comment]
I closed this issue for now. feel free to re-open it if still valid
