### ISSUE TITLE
隐藏某个控件

### ISSUE THREAD

**Issue by trudger123** [forkingdog/UITableView-FDTemplateLayoutCell#25]
cell 从上到下有一个label，一个scroll view， 另外一个label。scroll view在没有内容的时候，会隐藏起来。这种情况下，似乎高度还是会算上scroll view，导致中间空白。有解决办法吗?

**Comment by philcn** [comment]
你是手动隐藏scroll view的吧，这时你需要把scroll view的高约束（或固有高度）设成0，只通过设置hidden并无法做到。可以使用 https://github.com/forkingdog/UIView-FDCollapsibleConstraints

**Comment by trudger123** [comment]
设置高度约束的确能解决问题。谢谢。

**Comment by trudger123** [comment]
另外提意见建议。我在使用过程中发现ios自动算高和你的这个扩展算高，都会出现lable少一行的问题。我想这可能是由于你的扩展也使用了系统算高的方式。我现在的做法是使用你的缓存机制，但高度计算用sizeThatFits 提供。

问题在于你的代码中凡是有任何约束，就使用自动算高的机制     
BOOL autoLayoutEnabled = cell.contentView.constraints.count > 0 ? YES : NO;
因此我不得不更改代码，手工设置为false。

是否可以考虑把autoLayoutEnabled 开放成一个属性？

**Comment by tigerZhang86** [comment]
我也遇到上面这位朋友的问题，在计算label的高度少了一行

**Comment by sunnyxx** [comment]
我在新版本（1.3）里面增加了强制使用 `sizeThatFits:`方式获取高度的开关：  
``` objc
// in configure block
cell.fd_enforceFrameLayout = YES;
```

**Comment by trudger123** [comment]
测试没有问题，感谢！
