### ISSUE TITLE
cell 设置的时候轻微卡顿

### ISSUE THREAD

**Issue by zhaoyunyi** [forkingdog/UITableView-FDTemplateLayoutCell#251]
环境是IOS9.3 ip6 plus 
慢慢滑动的时候 cell 重用进行设置控件，更新约束的是会有卡顿，快读上下滑动缺一点也不卡，不知道是不是约束多的问题。。一个cell 里大概10多个控件，10来个约束。。同机 使用微信也有类似现象，如何进行优化？谢谢指导

**Comment by afantree** [comment]
用Instrument找找卡顿的原因？ 
并不是所有的卡顿都是约束的锅，还可能是Image太大？主线程计算量大？ 等等。。。
