### ISSUE TITLE
您好 我把您的代码 重新自己敲了一遍发现一个小的问题

### ISSUE THREAD

**Issue by DSPerson** [forkingdog/UITableView-FDTemplateLayoutCell#259]
- (void)invalidateHeightAtIndexPath:(NSIndexPath *)indexPath {
 [self buildCachesAtIndexPathsIfNeeded:@[indexPath]];
    [self enumerateAllOrientationsUsingBlock:^(FDIndexPathHeightsBySection *heightsBySection) {
        heightsBySection[indexPath.section][indexPath.row] = @-1;
    }];
}
使用此方法的时候。您调用了横/竖 数组 全部改成[indexPath.section][indexPath.row] = -1; 
我觉得应该使用 current 的数组 更为恰当一些

**Comment by afantree** [comment]
如果出错的话，就全部给清空了，只清空current ，可能脏数据还在。

**Comment by afantree** [comment]
heightsBySectionForCurrentOrientation取到的数组与当前的屏幕有关系的。如果出错的话，都给清空了，只清空current ，可能脏数据还在。
