### ISSUE TITLE
crash in iOS 10.2

### ISSUE THREAD

**Issue by 4dmoonlight** [forkingdog/UITableView-FDTemplateLayoutCell#263]
fittingSize = [templateLayoutCell.contentView systemLayoutSizeFittingSize:UILayoutFittingCompressedSize];

**Comment by 4dmoonlight** [comment]
//            NSLayoutConstraint *widthFenceConstraint = [NSLayoutConstraint constraintWithItem:templateLayoutCell.contentView attribute:NSLayoutAttributeWidth relatedBy:NSLayoutRelationEqual toItem:nil attribute:NSLayoutAttributeNotAnAttribute multiplier:1.0 constant:contentViewWidth];
//            [templateLayoutCell.contentView addConstraint:widthFenceConstraint];
            // Auto layout engine does its math
            fittingSize = [templateLayoutCell.contentView systemLayoutSizeFittingSize:UILayoutFittingCompressedSize];
//            [templateLayoutCell.contentView removeConstraint:widthFenceConstraint];
按以上注释代码以后不出现crash了

**Comment by WeiweiYuan810** [comment]
注释以后虽然不会crash了，但是同时计算得到的Size也不再正确了，包括里面UILabel（多行）的布局也出问题了。打算换回系统方法了，直接设置tableView.estimatedRowHeight = 44; tableView.rowHeight = UITableViewAutomaticDimension;

**Comment by 4dmoonlight** [comment]
是的，只是不出现crash了，高度算不对了

**Comment by 4dmoonlight** [comment]
在我这里只有动态取cell的idf的时候会crash，cell只有一种的时候不会crash

**Comment by niunaruto** [comment]
+1

**Comment by appjar** [comment]
the same issue.

**Comment by WeiweiYuan810** [comment]
解决了。

1. 删除UITableView+FDTemplateLayoutCell.m中的第43行代码；
````
templateCell.contentView.translatesAutoresizingMaskIntoConstraints = NO;
````

2. 将UITableView+FDTemplateLayoutCell.m中第100-104行代码
````
NSLayoutConstraint *widthFenceConstraint = [NSLayoutConstraint constraintWithItem:templateLayoutCell.contentView attribute:NSLayoutAttributeWidth relatedBy:NSLayoutRelationEqual toItem:nil attribute:NSLayoutAttributeNotAnAttribute multiplier:1.0 constant:contentViewWidth];
[templateLayoutCell.contentView addConstraint:widthFenceConstraint];
// Auto layout engine does its math
fittingSize = [templateLayoutCell.contentView
systemLayoutSizeFittingSize:UILayoutFittingCompressedSize];
[templateLayoutCell.contentView removeConstraint:widthFenceConstraint];
````
替换为
````
fittingSize = UILayoutFittingCompressedSize;
fittingSize.width = CGRectGetWidth(self.frame);
fittingSize = [templateLayoutCell systemLayoutSizeFittingSize:fittingSize withHorizontalFittingPriority:UILayoutPriorityRequired verticalFittingPriority:UILayoutPriorityFittingSizeLevel];
````
#257

**Comment by jb522185660** [comment]
我在最新的版本里面没有看到那一段代码啊

**Comment by WeiweiYuan810** [comment]
@jb522185660 这个是基于1.4 release的修改

**Comment by niunaruto** [comment]
应该也不能算是这个三方的问题，我们的定位到了代码中的一个约束导致的，修改后正常了

**Comment by TESTSUP** [comment]
其实把cell里面用到的UILabel，都设置上preferredMaxLayoutWidth就不会崩溃了

**Comment by fireup** [comment]
我也有此问题，但是不止是在10.2上。iOS8 以上我都改为用autodimension了，但ios7上还是crash。。。

**Comment by 4dmoonlight** [comment]
autodimension 感觉性能不是很好

**Comment by wanhmr** [comment]
这个可以确定是 iOS 10.2 的bug, 已经解决了 crash  的问题，确实只要设置 UILabel  的preferredMaxLayoutWidth 就可以。
我已经提交了PR，在这基础上作了优化。
🔗https://github.com/forkingdog/UITableView-FDTemplateLayoutCell/pull/264

**Comment by wanhmr** [comment]
如果大家用UILabel，左右一定要用等于，如果不用，一定要设置 preferredMaxLayoutWidth。折腾了好久。

**Comment by fireup** [comment]
谢谢，确实是这样。
我有两个UILabel，右边的设置了width constraint最小值。把这个constraint去掉，改成content compression resistance priority: required，就好了。

**Comment by 4dmoonlight** [comment]
@WeiweiYuan810 有时候高度返回会为0

**Comment by manajay** [comment]
@TESTSUP  确实 将xib 中所有的label  都设置preferredMaxLayoutWidth Explicit 就可以了

**Comment by MrLJnull** [comment]
@wanhmr 非常感谢，我的cell左右有两个label，左边label设置的label.right.lessThanEqualTo(self.contentView.mas_centerX),改成equalTo 就行了

**Comment by benzhemin** [comment]
@WeiweiYuan810 可否讲一下原理？
