### ISSUE TITLE
内容在显示时才去网络请求，这种cell高度如何处理？

### ISSUE THREAD

**Issue by Kingson** [forkingdog/UITableView-FDTemplateLayoutCell#267]
当Cell中的Lable内容，需要在显示的时，才去网络请求。这种情况的Cell高度如何处理？

**Comment by afantree** [comment]
1. 先设置个默认值，有数据之后，再刷新界面。
为什么需要在显示时才网络请求？为了懒加载吗？
一般是图片等耗时的资源才做懒加载吧？
