### ISSUE TITLE
tableview reloaddata 的时候会走 算高度的方法 然后将所有cell移除掉 出现了闪屏的情况

### ISSUE THREAD

**Issue by xiaolong11** [forkingdog/UITableView-FDTemplateLayoutCell#269]
tableview reloaddata 的时候会走 算高度的方法 然后将所有cell移除掉 出现了闪屏的情况 望楼主帮忙看下

**Comment by weekwood** [comment]
Look like you reset your data source. can you double check, feel free to re-open if still has the issues
