### ISSUE TITLE
"multiple methods named 'xxx:' found” error

### ISSUE THREAD

**Issue by nonstriater** [forkingdog/UITableView-FDTemplateLayoutCell#27]
![image](https://cloud.githubusercontent.com/assets/3192105/7790983/68f3681a-02c9-11e5-8ba7-5760cd5f2a0f.png)

能在这里加一个强类型转换（NSArray *）吗？,我其它类也定义了removeObjectAtIndex:

**Comment by sunnyxx** [comment]
Fixed in 1.3
