### ISSUE TITLE
上拉加载过程会有卡顿

### ISSUE THREAD

**Issue by lingfengmarskey** [forkingdog/UITableView-FDTemplateLayoutCell#277]
使不使用缓存的方法都会出现卡顿现象

**Comment by weiminghuaa** [comment]
这个解决了吗，为什么我还是有卡顿@weekwood

**Comment by weiminghuaa** [comment]
<img width="898" alt="2017-06-21 17 55 11" src="https://user-images.githubusercontent.com/2723525/27378769-7a707b9a-56ab-11e7-8de3-a70c1fd940e5.png">

**Comment by weiminghuaa** [comment]
把demo的insertSection方法改一下，也能重现卡顿

`- (void)insertSection {
//    [self.feedEntitySections insertObject:@[self.randomEntity].mutableCopy atIndex:0];
//    [self.tableView insertSections:[NSIndexSet indexSetWithIndex:0] withRowAnimation:UITableViewRowAnimationAutomatic];
    NSMutableArray *temp = [NSMutableArray array];
    for (int i = 0; i < 50; i++) {
        [temp addObject:[self randomEntity]];
    }
    [self.feedEntitySections[0] addObjectsFromArray:temp];
    [self.tableView reloadData];

}`
