### ISSUE TITLE
ios10.2之后处理label自动换行时候会崩溃

### ISSUE THREAD

**Issue by stone54240** [forkingdog/UITableView-FDTemplateLayoutCell#278]
- (CGFloat)fd_systemFittingHeightForConfiguratedCell:(UITableViewCell *)cell 方法里的
fittingHeight = [cell.contentView systemLayoutSizeFittingSize:UILayoutFittingCompressedSize].height;这行在调用系统方法时候会被UIkit断言阻隔。导致崩溃

**Comment by ieliwb** [comment]
怎么解决啊，我也是这里崩溃了

**Comment by stone54240** [comment]
母鸡呀

**Comment by yiios** [comment]
设置 cell 中 label 的 preferredMaxLayoutWidth 属性可以暂时解决这个问题

**Comment by 631106979** [comment]
preferredMaxLayoutWidth，有的地方没设置没崩溃，有的地方会崩溃，具体是什么原因导致的有人知道么

**Comment by yiios** [comment]
不太清楚 
我目前已知的触发条件是有两个
1. 10.2系统以上 
2. label 需要换行

**Comment by faimin** [comment]
尽量少用或者不用`大于等于或者小于等于`这种约束，这种约束会使`autolayout`的计算量增加，而且假如在一个方向上有多个视图，其中包含换行`label`，并在其上添加`大于等于`这种约束的话，有可能就会导致crash

**Comment by stone54240** [comment]
对，只有在10.2以上需要自动换行才会出现。

**Comment by yiios** [comment]
@faimin 
为什么在10.2上这个问题才会出现呢 难道10.2系统修改了关于 lable 换行计算的机制?

**Comment by faimin** [comment]
@yiios 猜测苹果在`10.2`的时候应该是更新了计算`autolayout`布局的算法

**Comment by shareCourage** [comment]
我也是崩溃了，还在找解决方案，大神咋还没修复这个问题呢

**Comment by shareCourage** [comment]
设置 cell 中 label 的 preferredMaxLayoutWidth 属性可以暂时解决这个问题
刚使用这个方法，解决了这个问题

**Comment by weekwood** [comment]
@stone54240 can you provide more error messages?

**Comment by stone54240** [comment]
@weekwood 本来设置了label的preferredMaxLayoutWidth属性，解决了这个问题。刚刚看到你的回复，我去把设置代码去掉了，不过现在已经没有这个崩溃的bug了

**Comment by weekwood** [comment]
@stone54240 Thank your reply. Feel free to upgrade to 1.6.beta. We solved this issue for good.

**Comment by aa335418265** [comment]
10.2  我也是崩溃

**Comment by xilin** [comment]
10.2用1.6在有些时候不加`preferredMaxLayoutWidth `还是会崩溃

**Comment by kennenfromchina** [comment]
这个问题怎么破? 我只有在10.2.1上崩溃
