### ISSUE TITLE
Cell height not adapting according to the view...

### ISSUE THREAD

**Issue by hardikamal** [forkingdog/UITableView-FDTemplateLayoutCell#28]
http://www.androidhive.info/2014/06/android-facebook-like-custom-listview-feed-using-volley/

I am trying to make the view like shown in above link where imageview and contentview of the feed are not of fix size... i have tried your library but dont know if i m missing something..... i m not using autolayout for my app... but using autolayout only for the tableview cell in the xib...is that whats causing the problem??? please help

**Comment by philcn** [comment]
it is very likely that your autolayout constraints are not set up correctly. can u provide us a minimal reproducing project?

**Comment by hardikamal** [comment]
https://github.com/hardikamal/FeedTableViewDemo

**Comment by hardikamal** [comment]
@philcn  any solution???

**Comment by philcn** [comment]
@hardikamal you should configure your cell in the callback of `fd_heightForCellWithIdentifier:configuration:` the same way as you did in `cellForRow:atIndexPath:` .

Here's what your code should look like:

![2015-05-27 3 31 28](https://cloud.githubusercontent.com/assets/2667822/7831060/a640bdcc-0485-11e5-9b59-ef8f8fafddf0.png)
![2015-05-27 3 31 35](https://cloud.githubusercontent.com/assets/2667822/7831063/ab93df8e-0485-11e5-84c8-4fa5769fcf74.png)

and it worked:

![2015-05-27 3 31 17](https://cloud.githubusercontent.com/assets/2667822/7831067/b724e834-0485-11e5-9bd3-4e8c1419384c.png)

**Comment by hardikamal** [comment]
@philcn  and can u please tell me y the image not appearing.... i have been stuck in this since past 4 days :(

**Comment by hardikamal** [comment]
@philcn  are the set constraints right???

**Comment by hardikamal** [comment]
@philcn  its working......Thanks bro
