### ISSUE TITLE
Demo项目出现约束冲突

### ISSUE THREAD

**Issue by 1037390459** [forkingdog/UITableView-FDTemplateLayoutCell#280]
"<NSLayoutConstraint:0x79dba220 UITableViewCellContentView:0x79880af0.width == 280   (active)>",
    "<NSLayoutConstraint:0x798b47b0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x79880af0.width == 286   (active)>"
发现源码添加的约束与系统生成的宽度约束冲突了,[cell.contentView addConstraint:widthFenceConstraint];这里是不是应该设置下优先级?

**Comment by weekwood** [comment]
You can try the temporary solution in #291, the issue fix will come in next release.
