### ISSUE TITLE
出现约束冲突  xib拉的约束

### ISSUE THREAD

**Issue by wfs498121294** [forkingdog/UITableView-FDTemplateLayoutCell#281]
出现约束冲突  xib拉的约束
2017-02-20 11:25:45.899232 gdmobiletv[3416:852997] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x19ca8090 UITableViewCellContentView:0x19e5c420.width == 320>",
    "<NSLayoutConstraint:0x19ea5360 UITableViewCellContentView:0x19e5c420.width == 0>"
)

**Comment by anyuhao** [comment]
同求

**Comment by weekwood** [comment]
You can try the temporary solution in #291, the issue fix will come in next release.
