### ISSUE TITLE
10.3  自适应不行了

### ISSUE THREAD

**Issue by JWXIAN** [forkingdog/UITableView-FDTemplateLayoutCell#289]

**Comment by Er01c** [comment]
@JWXIAN https://github.com/SnapKit/Masonry/issues/426

**Comment by JWXIAN** [comment]
这是自适应失效了？

**Comment by KenmuHuang** [comment]
+1，希望能自适应处理好 10.3 系统下使用 Masonry 约束的高度计算

**Comment by apascual** [comment]
Same problem here...

**Comment by apascual** [comment]
I found the problem...

It looks like for some UILabel, a **preferredMaxLayoutWidth** is configured, mainly when they are created using the Storyboard/NIB file. And the problem is that the value available at the time that the Cell is created is the one it had on the Storyboard...

Setting all the label's **preferredMaxLayoutWidth** to **0** fixed the problem for me, i.e.:

`self.labelnsideCell.preferredMaxLayoutWidth = 0;`

**Comment by apascual** [comment]
Or even better:

`self.labelnsideCell.preferredMaxLayoutWidth = self.frame.size.width;`

**Comment by JWXIAN** [comment]
如果你返回Cell使用了forIndexPath:indexPath，高度返回也必须使用cacheByIndexPath:indexPath，相反。10.3之前没问题。
UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"Cell" forIndexPath:indexPath];

return [tableView fd_heightForCellWithIdentifier:@"Cell" cacheByIndexPath:indexPath configuration:^(UITableViewCell *cell) {
    }];

**Comment by yudun1989** [comment]
https://github.com/yudun1989/UITableView-FDTemplateLayoutCell/commit/e955c2b8cac0dbe1249547c3253d42825af0b4ac

**Comment by tyrad** [comment]
我现在的解决办法是在`awakeFromNib`中计算出label的实际宽度，并赋值给`label.preferredMaxLayoutWidth`(我的cell是用xib写的)

**Comment by faimin** [comment]
归根结底还是得设置`多行label`的`preferredMaxLayoutWidth`属性

**Comment by HomerLi** [comment]
目前 设置 label 的 preferredMaxLayoutWidth 在我的项目中不起作用
我的解决方法是 在 awakeFromNib 中填加如下代码
    [self layoutIfNeeded];
    self.noteLabel.lineBreakMode = NSLineBreakByWordWrapping;

lineBreakMode 枚举中, 选择前三个任意一个, 布局正常.

**Comment by 13hoop** [comment]
10.3
systemLayoutSizeFittingSize自动有width和height约束
导致约束冲突

使用`preferredMaxLayoutWidth `设置时注意

**Comment by hayashi1202** [comment]
纯代码项目中，使用Masonry和FD自适应cell高度，也出现一样的问题，这种情况应该怎么解决呢，每个cell都对应设置一下`preferredMaxLayoutWidth`么

**Comment by FreshAlpha** [comment]
重新约束contentView
self.contentView.mas_remakeConstraints { (m: MASConstraintMaker!) in
            m.edges.equalTo()(self)
        }
并且在cell的xib中更改width为较大值。

**Comment by taogeyijiu** [comment]
楼主看到你的帖子,我赶紧看了一下我的界面,iOS10.3没有发现问题呀,好多人都说设置preferredMaxLayoutWidth, 我也没设置过呀,不知道你的问题出在哪里???

**Comment by yudun1989** [comment]
@taogeyijiu  用nib布局会出问题

**Comment by xiongoahc** [comment]
+1

**Comment by xiongoahc** [comment]
设置多行label的preferredMaxLayoutWidth就好啦

**Comment by afantree** [comment]
结论: 多行label的preferredMaxLayoutWidth的问题

**Comment by xhp281** [comment]
为何我的cell设置还是不行那？

**Comment by zidonJ** [comment]
I resolve this use a estimatedRowHeight and set a value not zero. It is very helpful.

**Comment by pusswzy** [comment]
> I resolve this use a estimatedRowHeight and set a value not zero. It is very helpful.

thank you
