### ISSUE TITLE
iOS 10.3Label高度计算问题

### ISSUE THREAD

**Issue by okayz** [forkingdog/UITableView-FDTemplateLayoutCell#290]
- 10.3 Label高度只会显示一行

**Comment by zhangzhoufeng** [comment]
我也遇到这个问题了  找不到原因哇 做lable展开合上操作

**Comment by faimin** [comment]
`多行label`需要设置`preferredMaxLayoutWidth`

**Comment by okayz** [comment]
@faimin  thanks 解决了

**Comment by yudun1989** [comment]
https://github.com/forkingdog/UITableView-FDTemplateLayoutCell/issues/289

**Comment by zhangzhoufeng** [comment]
[self.contentView layoutIfNeeded]  赋值完使用这个方法 重新刷新一次子view也可以解决 亲测可以

**Comment by leizGit** [comment]
@faimin  如果是自动布局，并不知道Label的宽度怎么设置preferredMaxLayoutWidth？

**Comment by WB326** [comment]
同样遇到了

**Comment by balkarov** [comment]
+

**Comment by KatyChenLu** [comment]
@faimin d=====(￣▽￣*)b厉害了，已经解决啦

**Comment by yrx0910** [comment]
手机升10.3 ，xcode没升没你们怎么测试的呀

**Comment by yrx0910** [comment]
这个库好像都不更新了，还有没有什么好的库呀？

**Comment by yrx0910** [comment]
手机升10.3 ，xcode没升没你们怎么测试的呀？
自从iOS10开始，好像就有写问题，这个库好像都不更新了，还有没有什么好的库呀？

**Comment by xhp281** [comment]
在哪加  		preferredMaxLayoutWidth
 是控件初始化的是么？还是设置约束的时候。

**Comment by afantree** [comment]
@xhp281 一般是在代码里面添加的

**Comment by xhp281** [comment]
@afantree 大哥，你这句话说了跟没说一样啊。

**Comment by afantree** [comment]
@xhp281  😅  如果不动态改变Label宽的话，一般就在 - (void)awakeFromNib 中设置preferredMaxLayoutWidth 。

**Comment by xhp281** [comment]
@afantree哈哈，多谢大哥，我早都弄好了。
