### ISSUE TITLE
10.3下报 约束冲突,所有cell都有这种情况

### ISSUE THREAD

**Issue by anyuhao** [forkingdog/UITableView-FDTemplateLayoutCell#292]
demo 有会出现这种情况

cell. UITableViewCellContentView.width = 0  与
cell. UITableViewCellContentView.width = 375 (对应的最大宽度) MAXWidth 
冲突

** FDTemplateLayoutCell ** layout cell created - FDFeedCell
2017-04-05 15:14:53.986190+0800 Demo[4230:1055755] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x174085eb0 UITableViewCellContentView:0x100422b60.width == 341   (active)>",
    "<NSLayoutConstraint:0x17008f5a0 'UIView-Encapsulated-Layout-Width' UITableViewCellContentView:0x100422b60.width == 0   (active)>"
)

**Comment by anyuhao** [comment]
demo 也会出现这种情况.

**Comment by billding211** [comment]
今天做的时候也发现这个情况,希望大大看一看.....

**Comment by KenmuHuang** [comment]
+1；iOS 10.3 默认会添加对应的宽度约束，从而导致了约束冲突。希望能针对系统版本进行去掉默认约束处理来解决此问题

**Comment by BetrayalPromise** [comment]
+1约束冲突看着真揪心

**Comment by leejtom** [comment]
看来不是我一个人遇到了。QAQ

**Comment by kanting** [comment]
所以解决方法是？

**Comment by Jetsond** [comment]
解决方法呢

**Comment by JiangWenjia** [comment]
同样的问题。。。

**Comment by nanmingzhidian** [comment]
同样的问题

**Comment by taylor-young** [comment]
同样的问题

**Comment by MrLJnull** [comment]
一开始还以为是masonry问题，后来发现是这个。

**Comment by HY-Vae** [comment]
@ @KenmuHuang 针对系统版本进行去掉默认约束怎么去掉？

**Comment by weekwood** [comment]
Same as #291
