### ISSUE TITLE
- (CGFloat)fd_heightForCellWithIdentifier:(NSString *)identifier configuration:(void (^)(id cell))configuration计算出的高度不正确  系统是10.2

### ISSUE THREAD

**Issue by yxg1360634255** [forkingdog/UITableView-FDTemplateLayoutCell#294]

**Comment by JeffLJ** [comment]
你使用masonry布局吗?如果你按着以前的写法出错了,你需要在关键这行代码里面make.bottom.equalTo(self.bottomLine).priority(999);加上.priority(999); 加上一个优先级.

**Comment by yxg1360634255** [comment]
是的  我试试看 thank you

**Comment by yxg1360634255** [comment]
试过了  不行的

**Comment by yxg1360634255** [comment]
第一次刷新数据  计算出的高度正确  再刷新一次  高度就错了   ，然后再次刷新 高度正确 ，继续刷 又错了。。。。。。。。也就是奇次刷新高度正确  偶次刷新，高度就是错的

**Comment by AlianOL** [comment]
我遇到的类似的问题，我的是前几次计算的正确（就是第一次走回调的时候，那次的高度正确），但是第二次走回调函数的时候，那次的高度就出错了，我没有用masnory，我用xib设置的约束，并且只有在5 5s上高度计算的没问题。。在se 6 6p上面就出错，只计算了一行

**Comment by yxg1360634255** [comment]
不一定是半边 。试过了，在ios9没问题的

**Comment by weekwood** [comment]
@yxg1360634255, please try to update to 1.6.beta see if it works, sorry for the inconvenience.
