### ISSUE TITLE
解决10.3 系统label不能自适应

### ISSUE THREAD

**Issue by zhongab** [forkingdog/UITableView-FDTemplateLayoutCell#295]
![8308ddbf-e56b-4bdc-b64b-cf3bd58e9a3f](https://cloud.githubusercontent.com/assets/7332300/24945181/d25e6f1c-1f90-11e7-9ef5-f40b8d080c57.png)

**Comment by faimin** [comment]
添加这个约束的目的只是用来计算高度的，高度计算完毕之后需要把添加的约束移除，就像作者的做法一样。

**Comment by zhongab** [comment]
@faimin  你是怎么做的呢，我发现还是有问题

**Comment by faimin** [comment]
@zhongab 我还是老老实实的给 **多行`label`** 设置`preferredMaxLayoutWidth`属性值，官方文档就这么要求的

**Comment by shanglina** [comment]
对于有2个或以上的多行label时 , 设置这个preferredMaxLayoutWidth 加上[cell.contentView mas_makeConstraints:^(MASConstraintMaker *make) {
make.left.mas_equalTo(0).priorityLow();
make.right.mas_equalTo(0).priorityLow();
}]; 可以解决

**Comment by weekwood** [comment]
Same as #291.
