### ISSUE TITLE
使用rac_prepareForReuseSignal会有点小问题

### ISSUE THREAD

**Issue by hongdong** [forkingdog/UITableView-FDTemplateLayoutCell#297]
在awakeFromNib中监听并takeUtil rac_prepareForReuseSignal的话，tempCell会发射rac_prepareForReuseSignal，直接给解除监听了，求解？

**Comment by weekwood** [comment]
@hongdong can you upload a demo project?

**Comment by hongdong** [comment]
sorry,后来我想了想，由于复用并不会重新调用awakeFromNib，所以在awakeFromNib中监听并takeUtil rac_prepareForReuseSignal不是太好的用法。
