### ISSUE TITLE
约束问题，但是直接返回高度不会报错

### ISSUE THREAD

**Issue by yaoguanglin** [forkingdog/UITableView-FDTemplateLayoutCell#298]
Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60800028cfd0 UITableViewCellContentView:0x7fe2f4dc1f40.width == 414>",
    "<NSLayoutConstraint:0x60800028fd70 UITableViewCellContentView:0x7fe2f4dc1f40.width == 0>"
)

**Comment by longjianjiang** [comment]
麻烦具体描述下问题，通过分类提供的方法计算的高度是否符合预期？

**Comment by weekwood** [comment]
@yaoguanglin Please try to upgrade to 1.6.beta see if issue fixed

**Comment by weekwood** [comment]
I am closing this for now, let me know if still bugging u
