### ISSUE TITLE
EXC_BREAKPOINT 在viewDidLoad中刷新tableView如果cell是使用xib方式加载的，fd计算高度会出现访问僵尸对象的问题

### ISSUE THREAD

**Issue by JiangWenjia** [forkingdog/UITableView-FDTemplateLayoutCell#299]
在viewDidLoad数据直接从缓存加载，立即刷新tableView，然后fd计算高度时候，会使用cell里的控件，但是测试空间里的view还没加载完毕。 解决办法是我做了延迟。。。。。但是我觉得这个方式太奇怪了，看看能不能再fd直接解决。。有没有和我遇到同样问题的

**Comment by weekwood** [comment]
@JiangWenjia Hard to understand what's the issue. Can you explain or upload a demo?

**Comment by JiangWenjia** [comment]
@weekwood  很感谢，能回复我。。。嗯，问题已经找到了，那个cell xib设置的问题，已经解决了。tanks

**Comment by weekwood** [comment]
@JiangWenjia 😄
