### ISSUE TITLE
高度计算不正确

### ISSUE THREAD

**Issue by py3613778** [forkingdog/UITableView-FDTemplateLayoutCell#308]
现在用刚下载下来的demo，用iOS10.3 xcode8.3.1的 iPhone5、iphone5S模拟器运行，高度都不正确

**Comment by weekwood** [comment]
@py3613778 would you mind send me logs and show me your xcode interface?

**Comment by caizetong** [comment]
用来计算高度的cell的frame似乎有问题，目前我把contentViewWidth赋值给cell的width计算的高度就对了。

**Comment by py3613778** [comment]
用frame布局就好了，用xib布局会出现这个问题，应该是xibd的canvas device view固定了
