### ISSUE TITLE
reason: 'Cell must be registered to table view for identifier - JHBoss_StaffEvaluateTableViewCell'

### ISSUE THREAD

**Issue by LJJHD** [forkingdog/UITableView-FDTemplateLayoutCell#309]
[_tableView registerNib:[UINib nibWithNibName:@"JHBoss_StaffEvaluateTableViewCell" bundle:nil] forCellReuseIdentifier:@"JHBoss_StaffEvaluateTableViewCell"];

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath{
    return  [tableView fd_heightForCellWithIdentifier:@"JHBoss_StaffEvaluateTableViewCell" cacheByIndexPath:indexPath configuration:^(JHBoss_StaffEvaluateTableViewCell * cell) {
        
        [self configuration:cell indexPath:indexPath];
    }];
}

为什么注册过了，还是报 reason: 'Cell must be registered to table view for identifier - JHBoss_StaffEvaluateTableViewCell'这个错误

**Comment by weekwood** [comment]
check comments on #119
