### ISSUE TITLE
同一个Cell内两个动态高度Label会导致其中一个计算不正确

### ISSUE THREAD

**Issue by shicang1990** [forkingdog/UITableView-FDTemplateLayoutCell#32]
同一个Cell会用到某两个Label需要动态高度，经过测试一般都是第二个Label高度会不对，是我约束设置的不对吗？如果是上述情况，需要动态高度的Label需要怎么设置高度呢？
目前解决方法只能：
 [cell updateConstraintsIfNeeded];
 [cell layoutIfNeeded];

**Comment by sunnyxx** [comment]
可能是约束连的有些问题，我测试是ok的，要注意这两个 label 的上下左右都要有直接或间接的和父的约束。

**Comment by shicang1990** [comment]
找到问题了，我的cell重载过setFrame，改变了cell宽高，然后搞了个父类调用updateConstraintsIfNeeded和layoutIfNeeded再返回的高度+10，调用cell缓存方法返回高度的时候忘了+10

**Comment by sunnyxx** [comment]
恩恩，那我close了
