### ISSUE TITLE
Xcode 8.3 iOS10.3 cell高度计算不正确并且有log

### ISSUE THREAD

**Issue by Karthus1110** [forkingdog/UITableView-FDTemplateLayoutCell#328]
约束都已设置齐全但高度比实际高度高
<img width="353" alt="qq20170615-114738 2x" src="https://user-images.githubusercontent.com/13864988/27164522-75a8e312-51c0-11e7-80ba-5c9bdfd7570f.png">

**Comment by lsllsllsl** [comment]
我的是一直报 跟cell 自带的高度44 冲突，我的是自动算高的
<img width="682" alt="screen shot 2017-06-16 at 9 31 06 am" src="https://user-images.githubusercontent.com/20367199/27208211-f51eb9d0-5276-11e7-94ae-90450c1aba88.png">
