### ISSUE TITLE
Is surport ios6?

### ISSUE THREAD

**Issue by wy19901227** [forkingdog/UITableView-FDTemplateLayoutCell#33]
I has tested it on iOS 6, It can not calculate the rowHeight correctly, but I have read your blog. You said it can surpot ios6,I have delete "self.tableView.estimatedRowHeight = 200;”

**Comment by sunnyxx** [comment]
Yes and If you have multiple lines labels, `preferredMaxLayoutWidth` should be set in iOS6.
