### ISSUE TITLE
用xib 创建cell，然后自动布局，为什么提示说我没用自动布局，不能这样使用吗？

### ISSUE THREAD

**Issue by wy19901227** [forkingdog/UITableView-FDTemplateLayoutCell#35]
如题

**Comment by sunnyxx** [comment]
cell 的 content view 里面要起码有一条约束，不能空着。

**Comment by wy19901227** [comment]
我设置了  好多呢

**Comment by wy19901227** [comment]
![d28ac65c-c090-4920-a311-215bd614334e](https://cloud.githubusercontent.com/assets/8086633/7858116/4fa046ca-0568-11e5-94a2-0e3944c6f43f.png)

**Comment by wy19901227** [comment]
我是直接 建了一个cell的xib文件，然后 添加的 约束

**Comment by sunnyxx** [comment]
请帮忙debug一下或者把demo工程发给我

**Comment by wxfstwxf** [comment]
我也遇到过类似的问题，我的解决办法是把 - (void)registerClass:(Class)cellClass forCellReuseIdentifier:(NSString *)identifier 改为用 - (void)registerNib:(UINib *)nib forCellReuseIdentifier:(NSString *)identifier。
给你参考下，不知道你是不是也是这个原因。

**Comment by wy19901227** [comment]
是得 ，- (void)registerClass:(Class)cellClass forCellReuseIdentifier:(NSString *)identifier 改为用 - (void)registerNib:(UINib *)nib forCellReuseIdentifier:(NSString *)identifier

这样不报错了，但是我的约束 不起作用。
