### ISSUE TITLE
How to call it in swift?

### ISSUE THREAD

**Issue by ringfox** [forkingdog/UITableView-FDTemplateLayoutCell#36]
tableView.fd_heightForCellWithIdentifier("cellId", configuration: { (cell:UITableviewCell) -> Void in
self.configureCell(cell, atIndexPath: indexPath)
})

does not work

**Comment by sunnyxx** [comment]
I'm sorry, it doesn't support swift for now. Maybe in a future version?

**Comment by lucasleelz** [comment]
原来是还不支持~ 我搞了半天，发现没有效果。 请问什么时候能够支持？
