### ISSUE TITLE
xib下给cell中的imageView加入TapGesture后出现crash的问题

### ISSUE THREAD

**Issue by Vienta** [forkingdog/UITableView-FDTemplateLayoutCell#38]
Hi,
感谢作者的辛勤劳动，这两天在用感觉比较方便，但遇到些问题
cell中的imageView加上TapGesture之后会crash，
是否对tableView.headerView是不是默认也进行了自动布局？

**Comment by sunnyxx** [comment]
你说的crash可不可以帮忙debug下，或者把错误堆栈发出来。这个只有cell布局headerView没碰
