### ISSUE TITLE
新手请教下关于xib使用

### ISSUE THREAD

**Issue by realchen** [forkingdog/UITableView-FDTemplateLayoutCell#398]
设计图和xib如下
![b8cdc88d-a950-4e53-a843-426128e7aea2](https://user-images.githubusercontent.com/5886378/53937610-92bd9880-40e8-11e9-97bd-8c298f57f023.png)
![f699a3cf-0d86-410c-b2bb-abd485be8e2e](https://user-images.githubusercontent.com/5886378/53937615-94875c00-40e8-11e9-8a98-0ffad23179fd.png)

我的理解使用自适应框架,那么cell的高度和cell里面每一部分的高度都不能设死,所以我里面分了3部分和2条分割线

第一部分,设置的是 top left right 都是0于superview
然后里面的label设置了top和bottom 来确定高度

第二部分同样
现在问题是 到最好设置分割线的时候,设置left right和top后,不能设置bottom
如果设置bottom于superview为0xib会报错,但是可以正常运行,如果我前面第一个或者第二个文字过多,下面2个item动态获取的label显示不出来

刚接触ios 希望可以得到解答

**Comment by cddjr** [comment]
bottom的约束优先级设为999即可忽略警告。 毕竟cell的高度是随内容动态调整的，IB中我们只是随手画了cell，高度不一定满足约束。
