### ISSUE TITLE
How to use without storyboard?

### ISSUE THREAD

**Issue by sahil263** [forkingdog/UITableView-FDTemplateLayoutCell#41]
I am using xibs in my project. I followed your guidelines. But, still I am not able to make it work with xib.

Please provide the details, for how to add it with xib.

**Comment by sunnyxx** [comment]
Could you post a snapshot of your constraints in xib?  The cell doesn't self-satisfied most likely.

**Comment by sahil263** [comment]
@sunnyxx Here are the snapshots or the cell xib (with auto layout contains)

![screen shot 2015-06-05 at 9 00 16 pm](https://cloud.githubusercontent.com/assets/4958184/8009415/5117d482-0bc6-11e5-9c9c-d2a183a2991e.png)
![screen shot 2015-06-05 at 9 00 55 pm](https://cloud.githubusercontent.com/assets/4958184/8009417/513e5760-0bc6-11e5-968e-aee494cab37c.png)
![screen shot 2015-06-05 at 9 00 46 pm](https://cloud.githubusercontent.com/assets/4958184/8009414/511610ca-0bc6-11e5-91f7-7cefb5751c1a.png)
![screen shot 2015-06-05 at 9 01 03 pm](https://cloud.githubusercontent.com/assets/4958184/8009418/513f70e6-0bc6-11e5-944b-0f01bb13a43a.png)
![screen shot 2015-06-05 at 8 59 33 pm](https://cloud.githubusercontent.com/assets/4958184/8009416/512f1638-0bc6-11e5-911e-0bb3ed3033c3.png)
![screen shot 2015-06-05 at 9 00 27 pm](https://cloud.githubusercontent.com/assets/4958184/8009420/51ab1cb0-0bc6-11e5-9aa7-2302518dc301.png)

**Comment by sunnyxx** [comment]
Actually, there's no constraint against content view, as **README** said, you must have top, left, bottom, right for at least 1 constraint against content view, which looks like:  
![Correct constraints](https://cloud.githubusercontent.com/assets/2410234/8017165/be69a302-0c21-11e5-9179-160b74ca14d3.png)

**Comment by sahil263** [comment]
Now I have added constrains to content view. But, still the cell are returned empty.

![screen shot 2015-06-06 at 5 41 45 am](https://cloud.githubusercontent.com/assets/4958184/8017261/d563c668-0c0e-11e5-9921-560eb90362a1.png)


When I run it on device:

![c6f3057c92e376eaa4b57b520496fb8ba15dde90f7ecb2d77fpimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/4958184/8017279/43b30a48-0c0f-11e5-88a7-b336415f298b.jpg)

**Comment by sunnyxx** [comment]
Would you try it in a minimal demo? If still not work, post it into a repo and I'll check it out for you, I think there's still something wrong with your constraints or how to use this tool, xib works in my demo.

**Comment by sahil263** [comment]
Sure, I do test it in a minimal demo and let you know.

**Comment by sahil263** [comment]
@sunnyxx I have prepared a demo project (with xib, please check under my repo).

Earlier the screen short I posted above `UITableViewCellAccessoryDisclosureIndicator` and `UITableViewCellAccessoryCheckmark` accessoryTypes ver being displayed.

Now they are also not being displayed.

Please let me know, once you check the code.
Thanks!

**Comment by sunnyxx** [comment]
There're terrible several things you didn't get fully understood.  
First, In your **HomeVC**, cells in xib are not registered by "-registerClass:forCellReuseIdentifier:", it should be:  
``` objc 
 [self.homeTableViewOutlet registerNib:[UINib nibWithNibName:@"HomeCell" bundle:nil] forCellReuseIdentifier:@"FDFeedCell"];
```
Then cells appear, but quite weird:  
![2015-06-06 7 38 13](https://cloud.githubusercontent.com/assets/2410234/8019487/a44432aa-0c83-11e5-9f51-af9267c12aa6.png)

It's an obvious reason that you didn't adapt screen resolution by assigning a **Launch Screen File** in your project setting:  
![2015-06-06 7 41 07](https://cloud.githubusercontent.com/assets/2410234/8019495/196fb70c-0c84-11e5-8c62-5dbbc90e188c.png)

Then it still looks weird:  
![2015-06-06 7 42 14](https://cloud.githubusercontent.com/assets/2410234/8019498/377c23fc-0c84-11e5-904b-fcdf99101808.png)

I figure it out that you even forgot to set table view's layout constraints in your **HomeVC.xib**:  
![2015-06-06 7 44 03](https://cloud.githubusercontent.com/assets/2410234/8019501/727c16ce-0c84-11e5-9d95-9d534d8c5364.png)  

It should be:  

![2015-06-06 7 44 16](https://cloud.githubusercontent.com/assets/2410234/8019502/727e57ea-0c84-11e5-99c1-f1b584076c48.png)

After all those corrections, cells are finally controlled by what you've set in xib file.  

![2015-06-06 7 46 17](https://cloud.githubusercontent.com/assets/2410234/8019516/58cc67f0-0c85-11e5-874c-eb8bea9ca306.png)

You must be more careful and try to review some Interface Builder's usages.

**Comment by sahil263** [comment]
@sunnyxx Yes, I see the mistakes which I made. It's working now...
Thanks a lot, for your help. I appreciate your effort. Thanks once again!
