### ISSUE TITLE
微信朋友圈布局autolayout

### ISSUE THREAD

**Issue by BestKai** [forkingdog/UITableView-FDTemplateLayoutCell#42]
我想问下，就是类似微信朋友圈的那种布局，九张图片如果使用autolayout怎么添加约束，我现在是用一个View来做这几张图片的背景，但是用添加约束之后，使用autolayout，高度并没有发生改变。

**Comment by sinzang** [comment]
1、使用UICollectionView做图片展示
2、不要将UICollectionView的delegate放在cell里面
3、请参考http://ashfurrow.com/blog/putting-a-uicollectionview-in-a-uitableviewcell/，并结合这个来做高度自适应

**Comment by cloudPig** [comment]
好的，我试试，非常感谢

**Comment by atbj505** [comment]
我试着加入了UICollectionView用于显示多张图片，也给UICollectionView加了约束，但是展示的时候UICollectionView告诉变成了0，是我的约束加的不对吗？
![Uploading iOS Simulator Screen Shot 2015年7月12日 下午6.01.22.png…]()

**Comment by atbj505** [comment]
我试着加入了UICollectionView用于显示多张图片，也给UICollectionView加了约束，但是展示的时候UICollectionView告诉变成了0，是我的约束加的不对吗？
![ios simulator screen shot 2015 7 12 6 01 22](https://cloud.githubusercontent.com/assets/8262619/8637363/86115d18-28c0-11e5-905a-b43787f485cf.png)

**Comment by xilin** [comment]
@atbj505 我也遇到了这个问题，在`UITableViewCell`里添加的`UICollectionView`高度恒为0

**Comment by sunnyxx** [comment]
内嵌的 collection view 需要设置高度约束来撑开自己（因为 collection view 没有固有），在设置数据之后，调用 UICollectionViewLayout 的 `-collectionViewContentSize` 可以获取到计算后的高度，再把高度值设置到高约束上。

**Comment by AaronZhang2015** [comment]
如何知道CollectionView的高度已经计算完毕呢？
