### ISSUE TITLE
动态size图片有时候高度不正确，而且一旦出现不正确的，就会连带出现很多

### ISSUE THREAD

**Issue by AugustRush** [forkingdog/UITableView-FDTemplateLayoutCell#44]
![img_0453](https://cloud.githubusercontent.com/assets/6881916/8105094/9f25d600-1068-11e5-9aa8-df449b66a264.PNG)

**Comment by sunnyxx** [comment]
应该是数据源和高度的缓存不一致导致的，得查下是不是动态改了数据源但没有刷新 table view

**Comment by AugustRush** [comment]
就是正常的加载历史数据，reloadData

发自我的 iPhone

**Comment by sunnyxx** [comment]
see #84 , Thanks
