### ISSUE TITLE
ios8以上的系统cell.contentView.constraints 是个空数组

### ISSUE THREAD

**Issue by zhaofucheng1129** [forkingdog/UITableView-FDTemplateLayoutCell#45]
使用Xib布局 registerNib:forCellReuseIdentifier:注册了Cell 
计算高度时 
BOOL autoLayoutEnabled = cell.contentView.constraints.count > 0 && !cell.fd_enforceFrameLayout; 
这句中的cell.contentView.constraints 是个空数组 但是我用了AutoLayout了

**Comment by zhaofucheng1129** [comment]
找到问题了 BOOL autoLayoutEnabled = cell.contentView.constraints.count > 0 && !cell.fd_enforceFrameLayout; 这句中的cell.contentView.constraints 是个空数组 但是我用了AutoLayout了

**Comment by qchenqizhi** [comment]
都有代码了，直接改吧，现在这里是2选1，这个判断确实有点多余
```objective-c
BOOL autoLayoutEnabled = /*cell.contentView.constraints.count > 0 && */!cell.fd_enforceFrameLayout;
```

**Comment by adin283** [comment]
我用purelayout来布局的cell，cell.contentView.constraints.count也是0

**Comment by adin283** [comment]
在configuration block里面强制来更新约束解决了这个问题：
```
[cell setNeedsUpdateConstraints];
[cell updateConstraintsIfNeeded];
```

**Comment by zhaofucheng1129** [comment]
我后来使用Masonry 纯代码方式布局了 用- (CGSize)sizeThatFits:(CGSize)size 反算高度了 autolayout 做复杂界面 还是有点力不从心

**Comment by HanYaZhou1990** [comment]
通过- (CGSize)sizeThatFits:(CGSize)size 反算高度，如果有加载网络图片，你的不会出现问题吗？

**Comment by zhaofucheng1129** [comment]
我的网络加载图片是固定了宽度高度的 没有根据图片高度调整Cell高度 所以没问题

**Comment by sunnyxx** [comment]
Fixed in new version
