### ISSUE TITLE
在＋load方法中实现swizzle是不是应该加上dispatch_once？

### ISSUE THREAD

**Issue by nickqiao** [forkingdog/UITableView-FDTemplateLayoutCell#58]
static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
       //swizzle代码
    });

**Comment by Gottabe** [comment]
对的没错，可以说必须在dispatch_once里面做，swizzle一般用来改变全局状态，安全起见要确保其原子性

**Comment by sunnyxx** [comment]
恩，下个版本会加上，但个人对 swizzle UI 类的 +load 是否有多线程问题表示怀疑。
