### ISSUE TITLE
请教一个问题，如何移除某行的高度缓存，例如我需要动态插入一条评论..或一个固定大小的UIView

### ISSUE THREAD

**Issue by mrkey0310** [forkingdog/UITableView-FDTemplateLayoutCell#59]
如题：
<img width="796" alt="2015-07-13 6 00 41" src="https://cloud.githubusercontent.com/assets/2264869/8647274/1d253828-2989-11e5-8de5-d3fc9c36d7e6.png"> 通过以上方法返回cell的高度，在第一次回调时，我隐藏里面某个view是高度是正常的，但当我在运行过程中，动态修改内容后，调用reloadData 刷新列表，但会在滚动时出现一些奇怪的bug，cell一卡一卡的。

**Comment by sunnyxx** [comment]
要是高度计算不正确，需要考虑重用时是否在 `-prepareForReuse`已经把动态修改的部分等效的移除；若是卡顿，可能是因为 `-reloadData` 把所有的缓存都清除了，进行了全量计算。See #66
