### ISSUE TITLE
已经集成到项目中，简单易用，快速上手，赞一个

### ISSUE THREAD

**Issue by songxing10000** [forkingdog/UITableView-FDTemplateLayoutCell#60]

**Comment by LanceBinbin** [comment]
w我想问一下 你在 加载 网络图片的时候 也是正常 的嘛 ？

**Comment by songxing10000** [comment]
这个框架只是自动计算行高，至于你加载图片有问题，那就是另外的问题了

**Comment by LanceBinbin** [comment]
不是得了 你只个好高用本地图片 是没问题的  但是因为是加载网络图片 所以会慢  也就是说 图片还没加载下来 你就已经计算过高度了 默认 没有加载完成的图片 为 没有图片来计算行高  当手动刷新一下 tableView的时候 这时候 因为图片已经加载完成  所以 又会重新 计算一下cell的高度 把 图片显示出来 所以如何等图片加载完成之后 再去计算高度呢？

**Comment by yyhui** [comment]
如果SDWebImage，有个block方法，在里边完成image的设置不行吗？

Send from my vivo

HaibinGong <notifications@github.com> wrote:

不是得了 你只个好高用本地图片 是没问题的  但是因为是加载网络图片 所以会慢  也就是说 图片还没加载下来 你就已经计算过高度了 默认 没有加载完成的图片 为 没有图片来计算行高  当手动刷新一下 tableView的时候 这时候 因为图片已经加载完成  所以 又会重新 计算一下cell的高度 把 图片显示出来 所以如何等图片加载完成之后 再去计算高度呢？

---

**Comment by LanceBinbin** [comment]
如何  tell me  求解答  解答 Demo 可以 发我  邮箱  Lance901221@163.com  谢了

**Comment by sunnyxx** [comment]
See #84
