### ISSUE TITLE
用Masonry如何设置？？？

### ISSUE THREAD

**Issue by zdrzdr** [forkingdog/UITableView-FDTemplateLayoutCell#62]

**Comment by zdrzdr** [comment]
模拟器不没有打印出警告，真机打印了很多了警告 Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
.....

**Comment by zdrzdr** [comment]
是6p就有打印,其他没有

**Comment by zdrzdr** [comment]
[self.contentView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.height.equalTo(117);
        make.width.equalTo([UIScreen mainScreen].bounds.size.width);
    }];
加了这个就不打印了？？？

**Comment by sunnyxx** [comment]
计算时若约束设置正确是肯定可以正确计算的，请检查下 Masonry 约束设置的时机和是否约束正确，Masonry 如何写的问题就不在这儿讨论了。
