### ISSUE TITLE
手离开cell,cell滑动至停止过程中有严重的卡顿现象！！！

### ISSUE THREAD

**Issue by zdrzdr** [forkingdog/UITableView-FDTemplateLayoutCell#63]

**Comment by 651893553** [comment]
你好，你的卡顿问题解决了么？

**Comment by MrReN** [comment]
卡

**Comment by alienjun** [comment]
卡

**Comment by sunnyxx** [comment]
这应该是 iOS8 下面一个原生现象，可以试试不使用这个高度计算工具时是否也卡。若是上拉加载更多卡，请把 `- reloadData` 改成 `- insertRowsAtIndexPaths:`，因为 reload 会把所有高度缓存删除重新计算，导致瞬时的卡顿。
