### ISSUE TITLE
tableview显示多种变高cell时，reload或者insert后，首次下滑会有卡顿现象

### ISSUE THREAD

**Issue by 651893553** [forkingdog/UITableView-FDTemplateLayoutCell#66]
tableview显示多种变高cell时，reload或者insert后，首次下滑会有卡顿现象，滑动上面后再滑动时卡顿现象消失，但是再次下拉加载更多的时候这种状况会继续出现，猜测是insert或reload后之前的缓存失效了，烦请帮忙给个解决方案！

**Comment by sunnyxx** [comment]
reload 之后将会把缓存失效，如果确定是加载更多，可以使用 insert 方法加载后面的数据源。1.4 提供了一个不清除缓存的 reload 方法：
``` objc
[self.tableView fd_reloadDataWithoutInvalidateIndexPathHeightCache];
```
当然，也可以使用 1.4 版本出的 `cacheByKey` 模式，就不用担心这些了。
