### ISSUE TITLE
在缓存高度的情况下删除一个cell，cell的高度就会出错

### ISSUE THREAD

**Issue by 643824979** [forkingdog/UITableView-FDTemplateLayoutCell#68]
self.cellHeightCacheEnabled = YES

NSMutableArray *mutableEntities = self.feedEntitySections[indexPath.section];
        [mutableEntities removeObjectAtIndex:indexPath.row];
        [self.tableView deleteRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationAutomatic];

就会发现其他的cell高度出错

**Comment by sunnyxx** [comment]
Fixed in 1.4
