### ISSUE TITLE
缓存cell高度那个方法一调用就直接说我没有注册cell的reuseIdentifier?实际上我在cell 的类方法里注册了的呀?

### ISSUE THREAD

**Issue by cxGoGoing** [forkingdog/UITableView-FDTemplateLayoutCell#69]
return [tableView fd_heightForCellWithIdentifier:@"HomeRecommendCell" cacheByIndexPath:indexPath configuration:^(HomeRecommendCell* cell) {
        [cell configWithGoodsInfo:_goodsInfoArray[indexPath.row]];
    }];

+ (instancetype)homeRecommendCellWith:(UITableView*)tableView indexPath:(NSIndexPath*)indexPath
{
    UINib * nib = [UINib nibWithNibName:NSStringFromClass([self class]) bundle:nil];
    
    [tableView registerNib:nib forCellReuseIdentifier:NSStringFromClass([self class])];
    
    HomeRecommendCell * cell = [tableView dequeueReusableCellWithIdentifier:NSStringFromClass([self class]) forIndexPath:indexPath];
    
    return cell;
}

**Comment by lishuanghenu** [comment]
viewdidload中注册 你试试行不行

**Comment by HanYaZhou1990** [comment]
不行，我试过了，这个类必须继承UITableViewController才能用，如果继承自UIViewController，直接就crash，目前这个问题，我还不知道怎么解决

**Comment by Coder-XL** [comment]
哥们不要给我发了，我也不知道




------------------ 原始邮件 ------------------
发件人: "韩亚周";<notifications@github.com>;
发送时间: 2015年8月24日(星期一) 晚上6:20
收件人: "forkingdog/UITableView-FDTemplateLayoutCell"<UITableView-FDTemplateLayoutCell@noreply.github.com>; 

主题: Re: [UITableView-FDTemplateLayoutCell] 缓存cell高度那个方法一调用就直接说我没有注册cell的reuseIdentifier?实际上我在cell 的类方法里注册了的呀? (#69)




不行，我试过了，这个类必须继承UITableViewController才能用，如果继承自UIViewController，直接就crash，目前这个问题，我还不知道怎么解决

**Comment by HanYaZhou1990** [comment]
在创建tableView以后，立即注册就没问题了

**Comment by cxGoGoing** [comment]
到用的时候注册不行么?在cell中完成注册不是也就是tableView创建之后么?

**Comment by HanYaZhou1990** [comment]
那个时候就太晚了，会闪退

发自我的 iPhone

**Comment by sunnyxx** [comment]
在尽量早的时候注册，很多操作都会引发 table view 提前询问数据源。

**Comment by CoderNevinZ** [comment]
终于找到了答案
