### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by luyinuo** [forkingdog/UITableView-FDTemplateLayoutCell#70]
1.文章中说，使用前需要先注册cell,但是在demo中并没有注册相关的cell.
2.tableview滚动的时候在allocation中跟踪，确实看到内存一直保持在18M左右，缓存高度很给力，但是在滑动的过程中还是有肉眼能够识别的抖动感，让人还是很不适，不知道是不是estimatedRowHeight的原因。
还望大神给个回答呀，小弟不胜感谢

**Comment by lixiya1990** [comment]
@luyinuo 问题解决了吗 我也遇到这个问题  是加载网络图片时 demo里用的是本地的

**Comment by HanYaZhou1990** [comment]
我加载网络图片也有问题，你们都解决了吗

**Comment by LanceBinbin** [comment]
怎么解决  加载网络图片时  不能像 Demo 里面加载本地图片的 那种效果 完全没事实现动态的cell 高度 你们解决了吗？

**Comment by sunnyxx** [comment]
See #84

**Comment by sunnyxx** [comment]
另外，estimatedRowHeight 设置的不准确会引起 content size 的跳动；iOS 8 之后的 table view 就算高度固定滑到最后也会丢帧，iOS 9 好像更严重，这个就没啥办法了。
