### ISSUE TITLE
how to deal with table view header?

### ISSUE THREAD

**Issue by caofei10119** [forkingdog/UITableView-FDTemplateLayoutCell#71]
I added these two methods

- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section
- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section

heightForHeadersInSection method keeps getting called.
How to deal with it?

**Comment by sunnyxx** [comment]
Maybe support in next release, Thanks
