### ISSUE TITLE
图片加载延迟导致错乱的问题

### ISSUE THREAD

**Issue by wangzhenyujiang** [forkingdog/UITableView-FDTemplateLayoutCell#72]
这个库很灰常好用炒鸡赞，从 Star 的数目就看出来了。使用的时候遇到了点小问题：

问题：

我的 Cell 加载图片后出现了图片被压缩成一小条的情况，图片的 Size 严重改变。我拿着自己的项目和阳神的 Demo 每一行代码每一个设置对比，基本一样，代码和设置没有问题。但是阳神的 Demo 就炒鸡好看而我的 Cell 中的 ImgaeView 却被严重压缩变形。

原因：

这个原因还是找了一通的，和这个库的 Cell 高度计算以及控件高度计算机制有关。具体原因是： 我用第三方的图片缓存库 Kingfisher 来加载的图片，当第一次设置图片的时候，因为图片还没有下载下来，就会给 ImgaeView 设置一个 placeholderImage 来提高用户体验，问题就是出在 placeholderImage 上面。当设置 placeholderImage 的时候，可能这个 Cell 中 ImageView 的高度就被计算出来并定死了，意味着图片下载完并设置完成后这个 ImageView 的大小也不会改变。所以，当要设置图片的 Size 和 placeholderImage 的 Size 不一样的时候，就会导致图片被压缩。而阳神的 Demo 是本地读数据的，所以他的图片是一次性直接赋值上去的。

菜逼的解决办法：

项目是自己独立开着玩的，所以菜逼暂时的解决方案是上传图片的时候加一个 Size 字段，当加载 image 的时候先把 Size 拿到并用这个 Size 来生成一个 UIImage 先占着，这样就暂时解决了问题。

**Comment by HanYaZhou1990** [comment]
我用的sd_webimage，有placehodlerimage，第一次图片就那样，但是再加载的时候，图片被缓存在本地了，就直接取本地缓存的图片了，造成image变的非常高，实际imageView很低，图片以下的控件就全乱了

**Comment by sunnyxx** [comment]
See #84 , Thanks
