### ISSUE TITLE
 请教一个问题，runloop怎么被不断唤醒呢，一次runloop周期运行完后处于休眠状态，怎么不断唤醒去执行预缓存高度任务呢

### ISSUE THREAD

**Issue by yunyu2014** [forkingdog/UITableView-FDTemplateLayoutCell#73]
若当前有20个cell的高度要预缓存，则接下来的20个runloop迭代中会依次分发这些任务，runloop会被不断地唤醒，直到任务全部完成。 请教一个问题，runloop怎么被不断唤醒呢，一次runloop周期运行完后处于休眠状态，怎么不断唤醒去执行预缓存高度任务呢

**Comment by wangzhenyujiang** [comment]
performSelector 方法

**Comment by yunyu2014** [comment]
CFRunLoopObserverRef observer = CFRunLoopObserverCreateWithHandler
    (kCFAllocatorDefault, kCFRunLoopBeforeWaiting, true, 0, ^(CFRunLoopObserverRef observer, CFRunLoopActivity _) {
        // Remove observer when all precache tasks are done.
        if (mutableIndexPathsToBePrecached.count == 0) {
            CFRunLoopRemoveObserver(runLoop, observer, runLoopMode);
            CFRelease(observer);
            return;
        }
        // Pop first index path record as this RunLoop iteration's task.
        NSIndexPath *indexPath = mutableIndexPathsToBePrecached.firstObject;
        [mutableIndexPathsToBePrecached removeObject:indexPath];
        
        // This method creates a "source 0" task in "idle" mode of RunLoop, and will be
        // performed in a future RunLoop iteration only when user is not scrolling.
        [self performSelector:@selector(fd_precacheIndexPathIfNeeded:)
                     onThread:[NSThread mainThread]
                   withObject:indexPath
                waitUntilDone:NO
                        modes:@[NSDefaultRunLoopMode]];
    });

你好waitUntiDone设为NO, 我可以理解， 但是我试了一下设为YES后也能正常工作， 这是为什么， 
如果设为YES, @selector(fd_precacheIndexPathIfNeeded:)在runloop休眠之前就会执行，这样就不会再唤醒runloop
这是我的理解，可能有偏差，求指点

**Comment by yunyu2014** [comment]
[self performSelector:@selector(fd_precacheIndexPathIfNeeded:)
                 onThread:[NSThread mainThread]
               withObject:indexPath
            waitUntilDone:NO
                    modes:@[NSDefaultRunLoopMode]];

这个方法在runloop即将休眠的时候会调用， 这时候runloop并不在休眠状态，

求指点

**Comment by Coder-XL** [comment]
我不是作者，我也不懂




------------------ 原始邮件 ------------------
发件人: "GaoYuJian";<notifications@github.com>;
发送时间: 2015年8月14日(星期五) 下午4:41
收件人: "forkingdog/UITableView-FDTemplateLayoutCell"<UITableView-FDTemplateLayoutCell@noreply.github.com>; 

主题: Re: [UITableView-FDTemplateLayoutCell]  请教一个问题，runloop怎么被不断唤醒呢，一次runloop周期运行完后处于休眠状态，怎么不断唤醒去执行预缓存高度任务呢 (#73)




[self performSelector:@selector(fd_precacheIndexPathIfNeeded:)
                  onThread:[NSThread mainThread]
                withObject:indexPath
             waitUntilDone:NO
                     modes:@[NSDefaultRunLoopMode]];
 
这个方法在runloop即将休眠的时候会调用， 这时候runloop并不在休眠状态，
 
求指点

**Comment by Coder-XL** [comment]
sorry,I don't know






------------------ 原始邮件 ------------------
发件人: "GaoYuJian";<notifications@github.com>;
发送时间: 2015年8月14日(星期五) 下午4:41
收件人: "forkingdog/UITableView-FDTemplateLayoutCell"<UITableView-FDTemplateLayoutCell@noreply.github.com>; 

主题: Re: [UITableView-FDTemplateLayoutCell]  请教一个问题，runloop怎么被不断唤醒呢，一次runloop周期运行完后处于休眠状态，怎么不断唤醒去执行预缓存高度任务呢 (#73)




Reopened #73.

**Comment by sunnyxx** [comment]
这个调用创建一个 source 0 任务，加入到要 run loop 的队列中，**而 source 0 本身就会唤醒该 run loop**

**Comment by yunyu2014** [comment]
如果run loop本身没有休眠呢， 这时self performSelector:@selector(fd_precacheIndexPathIfNeeded:)
onThread:[NSThread mainThread]
withObject:indexPath
waitUntilDone:NO
modes:@[NSDefaultRunLoopMode]];

是怎么执行的
