### ISSUE TITLE
iOS8.4下cell.contentView.constraints为空

### ISSUE THREAD

**Issue by Vernsu** [forkingdog/UITableView-FDTemplateLayoutCell#74]
使用xib布局的，用 registerNib:forCellReuseIdentifier:注册了Cell 
计算高度时，`UITableView-FDTemplateLayoutCel`里判断是否用了AutoLayout的代码：
`BOOL autoLayoutEnabled = cell.contentView.constraints.count > 0 && !cell.fd_enforceFrameLayout; `
So,提示：
`NSAssert(NO, @"Customized cell must override '-sizeThatFits:' method if not using auto layout.");`
iOS7.1下正常
@sunnyxx

**Comment by sunnyxx** [comment]
将在新版本去除这个判断，由 `fd_enforceFrameLayout` 控制

**Comment by sunnyxx** [comment]
而且很有可能因为开了 SizeClasses
