### ISSUE TITLE
ios6下自动计算高度不对(有自适应高度的label)

### ISSUE THREAD

**Issue by t3239658** [forkingdog/UITableView-FDTemplateLayoutCell#75]
iOS6下如果有Label，这个label的高度根据填充内容变化，距离上下左右的约束都设置好了，autolayout的情况下，计算出来的高度有问题？看了官方的demo，需要iOS7以上才能运行，暂时的解决办法只能判断如果是iOS6下就手动计算。希望大神能解决一下。

**Comment by Coder-XL** [comment]
我也不会，不要再发给我了






------------------ 原始邮件 ------------------
发件人: "t3239658";<notifications@github.com>;
发送时间: 2015年8月14日(星期五) 下午4:45
收件人: "forkingdog/UITableView-FDTemplateLayoutCell"<UITableView-FDTemplateLayoutCell@noreply.github.com>; 

主题: [UITableView-FDTemplateLayoutCell] ios6下自动计算高度不对(有自适应高度的label) (#75)




iOS6下如果有Label，这个label的高度根据填充内容变化，距离上下左右的约束都设置好了，autolayout的情况下，计算出来的高度有问题？看了官方的demo，需要iOS7以上才能运行，暂时的解决办法只能判断如果是iOS6下就手动计算。希望大神能解决一下。

**Comment by sunnyxx** [comment]
iOS 6 上还是要手动设置下 `preferredMaxLayoutWidth` Label 才知道如何折行。
