### ISSUE TITLE
在SizeClasses为"For all iPhone in Portrait"时crash

### ISSUE THREAD

**Issue by Vernsu** [forkingdog/UITableView-FDTemplateLayoutCell#77]
因为一直用的`For all iPhone in Portrait`
花了很长时间才发现导致crash的原因……
感觉自己autoloayout设置的如此完美，可还是进入
`NSAssert(NO, @"Customized cell must override '-sizeThatFits:' method if not using auto layout.");`
刚开始没有搜到别人遇到过同样的问题，死活找不到原因 ……
fucking dog！

**Comment by Vernsu** [comment]
Size Classes 我没怎么研究过…… 接手项目就一直用的"For all iPhone in Portrait",莫非是我用错了……
iOS7下正常，iOS8下crash
@sunnyxx

**Comment by Vernsu** [comment]
接手项目就一直用的"For all iPhone in Portrait",这个问题好蛋疼
iOS7下正常，iOS8下crash
@sunnyxx

**Comment by rajanbalana1mg** [comment]
I am facing the same problem.

**Comment by sunnyxx** [comment]
Fixed in 1.4, Thanks
