### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by HanYaZhou1990** [forkingdog/UITableView-FDTemplateLayoutCell#78]
如果这个viewController继承自UIViewController毁崩溃，如果继承UITableViewController就没事，这个问题不知道你有没有发现

**Comment by Coder-XL** [comment]
没有用的不多




------------------ 原始邮件 ------------------
发件人: "韩亚周";<notifications@github.com>;
发送时间: 2015年8月24日(星期一) 晚上6:23
收件人: "forkingdog/UITableView-FDTemplateLayoutCell"<UITableView-FDTemplateLayoutCell@noreply.github.com>; 

主题: [UITableView-FDTemplateLayoutCell] crash (#78)




如果这个viewController继承自UIViewController毁崩溃，如果继承UITableViewController就没事，这个问题不知道你有没有发现

**Comment by HanYaZhou1990** [comment]
那我该如何去修复这个问题呢?

**Comment by Coder-XL** [comment]
我也不知道，问作者




------------------ 原始邮件 ------------------
发件人: "韩亚周";<notifications@github.com>;
发送时间: 2015年8月24日(星期一) 晚上6:27
收件人: "forkingdog/UITableView-FDTemplateLayoutCell"<UITableView-FDTemplateLayoutCell@noreply.github.com>; 
抄送: "CoderXL"<1172632508@qq.com>; 
主题: Re: [UITableView-FDTemplateLayoutCell] crash (#78)




那我该如何去修复这个问题呢?

**Comment by sunnyxx** [comment]
和继承自哪里没关系，看看 `register` 的时机吧，越早越好

**Comment by HanYaZhou1990** [comment]
改早一点儿，在创建tableView以后，立即注册就没问题了
