### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Ashleyjwsi** [forkingdog/UITableView-FDTemplateLayoutCell#79]
FDTemplateLayoutCell crashed on going back in navigation history. What to do ? Any help ?

**Comment by ylovern** [comment]
try:
- (void)dealloc{
   _tableview.delegate = nil
}

**Comment by sunnyxx** [comment]
Agree with @ylovern , table view may dealloc slower than its data source and delegate because navigation controller's transition view has a strong reference to it when performing animation.

**Comment by Ashleyjwsi** [comment]
Thanks @ylovern  and @sunnyxx . It works
