### ISSUE TITLE
New pixel logos

### ISSUE THREAD

**Issue by lexrus** [forkingdog/UITableView-FDTemplateLayoutCell#81]
<img width="839" alt="screen shot 2015-08-29 at 10 54 01 pm" src="https://cloud.githubusercontent.com/assets/219689/9562557/9d31d8c2-4ea1-11e5-8abb-a56df55feb17.png">

![8x8_8](https://cloud.githubusercontent.com/assets/219689/9562561/b250d0aa-4ea1-11e5-8b06-e6bd20ac0f2f.png)

![16x16 2_16c](https://cloud.githubusercontent.com/assets/219689/9562563/b2a24ba6-4ea1-11e5-95c0-00c27fe34a93.png)

![16x16_16](https://cloud.githubusercontent.com/assets/219689/9562562/b2a24d4a-4ea1-11e5-83b0-2ee3df068fea.png)

**Comment by sunnyxx** [comment]
💗💗💗💗 Tang
