### ISSUE TITLE
cell中添加了一个UIView，然后会动态往里面添加内容。怎么设置好自动高度了？

### ISSUE THREAD

**Issue by wakaryry** [forkingdog/UITableView-FDTemplateLayoutCell#82]
cell中添加了一个UIView，然后会动态往里面添加内容。怎么做到自适应高度了？添加的内容有多有少。

**Comment by wakaryry** [comment]
我对UIview的内容进行了手动计算，然后其他的地方用的自适应布局的计算结果。cell高度时自适应了，但是表上下滑动会出现内容重叠。

**Comment by mrkey0310** [comment]
这个库是根据你autolayout的constraints来计算高度的，你里面内容及时给View和其内容updateConstraints就可以了

**Comment by wakaryry** [comment]
好的。我现在里面的内容的位置和高度都是手动算的。

**Comment by mrkey0310** [comment]
你需要autolayout做为前提，不然的话，你用这个库是没效果的~不管你里面内容是什么~，

**Comment by wakaryry** [comment]
嗯。谢谢。

**Comment by sunnyxx** [comment]
图片需要有内容才有固有宽度，动态的图片在下载前可能不知道宽高，这就需要向 image view 添加宽和高约束，当知道其大小的时候再设置这两条约束的 constant 值。
