### ISSUE TITLE
如何加载网络图片上 达到你的Demo 的效果

### ISSUE THREAD

**Issue by LanceBinbin** [forkingdog/UITableView-FDTemplateLayoutCell#84]
我把你 的plist 文件的imageName 里面的本地资源改成了 网络图片连接 结果 没有到达预期的效果 

求帮忙 谢谢了

**Comment by HanYaZhou1990** [comment]
我imageview用的是固定高度，算是临时解决，加载网络图片确实存在问题，您时间充足可以研究一下，研究出来望通知一下

发自我的 iPhone

**Comment by LanceBinbin** [comment]
我也不晓得 怎么搞 总是 刷新之后再刷新 一遍才好

**Comment by sunnyxx** [comment]
图片需要有内容才有固有宽度，动态的图片在下载前可能不知道宽高，这就需要向 image view 添加宽和高约束，当知道其大小的时候再设置这两条约束的 constant 值。
