### ISSUE TITLE
fd_precacheIndexPathIfNeeded 导致的crash

### ISSUE THREAD

**Issue by GabrielShiao** [forkingdog/UITableView-FDTemplateLayoutCell#86]
重现方法：
一级页面导航到二级页面，二级页面是用fdtemplatelayoutcell构建的tableview。二级页面进入后会网络请求异步加载显示数据。在网络极快的情况下，进入二级页面马上返回，这个时候会产生crash,定位到fd_precacheIndexPathIfNeeded方法产生的。具体是下面这一行：EXC_BAD_ACCESS

CGFloat height = [self.delegate tableView:self heightForRowAtIndexPath:indexPath]; 

我的回调代码如下：
        WS(ws); //ws是二级页面UIViewController的weak self
        [TJsonServer commentList: [ws.post objectForKey:@"id"]  sinceId:@"0" getNum:20 completion:^(TJsonResponse *jsonResponse) {
            
            [ws.tableView.footer endRefreshing];
            
            if (jsonResponse.success) {
                ws.comments = [jsonResponse.data objectForKey:@"list"];
                
                ws.jsonResponse = jsonResponse;
                
                DDLogDebug(@"comments total %lu", (unsigned long)ws.comments.count);
                
                [ws.tableView reloadData]; //出错在这一行
                
            } else {
                [TInformationView showOn: ws.tableView.superview message:jsonResponse.errorDescription];
            }
            
        }];

我是这么猜测的：
当网络数据返回的时候，UIViewController还存在，所以可以reloadData触发，但是看了您的代码，发现在计算行高的时候，您有这么一段代码：
        [self performSelector:@selector(fd_precacheIndexPathIfNeeded:)
                     onThread:[NSThread mainThread]
                   withObject:indexPath
                waitUntilDone:NO
                        modes:@[NSDefaultRunLoopMode]];
这块变成了异步执行，这个是不是就变得不可靠了，可能在执行的时候，UIViewController已经返回析构掉了。

我是这么猜的，也可能我那里写的不对。计算行高的代码我是这么写的：
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    

        return [tableView fd_heightForCellWithIdentifier:@"TPhotoDetailCommentCell" cacheByIndexPath:indexPath configuration:^(TPhotoDetailCommentCell *cell) {
            [self configureCommentCell:cell atIndexPath:indexPath];
        }];
    
}

2015-09-08  10：12 添加日志截屏：
我打开了日志，发现点进页面马上返回崩溃，是加载了一部分数据（总共20条数据）。感觉加载了一部分数据，由于页面析构了，但是fd框架还引用着这个tableview，所以发生了错误？
![fdtemplatecell_error](https://cloud.githubusercontent.com/assets/2384004/9725007/517d29f4-5612-11e5-8e73-6d28e02264d3.png)

我将- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath 高度计算硬编码返回60（仅测试目的，实际cell高度是不定的），基本上就不会出现这个问题了，很多次才能试验出一次崩溃，看了代码才发现，reload被swizzle了，好厉害。reload会将所有cell高度重新cache一遍，是不是因为异步执行，导致崩溃的？

2015-09-08 10：57添加：
打开zombie enabled，crash在同一行代码，得到如下日志：
![ae4523e4-6fc6-4ef5-9b80-59f37f0abb48](https://cloud.githubusercontent.com/assets/2384004/9725621/b264fc0e-5619-11e5-8383-cf75764cc1cc.png)

TPhotoDetailTableViewController是这个tableview的delegate，是不是这里需要增加self.delegate是否存在的逻辑？

**Comment by GabrielShiao** [comment]
我先临时规避了这个问题，在tableview controller析构的时候:
self.tableview.delegate= nil; 

不过这个不是一个好的方法，希望框架能够解决掉。

**Comment by sunnyxx** [comment]
你好，首先感谢 Issue，很详尽。这是个 UITableView 一直有的问题，本质原因是 UITableView 的 data source 和 delegate 都是 assign 而非 weak （iOS 9 SDK 中刚刚变成的 weak），这就导致 Controller 析构后，delegate 野指针，同时，由于返回时 table view 在跟随 UINavigationController 的 transition view 做动画，所以延迟了析构，若此时触发了数据源，就会 crash。precache 可能会增加遇到的概率，在刚刚更新的 1.4 版本中，我去掉了 precache 的功能，它的收益没有我想象的大。所以使用 iOS 9 SDK + 最新的 1.4 release，这个问题应该就可以消除了。
