### ISSUE TITLE
麻烦作者支持一下carthage吧

### ISSUE THREAD

**Issue by cbahai** [forkingdog/UITableView-FDTemplateLayoutCell#88]
如题。。。

**Comment by renkai19880205** [comment]
我开了个Fork支持了carthage，已经向这个项目提交了pr，你可以先用我的Fork上的carthage分支，https://github.com/renkai19880205/UITableView-FDTemplateLayoutCell

**Comment by sunnyxx** [comment]
已经 merge 谢谢
