### ISSUE TITLE
当TableView 为自定义宽度(宽度不为屏幕宽度时)，计算的高度不符合

### ISSUE THREAD

**Issue by liwenDeng** [forkingdog/UITableView-FDTemplateLayoutCell#89]
使用Masonry 布局设置的约束，当把tableView 的宽度设置为非屏幕宽度时，计算出来的cell 高度不符合，并且Masonry会报错；个人感觉好像是计算高度时都是默认cell 的宽度为屏幕宽度？

**Comment by bottotl** [comment]
孙源在博客上有说明：
同时，工具也顺手解决了-preferredMaxLayoutWidth的问题，在计算高度前向 contentView 加了一条和 table view 宽度相同的宽度约束，强行让 contentView 内部的控件知道了自己父 view 的宽度，再反算自己被外界约束的宽度，破除“鸡生蛋蛋生鸡”的问题，这里比较 tricky，就不展开说了。

**Comment by sunnyxx** [comment]
扣的宽约束是 tableView 的 width，没有和屏幕宽度耦合。你可以再详细说下问题，看是哪里出错了。

**Comment by sunnyxx** [comment]
先 close，还有问题再 open
