### ISSUE TITLE
只能显示部分图片

### ISSUE THREAD

**Issue by lcddhr** [forkingdog/UITableView-FDTemplateLayoutCell#9]
![2015-04-26 6 00 27](https://cloud.githubusercontent.com/assets/4919222/7336738/e361d84e-ec3e-11e4-9b8f-2c60909af4de.png)
iphone5模拟器跑的，tableView图片只有部分与json里面数据对上

**Comment by sunnyxx** [comment]
deploy小于8.0时，jpg格式不认，现在已经把Demo中图片都改成png了，谢谢。
