### ISSUE TITLE
 使用storyboard添加的约束，但是cell.contentView.constraints.count为0

### ISSUE THREAD

**Issue by TrackyTian** [forkingdog/UITableView-FDTemplateLayoutCell#91]
使用storyboard添加的约束，但是cell.contentView.constraints.count为0，完全按照你的Demo做的，一模一样的约束，但是为什么你的不为0，我的却为0啊

**Comment by sunnyxx** [comment]
Size Classes

**Comment by TrackyTian** [comment]
如果不去掉size classes怎么解决这个问题！

**Comment by sunnyxx** [comment]
下个版本会去掉那个判断

**Comment by TrackyTian** [comment]
我试着去掉那么判断也不对，因为如果使用了size classes就获取不到约束了，是不是其他也要改

**Comment by sunnyxx** [comment]
估计是你的 Size Classes 设置的不对，是不是约束只 install 在某种特定 Size Class 上了，如果没真用到，还是不建议用

**Comment by TrackyTian** [comment]
是的啊！我只用到了iPhone通用上，没有包括iPad
