### ISSUE TITLE
大神我想问您一个问题，困扰我两天了一直没人请教

### ISSUE THREAD

**Issue by TrackyTian** [forkingdog/UITableView-FDTemplateLayoutCell#93]
我自定义的cell，如果慢慢滑动屏幕，显示正常，但是如果滑动的快了，一些cell就显示错乱了。怎么回事啊

这是controller文件

```
- (void)viewDidLoad {
    [super viewDidLoad];
    [self.tableView registerNib:[UINib nibWithNibName:@"MyTableViewCell" bundle:nil] forCellReuseIdentifier:@"cell"];
    self.tableView.estimatedRowHeight = 200;
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.allowsSelection = NO;
    self.tableData = @[@"1\n2\n3\n4\n5\n6", @"123456789012345678901234567890", @"1\n2", @"1\n2\n3", @"1", @"1\n2\n3\n4\n5\n6", @"123456789012345678901234567890", @"1\n2", @"1\n2\n3", @"1", @"1\n2\n3",@"1\n2\n3"];
}


-(NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 1;
}

-(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return self.tableData.count;
}

-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    MyTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"cell"];
    
    cell.textView.text = self.tableData[indexPath.row];
   
    cell.isShowView = YES;
    cell.button.hidden = NO;
    cell.intextView.hidden = NO;
    if(indexPath.row % 2 == 0) {
        cell.isShowView = NO;
        cell.button.hidden = YES;
        cell.intextView.hidden = YES;
    }
    
    [cell setNeedsUpdateConstraints];
    [cell updateConstraintsIfNeeded];

    return cell;

}
```

这是自定义cell文件

```
- (void)awakeFromNib {
    self.isShowView = YES;
}

-(void)updateConstraints {
    
    if(self.isShowView == NO) {
        [self.content mas_makeConstraints:^(MASConstraintMaker *make) {
            make.height.equalTo(@0);
        }];
        NSLog(@"self.isShowView == NO");
    }

    
    [super updateConstraints];
}
```

正常的时候：

![](http://cl.ly/image/1t0g2X1P1Q3K/85375F0C-32BD-4DE9-BFB7-34D4A19C90FA.png)

快读滑动的时候：

![](http://cl.ly/image/350l3P2g2c2Q/A83A3344-B02B-4ECD-A063-F401D0354E9D.png)

**Comment by doyanaml** [comment]
Hi 田腾飞,


你的这个问题解决了么？
我看了下你的代码，发现有个问题，
-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    MyTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"cell"];   // 这里cell可能回nil, 你应该用MyTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"cell" forIndexParth:(NSIndexPath *)];
如果可以的话，可以把代码给我打包发一下，我看看。

在 2015-09-17 19:48:38，"田腾飞" <notifications@github.com> 写道：


我自定义的cell，如果慢慢滑动屏幕，显示正常，但是如果滑动的快了，一些cell就显示错乱了。怎么回事啊

这是controller文件

- (void)viewDidLoad {
    [super viewDidLoad];
    [self.tableView registerNib:[UINib nibWithNibName:@"MyTableViewCell" bundle:nil] forCellReuseIdentifier:@"cell"];
    self.tableView.estimatedRowHeight = 200;
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.allowsSelection = NO;
    self.tableData = @[@"1\n2\n3\n4\n5\n6", @"123456789012345678901234567890", @"1\n2", @"1\n2\n3", @"1", @"1\n2\n3\n4\n5\n6", @"123456789012345678901234567890", @"1\n2", @"1\n2\n3", @"1", @"1\n2\n3",@"1\n2\n3"];
}


-(NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 1;
}

-(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return self.tableData.count;
}

-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    MyTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"cell"];

    cell.textView.text = self.tableData[indexPath.row];

    cell.isShowView = YES;
    cell.button.hidden = NO;
    cell.intextView.hidden = NO;
    if(indexPath.row % 2 == 0) {
        cell.isShowView = NO;
        cell.button.hidden = YES;
        cell.intextView.hidden = YES;
    }

    [cell setNeedsUpdateConstraints];
    [cell updateConstraintsIfNeeded];

    return cell;

}


这是自定义cell文件

- (void)awakeFromNib {
    self.isShowView = YES;
}

-(void)updateConstraints {

    if(self.isShowView == NO) {
        [self.content mas_makeConstraints:^(MASConstraintMaker *make) {
            make.height.equalTo(@0);
        }];
        NSLog(@"self.isShowView == NO");
    }


    [super updateConstraints];
}


正常的时候：

快读滑动的时候：

**Comment by sunnyxx** [comment]
@doyanaml 若已经成功注册 cell，那个调用并不会返回 nil。

**Comment by sunnyxx** [comment]
@TrackyTian 你在 cell 的 updateConstraints 里面添加约束，但是进入重用后并没有等效的移除约束，这就导致这条约束一遍一遍的被添加了很多次。

**Comment by TrackyTian** [comment]
谢谢大家  我已经解决了
