### ISSUE TITLE
demo中的cell约束并没有添加完全，有很多系统的警告，为何不会影响到高度的计算？？

### ISSUE THREAD

**Issue by 03128crz** [forkingdog/UITableView-FDTemplateLayoutCell#95]
<img width="641" alt="2015-09-24 2 22 14" src="https://cloud.githubusercontent.com/assets/3424553/10066667/b24e728a-62c7-11e5-9549-a7ddce8f18d0.png">

**Comment by sunnyxx** [comment]
在 superView 被压迫或拉大时，子视图间需要“决斗”出一个最弱的“欺负”，去压缩或拉大那个最弱的，抗压和抱团系数就是在这个情况下起作用。这个爆红不是约束没设置全，是 IB 中 cell 模拟的高度没设置对，不会影响 runtime 时的效果。

**Comment by 03128crz** [comment]
谢谢，请问这些知识可以从哪儿获取，有相关的链接吗？
