### ISSUE TITLE
Crash after popViewControllerAnimated

### ISSUE THREAD

**Issue by oney** [forkingdog/UITableView-FDTemplateLayoutCell#97]
Even I set tableView's delegate and dataSource to nil, the app still crashes after `self.navigationController?.popViewControllerAnimated(true)`

```
deinit {
    tableView.delegate = nil
    tableView.dataSource = nil
}
```

It only happened in iOS 9, not happened in iOS 8

**Comment by sunnyxx** [comment]
Any crash stack?

**Comment by weekwood** [comment]
closed cause no response
