### ISSUE TITLE
separatorHeight

### ISSUE THREAD

**Issue by MickeyHub** [forkingdog/UITableView-FDTemplateLayoutCell#99]
From `FDTemplateLayoutCell.m line:106`

```objc
// Add 1px extra space for separator line if needed, simulating default UITableViewCell.
    if (self.separatorStyle != UITableViewCellSeparatorStyleNone) {
        fittingSize.height += 1.0 / [UIScreen mainScreen].scale;
    }
```

but separatorHeight is 1dot rather than 1px, below is iPhone6's inspection from Reveal.app

![image](https://cloud.githubusercontent.com/assets/5426838/10117691/f2f05e2c-6491-11e5-9849-1f9e5287dea6.png)

**Comment by sunnyxx** [comment]
Maybe I should use a private property of UITableViewCell:
``` objc
CGFloat separatorHeight = [[templateLayoutCell valueForKey:@"_separatorHeight"] doubleValue];
```
It's how system's self-sizing cell calculates its separatorHeight.
